Check length to avoid XSTRNCMP accessing  memory after `list`
wolfSSL/wolfssl pull request #2842
Opened 2020-03-06 16:15 UTC by julek-wolfssl

2020-03-08 22:28 UTC, SparkiDev requested changes
We don't want to increase the size of

2020-03-08 22:28 UTC, SparkiDev commented on wolfssl/internal.h
> +    size_t name_len;
Leave this as an int.
We don't want to increase structure sizes unnecessarily.

2020-04-02 22:38 UTC, SparkiDev approved these changes

2020-04-07 20:02 UTC, toddouska approved these changes

2020-04-07 20:02 UTC, merged