Added unit test for evp.c
wolfSSL/wolfssl pull request #3387
Opened 2020-10-13 20:56 UTC by ethanlooney

2020-10-22 18:46 UTC, ejohnstown commented
retest this please

2020-11-06 20:27 UTC, cconlon requested changes

2020-11-06 20:27 UTC, cconlon commented on tests/api.c
> +    AssertIntEQ(wolfSSL_EVP_PKEY_base_id(pkey), 6);
Let's replace "6" with a meaningful enum/define value

2020-11-06 20:27 UTC, cconlon commented on tests/api.c
> +    AssertIntEQ(wolfSSL_EVP_PKEY_id(pkey), 6);
Same as above, please replace "6" with a meaningful enum/define.  We try our best to avoid using "magic numbers" when possible.

2020-11-06 20:27 UTC, cconlon commented on tests/api.c
> +    EVP_CIPHER_CTX *ctx = EVP_CIPHER_CTX_new();
We try to declare all variables at the top of a function.  Can you move the declaration of "EVP_CIPHER_CTX* ctx = NULL" to the top of the function, then only assign/initialize it here?

2020-11-06 20:27 UTC, cconlon commented on tests/api.c
> +    EVP_CIPHER_CTX *ctx = EVP_CIPHER_CTX_new();
We try to declare all variables at the top of a function.  Can you move the declaration of "EVP_CIPHER_CTX* ctx = NULL" to the top of the function, then only assign/initialize it here?  Same applies to "const EVP_CIPHER* init" on the line below.

2020-11-06 20:27 UTC, cconlon commented on tests/api.c
> +   !defined(NO_DES3)
Please remove duplicate "!defined(NO_DES3)" here, thanks

2020-11-06 20:27 UTC, cconlon commented on tests/api.c
> +    EVP_CIPHER_CTX *ctx = EVP_CIPHER_CTX_new();
Please move declarations of variables to top of function, thanks.  Applies to EVP_CIPHER_CTX and const EVP_CIPHER.

2020-11-06 20:27 UTC, cconlon commented on tests/api.c
> +    WOLFSSL_ENGINE* e = 0;
To match consistency in the library, can you initialize your WOLFSSL_ENGINE pointer to NULL instead of 0?

2020-11-06 20:27 UTC, cconlon commented on tests/api.c
> +    AssertNotNull(wolfSSL_EVP_get_digestbynid(4)); /* NID_md5 */
Let's use the NID enum values here (ex: NID_md5, etc) instead of hard-coded numbers (ex: 4).  Also applies to next two lines.

2020-11-06 20:27 UTC, cconlon commented on tests/api.c
> +#if !defined(HAVE_FIPS) || (defined(HAVE_FIPS_VERSION) && (HAVE_FIPS_VERSION>2))
For consistency, please add a some spaces around the ">" in "HAVE_FIPS_VERSION>2".

2020-11-06 20:27 UTC, cconlon commented on tests/api.c
> +   !defined(NO_DES3)
Please remove duplicate "!defined(NO_DES3)"

2020-11-10 20:27 UTC, cconlon approved these changes

2020-11-10 20:27 UTC, merged