Apache httpd w/TLS 1.3 support
wolfSSL/wolfssl pull request #3421
Opened 2020-10-23 19:16 UTC by dgarske

* Add support for TLS v1.3 compatibility API `SSL_verify_client_post_handshake` for the server-side to support rehandshake (Required for Apache v2.4.39 with TLS v1.3)
* Add `OPENSSL_init_crypto` and `OPENSSL_init_ssl` API's.

2020-10-26 00:05 UTC, SparkiDev requested changes
Rest is fine.

2020-10-26 00:05 UTC, SparkiDev commented on src/ssl.c
> +    if (ssl->options.side == WOLFSSL_CLIENT_END) {
OpenSSL returns an error when client side.

2020-10-26 00:05 UTC, SparkiDev commented on src/ssl.c
> +/* For TLS v1.3 perform rehandshake. Returns 1=WOLFSSL_SUCCESS or 0=WOLFSSL_FAILURE */
Not a rehandshake - sending handshake messages after handshake complete.

2020-10-26 00:05 UTC, SparkiDev commented on src/ssl.c
> +        ret = wolfSSL_allow_post_handshake_auth(ssl);
Looks like SSL_[CTX_]set_post_handshake_auth() enables/disables.

2020-11-05 00:02 UTC, haydenroche5 commented on src/ssl.c
> +void wolfSSL_CTX_set_post_handshake_auth(WOLFSSL_CTX* ctx, int val)
I think the return type should be int for this guy and wolfSSL_set_post_handshake_auth.

2020-11-06 18:14 UTC, merged