CMake improvements
wolfSSL/wolfssl pull request #3425
Opened 2020-10-26 19:41 UTC by haydenroche5

- Begin adding options to enable/disable different features.
- Increase minimum CMake version to 3.2.
- Support installation of the built files.
- Add checks for necessary include files, functions etc.
- Generate options.h and config.h.

2020-10-27 15:57 UTC, dgarske requested changes
Hey Hayden,

Looks like you'll need to add `cmake/config.in` and `cmake/functions.cmake` to Makefile.am.

Please document the Cmake arguments somewhere... and add example for use in INSTALL. Also let's keep the cmake variable cache simple like `-DARC4=1`.

Thanks

2020-10-27 15:57 UTC, dgarske commented on CMakeLists.txt
> +# Build Unit Tests
The `--disable-examples` option disables the unit test as well.

2020-11-06 21:52 UTC, haydenroche5 commented on CMakeLists.txt
> +# Build Unit Tests
Got it, fixed.

2020-11-06 21:53 UTC, haydenroche5 commented
> Hey Hayden,
> 
> Looks like you'll need to add `cmake/config.in` and `cmake/functions.cmake` to Makefile.am.
> 
> Please document the Cmake arguments somewhere... and add example for use in INSTALL. Also let's keep the cmake variable cache simple like `-DARC4=1`.
> 
> Thanks

Seeing as there's no --help option-type thing for CMake, I've pointed users to cmake-gui  and CMakeCache.txt for documentation on what the various configuration options are and what they do in INSTALL. Definitely open to other ideas for how to make these options more visible, if you have any ideas.

2020-11-10 20:34 UTC, dgarske requested changes
@haydenroche5  Wow, awesome work on this. 

A couple of notes and items to consider before its gets merged:
1) If there were previously a cmake . done in the root then CMakeFiles and CMakeCache.txt need removed otherwise it will report "In-source builds are not allowed.".

2) Can we better document an example for enable/disable options? Such as disabling DH `cmake .. -DWOLFSSL_DH=no` and note the build file `wolfssl/options.h` is still generated and can be included in end application.

3) Let's consider putting the final applications in the same place autoconf does. As long as a make clean will remove those we should be fine.

Thanks! David

2020-11-13 17:27 UTC, haydenroche5 commented
> @haydenroche5 Wow, awesome work on this.
> 
> A couple of notes and items to consider before its gets merged:
> 
> 1. If there were previously a cmake . done in the root then CMakeFiles and CMakeCache.txt need removed otherwise it will report "In-source builds are not allowed.".
> 2. Can we better document an example for enable/disable options? Such as disabling DH `cmake .. -DWOLFSSL_DH=no` and note the build file `wolfssl/options.h` is still generated and can be included in end application.
> 3. Let's consider putting the final applications in the same place autoconf does. As long as a make clean will remove those we should be fine.
> 
> Thanks! David

Thanks for the feedback, David.

1. Annoyingly, CMake creates that directory and file after CMakeLists.txt execution ends, so I can't clean them up in the CMakeLists.txt. I've modified the error message to let the user know that they need to delete these manually if they try an in-source build. See https://medium.com/@qwertie/cmake-fights-against-disabling-in-source-builds-ab1d71c1d26f.
2. I've added additional documentation to INSTALL to make this stuff more clear. Let me know if you think it should go elsewhere, though.
3. Done!

2020-11-13 20:32 UTC, dgarske approved these changes
Perfect! Excellent CMake additions. One Jenkins is working we can get this merged.

2020-11-14 16:35 UTC, merged