TraceSetNamedServer() null arg warning fix
wolfSSL/wolfssl pull request #3480
Opened 2020-11-09 17:26 UTC by douzzer

src/sniffer.c: guard against null arguments to `TraceSetNamedServer()`, to eliminate `-Werror=format-overflow=` warnings from gcc.

redo of PR #3477 , which had a branch name with "warning" in it, which breaks the CI script algorithm (global searches on build outputs for "warning").

2020-11-09 18:20 UTC, dgarske approved these changes

2020-11-10 16:28 UTC, ejohnstown requested changes

2020-11-10 16:28 UTC, ejohnstown commented on src/ssl.c
> +#ifdef HAVE_FIPS
The more rigorous check for possible primality was added for FIPSv2. This should be

    #if defined(HAVE_FIPS_VERSION) && (HAVE_FIPS_VERSION >= 2)

2020-11-10 16:28 UTC, ejohnstown commented on src/ssl.c
> +#ifdef HAVE_FIPS
Same as above.

2020-11-10 16:41 UTC, ejohnstown commented on src/ssl.c
> +#ifdef HAVE_FIPS
The lower level function this calls for the key generation is switching on HAVE_FIPS. this is fine. If they are using FIPSv1, that isn't going to return the random error anyway.

2020-11-10 16:41 UTC, ejohnstown approved these changes

2020-11-10 17:37 UTC, dgarske approved these changes

2020-11-10 17:37 UTC, dgarske commented on scripts/external.test
> +	    echo 'skipping WOLFSSL_EXTERNAL_TEST because -DWOLFSSL_SNIFFER configuration of build is incompatible.'
I will look into this separately. This test should work with the sniffer build option enabled. The cipher suite can be provided explicitly for the external test and it won't use the static RSA cipher suite.

2020-11-10 17:37 UTC, merged