return err from fp_invmod_slow() when fp_add() fails
wolfSSL/wolfssl pull request #3511
Opened 2020-11-18 17:32 UTC by cconlon

This PR is related to ZD 11268.

In scenarios where FP_MAX_BITS is not set high enough, fp_add() can fail with an error return value due to FP_SIZE not being large enough.  This PR adjusts fp_invmod_slow() to correctly propagate that error to the caller instead of returning FP_OKAY.

2020-11-18 22:08 UTC, SparkiDev commented
Two more instances further down in the function.
Otherwise is good.

2020-11-18 22:09 UTC, SparkiDev requested changes
Two more instances further down in the function.
Otherwise is good.

2020-11-18 23:54 UTC, SparkiDev approved these changes

2020-11-25 23:41 UTC, toddouska approved these changes

2020-11-25 23:41 UTC, merged