Port for RT-Thread
wolfSSL/wolfssl pull request #3543
Opened 2020-12-07 08:27 UTC by WKJay

2020-12-09 18:29 UTC, dgarske commented
Hi @WKJay , thanks for the RTOS port to rt-thread.org. In order to accept code contributions we need a signed contributor agreement. Can you please email support@wolfssl.com and reference this PR along with your contact information? Okay to test.

Thanks,
David Garske, wolfSSL

2020-12-09 23:40 UTC, WKJay commented
Hi @dgarske 

I have sent the email, please check.

Thanks,
Jay

2020-12-17 00:05 UTC, tmael reviewed
Looks good. Can you add the new files in wolfssl/IDE/include.am?

2020-12-17 00:09 UTC, dgarske requested changes
Please add the new files as `EXTRA_DIST` to `include.am`. You can create one in `IDE/ECLIPSE/RTTHREAD`. See other include.am files for template. Then add it to the `IDE/include.am`.

2020-12-17 00:09 UTC, dgarske commented on IDE/ECLIPSE/RTTHREAD/README.md
> +### `WOLFSSL_BENCHMARK_TEST` output of benchmark_test()
Can you include the hardware and compiler / optimization level used for this benchmark?

2020-12-17 00:09 UTC, dgarske commented on IDE/ECLIPSE/RTTHREAD/user_settings.h
> +#define CURRENT_UNIX_TS 1542605837
Should this be `1542605837UL`?

2020-12-17 00:09 UTC, dgarske commented on IDE/ECLIPSE/RTTHREAD/wolfssl_test.c
> +     wolfcrypt_test(NULL);
Consider adding `#ifdef` for `NO_CRYPT_TEST` and `NO_CRYPT_BENCHMARK`.

2020-12-17 01:02 UTC, WKJay commented
@dgarske  I've updated the PR, please check. Thanks

2020-12-17 01:05 UTC, tmael approved these changes

2020-12-17 01:17 UTC, dgarske approved these changes
Thanks! Over to Todd for final review

2020-12-17 16:35 UTC, toddouska approved these changes

2020-12-17 16:36 UTC, merged