Check shift value
wolfSSL/wolfssl pull request #3552
Opened 2020-12-09 23:11 UTC by tmael

This fix makes clang with -fsanitize=undefined build happy.

ZD#11372
Thanks Guido Vranken for the report!

2020-12-09 23:18 UTC, SparkiDev commented on wolfcrypt/src/tfm.c
> +  x = DIGIT_BIT - b;
x = DIGIT_BIT - (b % DIGIT_BIT)
When x == DIGIT_BIT then don't do masking.

2020-12-10 01:11 UTC, tmael commented on wolfcrypt/src/tfm.c
> +  x = DIGIT_BIT - b;
@SparkiDev. Fixed. Thanks!!

2020-12-10 22:38 UTC, SparkiDev approved these changes

2020-12-10 22:39 UTC, SparkiDev requested changes
Same code in integer.c.
Fix there too.

2020-12-11 00:19 UTC, SparkiDev approved these changes

2020-12-11 00:19 UTC, merged