Alert Fixes
wolfSSL/wolfssl pull request #3554
Opened 2020-12-10 16:55 UTC by ejohnstown

When the server cannot match the client's identity, the server sends a unknown_psk_identity alert to the client. (ZD 11230)

2020-12-14 18:49 UTC, dgarske requested changes
@ejohnstown I suspect we don't send this alert to avoid leaking PSK failure information (padding vs key failures). You might need to confirm with Sean or Todd on that. If the customer needs this then can we wrap this in a build option?

2020-12-14 19:47 UTC, ejohnstown commented
I'll add the wrapper then. That's a good idea.

2020-12-14 22:39 UTC, SparkiDev commented
Wrap them with: WOLFSSL_EXTRA_ALERTS

2020-12-15 01:11 UTC, dgarske approved these changes

2020-12-15 22:49 UTC, dgarske reviewed
I approve the extra alert change. Moving the `SetKeysSide` from `SendFinished` to `SendChangeCipher` seems risky. @SparkiDev , what are your thoughts?

2020-12-15 23:38 UTC, SparkiDev approved these changes

2020-12-15 23:39 UTC, SparkiDev commented
Looks like the right thing to do, set ETM in SendChangeCipher as Finished is encrypted.

2020-12-15 23:40 UTC, merged