SESSION mutex: copying a session overwrote mutex
wolfSSL/wolfssl pull request #3562
Opened 2020-12-13 23:13 UTC by SparkiDev

New session creation function, NewSession, that doesn't initialize
mutex.
Calling functions, wolfSSL_SESSION_new() and wolfSSL_SESSION_copy(),
initialize the mutex.

2020-12-14 23:48 UTC, toddouska requested changes

2020-12-14 23:48 UTC, toddouska commented on src/ssl.c
> +    if (wc_InitMutex(&ret->refMutex) != 0) {
Needs memory failure check before dereference.

2020-12-15 00:00 UTC, SparkiDev commented on src/ssl.c
> +    if (wc_InitMutex(&ret->refMutex) != 0) {
Added check.

2020-12-15 16:50 UTC, toddouska approved these changes

2020-12-15 16:50 UTC, merged