Base64: Cache attack resistant decode
wolfSSL/wolfssl pull request #3563
Opened 2020-12-14 02:33 UTC by SparkiDev

2020-12-14 19:01 UTC, dgarske requested changes
Just one minor feedback item re `b64_idx`. Also can you add a note at top of coding.c with new `BASE64_NO_TABLE` build option?

2020-12-15 01:09 UTC, dgarske approved these changes

2020-12-15 16:48 UTC, dgarske approved these changes

2020-12-15 23:16 UTC, toddouska approved these changes

2020-12-15 23:16 UTC, merged