Fix SP integer square
wolfSSL/wolfssl pull request #3608
Opened 2020-12-31 00:16 UTC by tmael

This PR corrects an SP math issue found by Guido Vranken. ZD# 11439.

computing x*x mod m was producing incorrect results.  

Here's an example. 
x = "d7c134aa264366862a18302575d0fb98d116bc4b6ddebca3a5a7939f"
m = "d3537bed3acf18aba4e6d6f98f049912e6c22bffdd5ea02638da5f617cf03a1f7d5a224c88208d8000000000000000000000000000000003"

`x*x % m` now produces:
 B5D618463FA8787829E2D8CFE7D83C231C9599B9D50A9B50A1A4859618B4F8FE4076F69A02390444E02F8047403ACD6DED2CF676E491FCC1

Previously it was producing:

"FFFFFFFFFFFFFFFFE2829C5904D95FCC84FC01D658D3A31035D36DB9F7ABFB2A68CA26349BC4BEDEC31CD44D7A1876C4E02F8047403ACD6DED2CF676E491FCBE"

 The most common _sp_sqr_4() function has the fix, other _sp_sqr_* functions need to be examined.

2020-12-31 23:18 UTC, dgarske requested changes
@tmael , make sure the scripts are updated as well. You may find there are other changes that result from the generated code. I sent you a direct note.

2021-01-04 01:43 UTC, SparkiDev requested changes
This isn't the right fix.
The call to sp_clamp below your changes is meant to take care of the top words.
It is called on t instead of r.
There are other places that need fixing as well.

2021-01-04 05:51 UTC, SparkiDev approved these changes

2021-01-04 05:52 UTC, SparkiDev commented
https://github.com/wolfSSL/scripts/pull/132

2021-01-04 06:29 UTC, merged