Add support for user settings to CMake.
wolfSSL/wolfssl pull request #3617
Opened 2021-01-04 15:43 UTC by haydenroche5

2021-01-04 16:21 UTC, dgarske requested changes
@haydenroche5 , thanks for adding support for this. Can you also update the version number in this file to v4.6.0? I've made sure that release instructions have this noted.

2021-01-04 17:16 UTC, haydenroche5 commented
> @haydenroche5 , thanks for adding support for this. Can you also update the version number in this file to v4.6.0? I've made sure that release instructions have this noted.

Sure, added.

2021-01-04 17:16 UTC, dgarske approved these changes

2021-01-08 18:49 UTC, haydenroche5 commented
I added an option to disable generation of config.h and the defining of HAVE_CONFIG_H. See https://www.wolfssl.com/forums/post5684.html#p5684.

2021-01-08 18:50 UTC, haydenroche5 commented on CMakeLists.txt
> -add_definitions(${WOLFSSL_DEFINITIONS})
This was duplicate code.

2021-01-12 17:58 UTC, haydenroche5 commented
retest this please

2021-01-22 00:21 UTC, merged