EVP: return proper cipher type for AES OFB
wolfSSL/wolfssl pull request #3627
Opened 2021-01-05 21:59 UTC by elms

zd 11463

2021-01-08 13:52 UTC, julek-wolfssl requested changes
Checking the block sizes of the ciphers you added to the `api.c` tests with OpenSSL returned a discrepancy in the CTR modes. We return that the block size is 16 bytes while OpenSSL returns 1 byte. Please correct this in `evp.c` and check the other ciphers we support with `EVP_CIPHER_block_size`. Thanks.

This is the test program I used to check the sizes as returned by OpenSSL.
```
#include <openssl/evp.h>

#define test_blk_size(blk) printf("%s: %d\n", #blk, blk)

void main() {
    test_blk_size(EVP_CIPHER_block_size(EVP_aes_128_cbc()));
    test_blk_size(EVP_CIPHER_block_size(EVP_aes_192_cbc()));
    test_blk_size(EVP_CIPHER_block_size(EVP_aes_256_cbc()));

    test_blk_size(EVP_CIPHER_block_size(EVP_aes_128_gcm()));
    test_blk_size(EVP_CIPHER_block_size(EVP_aes_192_gcm()));
    test_blk_size(EVP_CIPHER_block_size(EVP_aes_256_gcm()));

    test_blk_size(EVP_CIPHER_block_size(EVP_aes_128_ctr()));
    test_blk_size(EVP_CIPHER_block_size(EVP_aes_192_ctr()));
    test_blk_size(EVP_CIPHER_block_size(EVP_aes_256_ctr()));

    test_blk_size(EVP_CIPHER_block_size(EVP_aes_128_ecb()));
    test_blk_size(EVP_CIPHER_block_size(EVP_aes_192_ecb()));
    test_blk_size(EVP_CIPHER_block_size(EVP_aes_256_ecb()));

    test_blk_size(EVP_CIPHER_block_size(EVP_aes_128_ofb()));
    test_blk_size(EVP_CIPHER_block_size(EVP_aes_192_ofb()));
    test_blk_size(EVP_CIPHER_block_size(EVP_aes_256_ofb()));
}
```
And the output:
```
EVP_CIPHER_block_size(EVP_aes_128_cbc()): 16
EVP_CIPHER_block_size(EVP_aes_192_cbc()): 16
EVP_CIPHER_block_size(EVP_aes_256_cbc()): 16
EVP_CIPHER_block_size(EVP_aes_128_gcm()): 1
EVP_CIPHER_block_size(EVP_aes_192_gcm()): 1
EVP_CIPHER_block_size(EVP_aes_256_gcm()): 1
EVP_CIPHER_block_size(EVP_aes_128_ctr()): 1
EVP_CIPHER_block_size(EVP_aes_192_ctr()): 1
EVP_CIPHER_block_size(EVP_aes_256_ctr()): 1
EVP_CIPHER_block_size(EVP_aes_128_ecb()): 16
EVP_CIPHER_block_size(EVP_aes_192_ecb()): 16
EVP_CIPHER_block_size(EVP_aes_256_ecb()): 16
EVP_CIPHER_block_size(EVP_aes_128_ofb()): 1
EVP_CIPHER_block_size(EVP_aes_192_ofb()): 1
EVP_CIPHER_block_size(EVP_aes_256_ofb()): 1
```

2021-01-11 21:28 UTC, elms commented
@julek-wolfssl Thanks for comparing the results. :clap:

2021-01-12 09:14 UTC, julek-wolfssl approved these changes

2021-01-18 23:13 UTC, toddouska approved these changes

2021-01-18 23:13 UTC, merged