Allow wolfSSL_RSA_public_decrypt on Windows.
wolfSSL/wolfssl pull request #3656
Opened 2021-01-15 18:32 UTC by haydenroche5

2021-01-15 19:32 UTC, dgarske requested changes
Also curious if you looked at the other occurrences of `_WIN32` in this file? They seems to be related to `vsnprintf`. Oddly there is a `XSNPRINTF`, which seems to properly handle the Windows side of things. It might be good to look at those while in there testing.

2021-01-15 19:32 UTC, dgarske commented on src/ssl.c
> +#if !defined(HAVE_SELFTEST) && (!defined(HAVE_FIPS) || \
@haydenroche5  Can you also update the comment on the `#endif`? It still has `_WIN32`.

2021-01-15 19:51 UTC, haydenroche5 commented
I'll check out the other _WIN32 instances and fix the #endif comment. Thanks David.

2021-01-15 21:10 UTC, haydenroche5 commented on src/ssl.c
> -    #if defined(OPENSSL_EXTRA) && (!defined(_WIN32) || defined(HAVE_VA_COPY))
Windows has versions of va_copy, vsnprintf, and va_end, so I don't think this needs to be gated on !_WIN32 anymore. The library built fine for me on Windows in Visual Studio. I also built the library in Cygwin and ran the unit tests and those passed.

This was the only instance of HAVE_VA_COPY in the project, so I got rid of it.

2021-01-19 20:20 UTC, haydenroche5 commented
According to [this SO answer](https://stackoverflow.com/a/25827156), the va_* functions are available starting in Visual Studio 2013. I believe we use Visual Studio 11.0, AKA Visual Studio 2012, in the Jenkins "Visual Studio Build Test" (just looking at an example build log), so that would explain why we're seeing a failure here.

@kaleb-himes do you happen to know if there's any particular need to support this older VS version, or if we could upgrade to a more recent one?

2021-01-19 23:23 UTC, kaleb-himes commented
@haydenroche5,

Yes we have customers that use VS 2012 and we retain backwards compatibility for the sake of those users. Some day it will be deprecated but I am not sure when that day will come.

- K

2021-01-20 17:09 UTC, dgarske approved these changes

2021-01-20 17:09 UTC, merged