Added support for AES GCM session ticket encryption
wolfSSL/wolfssl pull request #3660
Opened 2021-01-18 18:35 UTC by dgarske

If ChaCha/Poly is disabled it will use AES GCM (`./configure --enable-session-ticket --disable-chacha && make check`).
@SparkiDev is the author of this AES GCM code. Thanks Sean!
ZD 11511.

2021-01-19 23:34 UTC, SparkiDev requested changes
WOLFSSL_TICKET_IV_SZ should be 12 bytes for AES-GCM.

2021-01-20 00:18 UTC, dgarske commented
> WOLFSSL_TICKET_IV_SZ should be 12 bytes for AES-GCM.

@SparkiDev  At run-time the callback is using 12 bytes for the AES GCM IV. The remaining 4 bytes are just unused and we can keep the session ticket callback from changing.

2021-01-20 00:48 UTC, SparkiDev commented
The 16 bytes are munged down to 12 in the algorithm. Using 16 is just slowing things down.

2021-01-21 23:57 UTC, dgarske commented
> The 16 bytes are munged down to 12 in the algorithm. Using 16 is just slowing things down.

Sean and I had a discussion about the IV size. It doesn't make sense to reduce the IV at build time, since its a callback. It our example that decide if using AES GCM or ChaCha20. Then only the IV needed is generated. The library will have a 16 byte buffer for the IV because of the way the callback is setup.

2021-01-22 01:34 UTC, SparkiDev approved these changes

2021-01-25 22:59 UTC, toddouska approved these changes

2021-01-25 23:00 UTC, merged