SP math: Better error propagation
wolfSSL/wolfssl pull request #3730
Opened 2021-02-06 08:10 UTC by guidovranken

ZD 11650

2021-02-07 03:16 UTC, dgarske commented
OK to test

2021-02-07 22:45 UTC, SparkiDev requested changes

2021-02-07 22:45 UTC, SparkiDev commented on wolfcrypt/src/sp_int.c
> +            if ( err == MP_OKAY ) {
No spaces around condition in brackets.

2021-02-07 23:25 UTC, SparkiDev commented
Thanks Guido!

2021-02-08 04:17 UTC, SparkiDev approved these changes

2021-02-08 04:17 UTC, merged