always check index into certs
wolfSSL/wolfssl pull request #3748
Opened 2021-02-11 14:01 UTC by JacobBarthelmeh

Created for resolving internal fuzzer report. Probably is related also to ZD 11693

2021-02-12 02:14 UTC, miyazakh requested changes
@JacobBarthelmeh : I move the index checking for zd11613 as [PR3732](https://github.com/wolfSSL/wolfssl/pull/3732), down below. I tried this implantation first. However, I was seeing TLS connection failure(-416). Therefore, I move the checking to out of the loop around line#11125. The connection failure can see  by using server-chain.pem and set_verify_depth=0. 

My implementation broke your backward compatibility?

2021-02-12 06:14 UTC, JacobBarthelmeh commented
Hi @miyazakh , before the code goes into the upcoming release the bounds check on reading from "args->certs[args->totalCerts]" or avoiding the read needs to be in place. If the bounds check is removed then there is the chance of an out of bounds read around line 10904.

2021-02-12 08:39 UTC, miyazakh approved these changes

2021-02-14 22:20 UTC, SparkiDev approved these changes

2021-02-14 22:20 UTC, merged