Clean up CMake option strings.
wolfSSL/wolfssl pull request #3820
Opened 2021-02-25 20:58 UTC by haydenroche5

This commit makes all the binary CMake options (i.e. yes/no) conform to one
string convention: "yes/no." Previously, we had a mixture of yes/no and ON/OFF.

2021-02-25 21:38 UTC, elms requested changes
Wondering if we want to add checks for invalid options.

`cmake . -B build -DWOLFSSL_CURVE25519=foo` any value not in the list (or congruent to NO) behaves the same as yes.

2021-02-25 21:38 UTC, elms commented on CMakeLists.txt
> +set(WOLFSSL_ERROR_QUEUE "yes" CACHE STRING ${WOLFSSL_DISABLE_ERROR_QUEUE_HELP_STRING})
```suggestion
set(WOLFSSL_ERROR_QUEUE "yes" CACHE STRING ${WOLFSSL_ERROR_QUEUE_HELP_STRING})
```

2021-02-25 21:43 UTC, haydenroche5 commented
> Wondering if we want to add checks for invalid options.
> 
> `cmake . -B build -DWOLFSSL_CURVE25519=foo` any value not in the list (or congruent to NO) behaves the same as yes.

Yeah, that's a good point. I can create a macro/function to handle options parsing that generates an error if the user-supplied option value isn't in the list of allowed values. The, instead of this 3-line set, set, set_property idiom, we can just use a call to that macro/function. I'll do that today or tomorrow.

2021-02-25 23:03 UTC, haydenroche5 commented
I think we can replace the idiom I mentioned earlier with this function, which will check that the values are in the allowed list:
```
function(add_option NAME HELP_STRING DEFAULT VALUES)
    list(FIND VALUES ${DEFAULT} IDX)
    if (${IDX} EQUAL -1)
        message(FATAL_ERROR "Failed to add option ${NAME}. Default value "
            "${DEFAULT} is not in list of possible values: ${VALUES}.")
    endif()

    list(FIND VALUES ${${NAME}} IDX)
    if (${IDX} EQUAL -1)
        message(FATAL_ERROR "Failed to set option ${NAME}. Value "
            "${${NAME}} is not in list of possible values: ${VALUES}.")
    endif()

    set(${NAME} ${DEFAULT} CACHE STRING ${HELP_STRING})
    set_property(CACHE ${NAME} PROPERTY STRINGS ${VALUES})
endfunction()
```
Example usage:
```
set(WOLFSSL_ASM_HELP_STRING "Enables option for assembly (default: enabled)")
add_option("WOLFSSL_ASM" ${WOLFSSL_ASM_HELP_STRING} "yes" "yes;no")
```
Will modify this PR to do that tomorrow.

2021-03-01 16:41 UTC, elms approved these changes
Looks good.

It is a little different from default cmake convention for binary flags, but I think with the error message it is clear. I could see some initial confusion by some users as it is case-sensitive and won't work with the other cmake binary choices: FALSE/TRUE, 0/1, etc

2021-03-01 17:07 UTC, haydenroche5 commented
> Looks good.
> 
> It is a little different from default cmake convention for binary flags, but I think with the error message it is clear. I could see some initial confusion by some users as it is case-sensitive and won't work with the other cmake binary choices: FALSE/TRUE, 0/1, etc

Agree that it could be confusing initially. This change could also break existing configurations in the wild, but maybe that's ok? I still view our CMake stuff as under development / kind of experimental. So maybe ensuring backwards compatibility with old CMake commands isn't the highest priority.

2021-03-01 17:41 UTC, dgarske approved these changes

2021-03-02 16:55 UTC, merged