Correctly reset the Tx sequence number
wolfSSL/wolfssl pull request #3843
Opened 2021-03-04 11:27 UTC by julek-wolfssl

All DTLS records after the ClientHello should try to start from the sequence number of the ClientHello if it is available.

2021-03-05 21:47 UTC, ejohnstown approved these changes

2021-03-09 16:07 UTC, ejohnstown requested changes
Works correctly. I went back to my network capture and saw what happened. This is definitely the right fix. Thanks!

2021-03-09 17:30 UTC, julek-wolfssl commented on src/internal.c
> +#ifdef WOLFSSL_DTLS
Right. I removed some unnecessary branching as well.

2021-03-09 17:35 UTC, ejohnstown approved these changes

2021-03-09 21:06 UTC, merged