ASN1 Template: stricter and simpler DER/BER parsing/construction
wolfSSL/wolfssl pull request #3869
Opened 2021-03-12 03:22 UTC by SparkiDev

Reduce debug output noise

2021-07-30 19:05 UTC, dgarske approved these changes
I've pushed updates for any issues found. I am happy with the state of it. Most changes are wrapped in the new WOLFSSL_ASN_TEMPLATE macro, which I did all of my testing with and various edge cases. Measured code size difference and almost none (slightly larger in some cases). Over to @ejohnstown

2021-08-16 00:34 UTC, SparkiDev commented on src/ssl.c
> +        /* TODO: test case */
There is a test case now.
Removed comment.

2021-08-16 00:44 UTC, SparkiDev commented on src/ssl.c
> +#ifndef WOLFSSL_ASN_TEMPLATE_SSLC
The ssl.c code got reworked.
I've fixed the code to not require ASN template code in ssl.c anymore.

2021-08-16 06:11 UTC, SparkiDev commented
Rebased and merged all changes.

2021-08-19 00:16 UTC, ejohnstown requested changes

2021-08-19 00:16 UTC, ejohnstown commented on configure.ac
> +AX_COVERAGE
`AX_COVERAGE` isn't defined.

2021-08-19 01:33 UTC, SparkiDev commented on configure.ac
> +AX_COVERAGE
Fixed - removed the lines.

2021-08-19 18:18 UTC, ejohnstown approved these changes

2021-08-19 19:47 UTC, merged