Static analysis fixes for items listed as high priority
wolfSSL/wolfssl pull request #3885
Opened 2021-03-17 10:44 UTC by JacobBarthelmeh

ZD11725

2021-03-24 18:10 UTC, cconlon requested changes

2021-03-24 18:10 UTC, cconlon commented on src/ssl.c
> +    WOLFSSL_MSG("wolfSSL_BN_pseudo_rand");
Should this be WOLFSSL_ENTER?

2021-03-26 22:54 UTC, cconlon commented on src/ssl.c
> +    WOLFSSL_MSG("wolfSSL_BN_pseudo_rand");
Thanks

2021-03-26 22:55 UTC, cconlon approved these changes
Looks good, back to Todd for final review/merge.

2021-03-30 22:59 UTC, toddouska approved these changes

2021-03-30 23:00 UTC, merged