Fix ATECC608A TNGTLS certificate size issue
wolfSSL/wolfssl pull request #3926
Opened 2021-03-27 18:47 UTC by vppillai

TNGTLS devices has shown variations in the device and signer certificate sizes causing failure.
This fix makes the size query dynamic.

I have also updated the I2C address variable name to match the latest release of cryptoauth lib.

@dgarske This is a continuation of the work we did in #3531

2021-04-05 18:36 UTC, dgarske commented
OK to test. Contributor Agreement on File. These changes look good. I will make a few comments.

@vppillai , have you seen our Microchip examples repo here? https://github.com/wolfSSL/microchip-atecc-demos

2021-04-05 18:40 UTC, dgarske requested changes

2021-04-05 18:40 UTC, dgarske commented on wolfcrypt/src/port/atmel/atmel.c
> +    cfg_ateccx08a_i2c_pi.atcai2c.address       = cfg->atcai2c.address;
Is there a way to make this change without breaking compatibility with older ATCA releases? Perhaps there is a macro or version to check for that?

2021-04-05 18:40 UTC, dgarske commented on wolfcrypt/src/port/atmel/atmel.c
> +    printf("ATECC508A Revision: %x\r\n", (word32)revision);
Can you rename this to `"ATECC Revision"`? If the `\r` change is important perhaps update the other ones also otherwise please remove.

2021-04-05 18:40 UTC, dgarske commented on wolfcrypt/src/port/atmel/atmel.c
> +    certBuffer=XMALLOC(signerCertSize+deviceCertSize, NULL, DYNAMIC_TYPE_TMP_BUFFER);
Please add cast `uint8_t*` to avoid come compiler warnings.

2021-04-05 18:40 UTC, dgarske commented on wolfcrypt/src/port/atmel/atmel.c
> +    status = tng_atcacert_read_signer_cert(&certBuffer[deviceCertSize],\
Please remove the trailing `\` in the code changes. That is only required for macros.

2021-04-05 18:40 UTC, dgarske commented on wolfcrypt/src/port/atmel/atmel.c
> +    /*fetch signer cert size*/
For all new comments please add spaces before and after the multi-line comment. Example `/* Fetch signer cert size */`

2021-04-19 16:04 UTC, dgarske commented
Hi @vppillai , I wanted to ping you and make sure you saw the PR feedback comments? Thanks

2021-04-22 16:40 UTC, vppillai commented
David,
 I got a bit busy with work. Will get to this early next week.

Thanks,
Vysakh

On Mon, 19 Apr 2021, 9:34 pm David Garske, ***@***.***> wrote:

> Hi @vppillai <https://github.com/vppillai> , I wanted to ping you and
> make sure you saw the PR feedback comments? Thanks
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/wolfSSL/wolfssl/pull/3926#issuecomment-822586985>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA3XJSQLHI5HQVG4O2RPFE3TJRIAHANCNFSM4Z5F3LSA>
> .
>

2021-04-27 06:29 UTC, vppillai commented
> 
> 
> OK to test. Contributor Agreement on File. These changes look good. I will make a few comments.
> 
> @vppillai , have you seen our Microchip examples repo here? https://github.com/wolfSSL/microchip-atecc-demos

The demos look interesting. will take a detailed look later.

2021-04-27 06:51 UTC, vppillai commented
@dgarske , I have used `ATCA_ENABLE_DEPRECATED` from [atca_iface.h](https://github.com/MicrochipTech/cryptoauthlib/blob/5ea6a891c1394e0eb24ab8890696cb46627d3ae6/lib/atca_iface.h#L88) to make the i2c address variable change compatible with older versions.

2021-04-27 11:28 UTC, vppillai commented
I have added an additional change to this PR based on debug I did while testing these changes with some of my older projects. 
for TNGTLS, `ATMEL_SLOT_ECDHE` type should not be reserved in `mSlotList` just like `ATMEL_SLOT_ECDHE_ENC`. 

Without this change, slot allocation will fail when called from `atcatls_create_pms_cb()` since it will be marked as reserved in `mSlotList` due to the previous call from `atcatls_create_key_cb`

2021-04-28 14:13 UTC, dgarske requested changes
Thanks @vppillai for these changes. Just one minor item and it will be ready to merge.

2021-04-28 14:13 UTC, dgarske commented on wolfcrypt/src/port/atmel/atmel.c
> +	    cfg_ateccx08a_i2c_pi.atcai2c.address        = ATECC_I2C_ADDR;
Looks like line 530 needs removed now.

2021-04-28 14:13 UTC, dgarske commented on wolfcrypt/src/port/atmel/atmel.c
> +    status = tng_atcacert_read_device_cert(certBuffer, &deviceCertSize,\
Can you remove the trailing `\` on this. Not required for plain C function calls.

2021-04-28 14:13 UTC, dgarske commented on wolfcrypt/src/port/atmel/atmel.c
> +    ret = wolfSSL_CTX_use_certificate_chain_buffer_format(ctx,\
Can you remove the trailing `\` on this. Not required for plain C function calls.

2021-04-29 15:18 UTC, dgarske approved these changes

2021-04-30 17:58 UTC, merged