const poisoning - gcc 4.x prefers consistency in prototypes and imple…
wolfSSL/wolfssl pull request #3955
Opened 2021-04-13 18:18 UTC by kaleb-himes

…mentations

2021-04-13 22:41 UTC, SparkiDev approved these changes

2021-04-13 22:42 UTC, SparkiDev commented
Assuming you have tried newer GCC compilers and it worked ...

2021-04-13 23:25 UTC, kaleb-himes commented
NOTE: const-poisoning was introduced after inline of ARM assembly for FIPS module which led to the seperation. Correct solution here is to guard non-const sections in the header with both `HAVE_FIPS_VERSION == 2` and `WOLFSSL_SP_ARM32_ASM` and `WOLFSSL_SP_ARM64_ASM`.

TODO: Refactor PR.

2021-04-15 23:41 UTC, SparkiDev approved these changes

2021-04-15 23:42 UTC, SparkiDev requested changes

2021-04-15 23:42 UTC, SparkiDev commented on wolfssl/wolfcrypt/sp.h
> +#endif /* HAVE_FIPS_VERSION && HAVE_FIPS_VERSION == 2 && !gcc 4.x */
Fix comments to say ARM ASM.

2021-04-16 21:13 UTC, kaleb-himes commented on wolfssl/wolfcrypt/sp.h
> +#endif /* HAVE_FIPS_VERSION && HAVE_FIPS_VERSION == 2 && !gcc 4.x */
Fixed, thank you @SparkiDev!

2021-04-18 22:42 UTC, SparkiDev approved these changes

2021-04-18 23:13 UTC, merged