Allow parsing spaces in Base64_SkipNewline
wolfSSL/wolfssl pull request #3992
Opened 2021-04-28 15:37 UTC by embhorn

Whitespace in the x509 is not strictly forbidden, and we already skipped spaces at the end of lines. This change allows skipping spaces at the beginning and in the middle of lines.

https://stackoverflow.com/questions/26496155/are-spaces-alowed-in-x509-certificates

Thanks to @julek-wolfssl for the patch!

This addresses an issue from ZD12169

2021-04-30 20:39 UTC, dgarske requested changes

2021-04-30 20:39 UTC, dgarske commented on wolfcrypt/test/test.c
> -#elif defined(WOLFSSL_DEOS)
Why was this removed?

2021-05-03 13:48 UTC, embhorn commented on wolfcrypt/test/test.c
> -#elif defined(WOLFSSL_DEOS)
Thanks for fixing that, @dgarske !

2021-05-05 20:09 UTC, dgarske approved these changes

2021-05-07 21:29 UTC, ejohnstown approved these changes

2021-05-07 21:30 UTC, merged