Expand SHA-3 support
wolfSSL/wolfssl pull request #4030
Opened 2021-05-12 10:56 UTC by julek-wolfssl

Add more support in the EVP layer as well as add signing support. The SHA-3 OID's were also added for DER algorithm identifier encoding.

2021-05-12 13:34 UTC, dgarske requested changes
Changes look good. Please resolve the Jenkins build errors:

```
./configure --enable-leantls
make[2]: warning: -jN forced in submake: disabling jobserver mode.
tests/tests_unit_test-api.o: In function `test_wolfSSL_EVP_Digest_all':
api.c:(.text+0x43c5): undefined reference to `wolfSSL_EVP_Digest'

./configure --enable-sp-math-all=small --enable-all --disable-asm --enable-smallstack --enable-32bit CFLAGS='-m32'
make[2]: warning: -jN forced in submake: disabling jobserver mode.
tests/api.c: In function ‘test_wolfSSL_RSA_sign_sha3’:
tests/api.c:38522:31: error: ‘WC_SHA3_256_DIGEST_SIZE’ undeclared (first use in this function)
     const unsigned char mHash[WC_SHA3_256_DIGEST_SIZE] = {
                               ^
tests/api.c:38522:31: note: each undeclared identifier is reported only once for each function it appears in
tests/api.c:38522:25: error: unused variable ‘mHash’ [-Werror=unused-variable]
     const unsigned char mHash[WC_SHA3_256_DIGEST_SIZE] = {
                         ^
```

2021-05-14 17:37 UTC, dgarske approved these changes
Over to Todd for final

2021-06-08 04:05 UTC, SparkiDev requested changes

2021-06-14 10:02 UTC, julek-wolfssl commented on src/ssl.c
> +                case CTC_SHA3_224wECDSA:
Protected.

2021-06-14 10:02 UTC, julek-wolfssl commented on src/ssl.c
> +                case CTC_SHA3_224wRSA:
Protected.

2021-06-14 10:02 UTC, julek-wolfssl commented on src/ssl.c
> +                case CTC_SHA3_224wECDSA:
Protected.

2021-06-24 17:31 UTC, julek-wolfssl commented on src/ssl.c
> +                case CTC_SHA3_224wRSA:
Protected.

2021-06-24 17:31 UTC, julek-wolfssl commented on src/ssl.c
> +                case WC_HASH_TYPE_SHA3_224:
Protected.

2021-06-24 17:31 UTC, julek-wolfssl commented on src/ssl.c
> +                case WC_HASH_TYPE_SHA3_224:
Protected.

2021-06-25 02:08 UTC, SparkiDev approved these changes

2021-06-25 02:18 UTC, merged