DH Key and Params Export cleanups and Apache httpd fixes
wolfSSL/wolfssl pull request #4062
Opened 2021-05-24 17:05 UTC by dgarske

* Refactor of DH key and param exports code (moved into asn.c) enabled with `WOLFSSL_DH_EXTRA`.
* Cleanup `WOLFSSL_DH_EXTRA` macro logic and do not allow with FIPS v1 or v2.
* Fixes for httpd (if `SSL_CONF_FLAG_FILE` is defined it is used to indicate support for `SSL_CONF_CTX_set_flags` and `SSL_CONF_cmd_value_type`).
* Add Curve448 and ED448 key type to `enum wc_PkType`.
* Expand `dh_ffdhe_test` to include 4096 bit.

2021-05-24 22:43 UTC, SparkiDev requested changes
Not seeing a test that calls the new encoding functions.

2021-05-24 22:46 UTC, dgarske commented on wolfcrypt/test/test.c
> +            ret = wc_DhPrivKeyToDer(key, tmp2, &idx);
@SparkiDev , The `wc_DhPrivKeyToDer` function calls both `wc_DhKeyToDer` and `wc_DhParamsToDer`.

2021-05-24 22:46 UTC, dgarske commented on wolfcrypt/test/test.c
> +            ret = wc_DhPubKeyToDer(key, tmp2, &idx);
@SparkiDev , The `wc_DhPubKeyToDer` function calls both `wc_DhKeyToDer` and `wc_DhParamsToDer`.

2021-05-24 22:48 UTC, SparkiDev approved these changes

2021-06-08 01:47 UTC, SparkiDev requested changes

2021-06-08 01:47 UTC, SparkiDev commented on wolfcrypt/src/asn.c
> +        idx = 1 + SetLength(pubSz, NULL) + pubSz; /* +1 for ASN_BIT_STRING */
BIT_STRING has an extra byte to indicate the number of unused bits in last octet.
Use SetBitString(pubSz, 0, NULL) to get length if possible.

2021-06-08 23:03 UTC, SparkiDev approved these changes

2021-06-09 18:08 UTC, kaleb-himes commented
retest this please

2021-06-10 10:54 UTC, merged