Fixes for STM32 PKA with ECC
wolfSSL/wolfssl pull request #4066
Opened 2021-05-25 23:06 UTC by dgarske

* Fix for STM32 PKA ECC point mapping, which is handled in hardware.
* Fixes for STM32 PKA compiler warnings.
* Fix for improperly initialized `PKA_ECDSASignOutTypeDef` on STM32 PKA sign.
* Remove unused STM32 cofactor.

2021-05-26 04:45 UTC, danielinux approved these changes

2021-06-11 02:04 UTC, SparkiDev requested changes

2021-06-11 02:04 UTC, SparkiDev commented on wolfcrypt/src/port/st/stm32.c
> +    szkbin = mp_unsigned_bin_size((mp_int*)k);
Cast not needed.

2021-06-13 22:31 UTC, SparkiDev commented
Looks good.
Merge conflict to be fixed now.

2021-06-14 22:33 UTC, SparkiDev approved these changes

2021-06-14 22:33 UTC, merged