Add an API function wc_EncryptPKCS8Key to handle encrypting a DER, PKCS#8-formatted key.
wolfSSL/wolfssl pull request #4067
Opened 2021-05-25 23:12 UTC by haydenroche5

There's already a function wc_CreatePKCS8Key, but this only creates the
unencrypted PKCS#8 key. TraditionalEnc exists, which takes a non-PKCS#8 key,
converts it to PKCS#8 format, and encrypts it, but this function isn't in the
public-facing API. I've modified TraditionalEnc to use wc_EncryptPKCS8Key after
wc_CreatePKCS8Key. wc_EncryptPKCS8Key is essentially the encryption portion of
TraditionalEnc moved out into its own function. wc_EncryptPKCS8Key will be in
the API going forward so that users can do PKCS#8 encryption without relying on
the non-API TraditionalEnc. Next, I'll be adding a corresponding
wc_DecryptPKCS8Key to handle decryption.

2021-05-25 23:13 UTC, haydenroche5 commented on wolfcrypt/src/asn.c
> -/* Converts Encrypted PKCS#8 to 'traditional' (i.e. PKCS#8 removed from
Further down, you'll see that I changed the comment on `TraditionalEnc`. The previous one didn't make sense to me.

2021-05-25 23:15 UTC, haydenroche5 commented
A little additional background for those not in the know:

Customer wants to do PKCS#8 encryption of a local private key on their embedded device. The only non-compatibility layer function to do that is `TraditionalEnc`, which isn't in the public-facing wolfSSL API. This PR is mean to address this gap. Looking for feedback before I proceed with implementing `wc_DecryptPKCS8Key`.

2021-05-25 23:19 UTC, dgarske approved these changes
This is a great cleanup and way to expose this API for users who want to just perform PKCS8 outside of TLS. Looking forward to seeing the wc_DecryptPKCS8Key and ToTraditionalEnc work next.

2021-05-26 07:03 UTC, SparkiDev commented
Did you look at UnTraditionalEnc()?

2021-05-26 15:41 UTC, haydenroche5 commented
> Did you look at UnTraditionalEnc()? Only implements PBES1 parameters.
> TraditionalEnc() implements PBES1 or PBES2 parameters.

I could also migrate that function to use the new `wc_EncryptPKCS8Key` (modifying it if needed), if that's what you're suggesting.

2021-05-26 17:29 UTC, haydenroche5 commented
Added `wc_DecryptPKCS8Key`. Will look into PRB failures.

2021-05-26 22:19 UTC, SparkiDev commented
Yes, take a look at the alternative versions of the APIs like UnTraditionalEnc() and change them to use the new APIs.
Thanks.

2021-05-27 00:14 UTC, haydenroche5 commented
> Yes, take a look at the alternative versions of the APIs like UnTraditionalEnc() and change them to use the new APIs.
> Thanks.

@SparkiDev, based on your comments and looking at `UnTraditionalEnc`, it seems like we could get rid of this function entirely since its functionality is a subset of what `TraditionalEnc` can already do. The only place `UnTraditionalEnc` is used is in `wc_PKCS12_shroud_key`. That usage can be replaced with a call to `TraditionalEnc`, setting the `encAlgId` parameter to 0. The one thing that would be nice to keep from `UnTraditionalEnc` is the option to pass in a NULL output buffer to get the max size buffer needed (i.e. the case where `LENGTH_ONLY_E` is returned). This functionality can be incorporated into `TraditionalEnc`.

I'd also like to change the name of `TraditionalEnc` to something more meaningful, and possibly bring it into the API. Taking a traditional key and converting it to PKCS#8 encrypted with one API call seems like a nice thing for users to have. As it stands now, users of the API have to call `wc_CreatePKCS8Key` and then `wc_EncryptPKCS8Key` to get the same functionality, which is what `TraditionalEnc` is already doing. Perhaps we could rename it `wc_CreateEncryptedPKCS8Key` and bring it into the API?

Curious everyone's feedback on both points.

2021-05-27 01:23 UTC, SparkiDev commented
I don't know why UnTraditionalEnc was introduced maybe @JacobBarthelmeh may be able to shed some light on this.
The TraditionalEnc is pseudo-public and has to be kept working as it is.
A new API that supports both TraditionalEnc and UntraditionalEnc(), and returns the size would be good!

The new API name should fit with the pattern of others. Right now we use ToDer or ToPublicDer for encoding and Decode for decoding. I would prefer we have 'Encode' and 'Decode' going forward.

2021-05-27 02:48 UTC, JacobBarthelmeh commented
Refactoring and consolidating the PKCS parsing would be great change. The UnTraditionalEnc was added during PKCS12 development and always intended to be an internal only function.

2021-06-02 17:07 UTC, dgarske approved these changes

2021-06-02 22:53 UTC, SparkiDev approved these changes

2021-06-03 16:23 UTC, JacobBarthelmeh requested changes
Only minor change to use the heap hint for static memory builds, other than that looks great! Thanks Hayden

2021-06-03 16:43 UTC, JacobBarthelmeh approved these changes
Added in a commit for the minor heap hint change

2021-06-03 16:46 UTC, dgarske approved these changes

2021-06-08 16:16 UTC, dgarske approved these changes
Great refactor for PKCS 8 key support. Thanks Hayden. 

Please make a note to followup with some test cases and documentation (doxy) for the new `wc_EncryptPKCS8Key` and `wc_DecryptPKCS8Key` functions.

2021-06-08 16:21 UTC, merged