Catch allocation failure in DecodeResponseData
wolfSSL/wolfssl pull request #4093
Opened 2021-06-06 01:17 UTC by guidovranken

The order of the operations was changed slightly such that member variables (`status` and `isDynamic`) are initialized first, and, if no error occurred, the chain is advanced (`single = single->next`). This makes it easier to deal with the potential failure to allocate a `CertStatus`.

2021-06-06 07:00 UTC, bernd-edlinger requested changes
Please look also here:
https://github.com/wolfSSL/wolfssl/blob/76e0a8666be6cd38a59118026260807f54239eae/wolfcrypt/src/asn.c#L16168-L16171

2021-06-06 17:53 UTC, guidovranken commented
> Please look also here:
> 
> https://github.com/wolfSSL/wolfssl/blob/76e0a8666be6cd38a59118026260807f54239eae/wolfcrypt/src/asn.c#L16168-L16171

Thanks, fixed.

2021-06-06 23:24 UTC, SparkiDev commented
ok to test

2021-06-07 01:17 UTC, SparkiDev commented on wolfcrypt/src/asn.c
> +            if ( single->next->status == NULL ) {
No space before and after brackets.

2021-06-07 01:20 UTC, guidovranken commented on wolfcrypt/src/asn.c
> +            if ( single->next->status == NULL ) {
Fixed.

2021-06-08 23:38 UTC, SparkiDev approved these changes

2021-06-08 23:38 UTC, merged