Fix nonblocking ret value from crlIOCb
wolfSSL/wolfssl pull request #4099
Opened 2021-06-07 19:31 UTC by embhorn

The nonblocking return code that is checked when `CheckCertCRL` is called is `OCSP_WANT_READ`, but the callback was returning `WANT_READ`, so the error was handled incorrectly. Also adds a check for `OCSP_WANT_READ` in `DoTls13HandShakeMsgType`.

These issues were first reported in ZD12274.

2021-06-07 19:53 UTC, kaleb-himes commented
retest this please.

2021-06-07 19:54 UTC, kaleb-himes commented
retest this please

2021-06-09 13:27 UTC, embhorn commented
retest this please

2021-06-09 18:07 UTC, kaleb-himes commented
retest this please

2021-06-10 15:35 UTC, dgarske approved these changes
These changes look good. @embhorn please confirm customer is happy with these and re-assign back to me for merge.

2021-06-15 19:48 UTC, dgarske requested changes

2021-06-15 19:48 UTC, dgarske commented on src/tls13.c
>  #ifdef WOLFSSL_ASYNC_CRYPT
This need ` || defined(WOLFSSL_NONBLOCK_OCSP)`.

2021-06-15 20:34 UTC, dgarske approved these changes

2021-06-16 13:37 UTC, embhorn commented
retest this please

2021-06-16 17:05 UTC, merged