Properly declare htons() and friends
wolfSSL/wolfssl pull request #4178
Opened 2021-07-02 07:49 UTC by dr-m

Since 794cb5c7a9ec9495d9751a0397b4cf681909e5a5 both GCC and Clang issue `-Wimplicit-function-declaration` about `XHTONS()` a.k.a. `htons()` in `wolfssl/src/internal.c`:
```
In file included from /mariadb/10.6-merge/extra/wolfssl/wolfssl/wolfssl/ssl.h:153,
                 from /mariadb/10.6-merge/extra/wolfssl/wolfssl/wolfssl/internal.h:29,
                 from /mariadb/10.6-merge/extra/wolfssl/wolfssl/src/internal.c:73:
/mariadb/10.6-merge/extra/wolfssl/wolfssl/src/internal.c: In function ‘DefTicketEncCb’:
/mariadb/10.6-merge/extra/wolfssl/wolfssl/wolfssl/wolfio.h:620:23: warning: implicit declaration of function ‘htons’ [-Wimplicit-function-declaration]
  620 |     #define XHTONS(a) htons((a))
      |                       ^~~~~
/mariadb/10.6-merge/extra/wolfssl/wolfssl/src/internal.c:30263:19: note: in expansion of macro ‘XHTONS’
30263 |     word16 sLen = XHTONS(inLen);
      |                   ^~~~~~
```
I am not sure where this would best be fixed; I saw quite a few `#include <arpa/inet.h>` in other files. In my opinion, header files should `#include` what they build upon. If some header file includes many mutually ‘unrelated’ things, then maybe the header file should be split, if you think that having every compilation unit depend on `<arpa/inet.h>` is a bad idea.

2021-07-02 14:13 UTC, dgarske commented
Hi @dr-m , looks like the Windows case doesn't like this change.

`wolfio.h(33,10): fatal error C1083: Cannot open include file: 'arpa/inet.h': No such file or directory [D:\a\wolfssl\wolfssl\wolfssl.vcxproj]`

Use the `USE_WINDOWS_API` macro to guard it.

Thanks,
David Garske, wolfSSL

2021-07-02 14:17 UTC, dgarske requested changes
The should be near the XHTONS macro in wolfio.h. Please adjust for the Windows case (USE_WINDOWS_API).

Also this XHTONS is only used for internal.c when `(defined(HAVE_SESSION_TICKET) && !defined(WOLFSSL_NO_DEF_TICKET_ENC_CB))`. Or defined(WOLFSSL_DTLS) || defined(HAVE_OCSP) || defined(HAVE_CRL_IO)`. Although you don't need to add this logic.

2021-07-02 16:39 UTC, dr-m commented
@dgarske Thank you. I did notice the Windows build failure, but decided to wait for advice.

I was a little confused by the indentation in the header file. We must include the header even if neither `USE_WOLFSSL_IO` nor `HAVE_HTTP_CLIENT` are defined.

2021-07-02 17:25 UTC, elms commented
Jenkins, @dr-m is an approved contributor, it is ok to test this PR.

2021-07-06 20:04 UTC, dgarske commented
Hi @dr-m , thanks for the PR. I've put up a different fix here: https://github.com/wolfSSL/wolfssl/pull/4191
Let me know if you have any issues with it.
Thanks, David Garske, wolfSSL

2021-07-06 20:04 UTC, closed without merging

2021-07-20 07:36 UTC, dr-m commented
@dgarske Thank you, I successfully tested 77c9b36b5a557e8241cf9f12a2d8cd3b96cfc231 with MariaDB/server@3e5a11e4889c97b781bb5828c8eed62251948a9e (compiled with `cmake -DWITH_SSL=bundled -DWITH_ASAN=ON`). That includes your c9aa23ac7af46c315fb0242fdeaf381d7a22ce97 (#4191).