Added new sniffer API for callback for key
wolfSSL/wolfssl pull request #4181
Opened 2021-07-02 20:00 UTC by dgarske

New API `ssl_SetKeyCallback` with support indicated by `WOLFSSL_SNIFFER_KEY_CALLBACK`.
Trace cleanup for custom error.

2021-07-15 22:16 UTC, ejohnstown requested changes

2021-07-15 22:16 UTC, ejohnstown commented on src/sniffer.c
> +    /* for secure renegotiation server arrays can be NULL */
The sessionID memcpy a few lines below is able to have a copy to a null pointer according to scan-build.

2021-07-19 14:59 UTC, dgarske commented
@ejohnstown customer confirms all sniffer issues are fixed and tests are passing with this PR.

2021-07-19 20:26 UTC, ejohnstown approved these changes

2021-07-19 20:26 UTC, merged