Added wc_Md2Hash() unit testing to test.c
wolfSSL/wolfssl pull request #4215
Opened 2021-07-16 21:50 UTC by lealem47

2021-07-21 15:47 UTC, cconlon requested changes

2021-07-21 15:47 UTC, cconlon commented on wolfcrypt/test/test.c
> +    for (i = 0; i < times; ++i){
Minor style request - please add a space after the closing ')' in your for loop here, and if statements below.  Thanks!

2021-08-03 02:30 UTC, lealem47 commented
retest this please

2021-08-03 22:50 UTC, cconlon commented on wolfcrypt/test/test.c
> +    for (i = 0; i < times; ++i){
For future reference, please allow the original reviewer to mark an issue as "Resolved", thanks!

2021-08-03 22:50 UTC, cconlon approved these changes

2021-08-03 22:51 UTC, merged