Fixes for building with Microchip XC32 and ATECC
wolfSSL/wolfssl pull request #4238
Opened 2021-07-23 19:51 UTC by dgarske

ZD 12605

2021-07-25 22:25 UTC, SparkiDev requested changes

2021-07-25 22:25 UTC, SparkiDev commented on wolfssl/wolfcrypt/types.h
> +                #undef  FALL_THROUGH
No need to undef anymore.

2021-07-26 21:37 UTC, embhorn approved these changes
Approved

2021-07-26 23:34 UTC, SparkiDev approved these changes

2021-07-27 23:32 UTC, SparkiDev approved these changes

2021-07-27 23:33 UTC, merged