Add support for pyOpenSSL.
wolfSSL/wolfssl pull request #4274
Opened 2021-08-02 16:15 UTC by haydenroche5

pyOpenSSL needs the OpenSSL function X509_EXTENSION_dup, so this commit adds
that to the compatibility layer. It also needs to be able to access the DER
encoding of the subject alt names in a cert, so that's added as well.

2021-08-04 20:01 UTC, dgarske requested changes

2021-08-04 20:01 UTC, dgarske commented on tests/api.c
> +    FILE* f;
I see a mix of linux BSK fopen and XFILE/XFOPEN in api.c, but my preference is to use our wc_port.h and XF macros.

2021-08-04 20:49 UTC, dgarske requested changes

2021-08-04 20:49 UTC, dgarske commented on src/ssl.c
> +
Can you also fix the leak cases below, since you are in this section of code and they have been identified? Lines 9105, 9119, 9129.

2021-08-04 21:13 UTC, haydenroche5 commented on src/ssl.c
> -                            sk = NULL;
Not sure why this error case and the one below weren't handled with a `return NULL`, but I think they should be, hence the change.

2021-08-05 15:06 UTC, dgarske approved these changes

2021-08-09 16:44 UTC, dgarske approved these changes

2021-08-09 16:44 UTC, dgarske commented
retest this please

2021-08-10 18:49 UTC, merged