Adding README.md to examples dir and links to examples github repo in…
wolfSSL/wolfssl pull request #4277
Opened 2021-08-02 21:59 UTC by lealem47

… client/server.c

2021-08-02 22:40 UTC, dgarske requested changes
You can preview the mark-down rendering in your branch here:
https://github.com/lealem47/wolfssl/tree/ex-repo-link/examples

Just a couple minor updates.

2021-08-02 22:40 UTC, dgarske commented on examples/README.md
> + Compile
Please move the "Compile" out of the triple tick. You can add sh to the triple tick to inform mark-down of format. Same for the other triple tick sections... the title should not be in the shell block.

2021-08-02 22:40 UTC, dgarske commented on examples/README.md
> +These directories contain a client (echoclient.c) and server (echoserver.c) that establish a connection encrypted by wolfSSL. Like the names indicate, once the connection has been established any mes
Spelling `disbled`

2021-08-02 22:40 UTC, dgarske commented on examples/README.md
> +#### client and server
Please use `##` for next level

2021-08-02 23:10 UTC, lealem47 commented on examples/README.md
> +These directories contain a client (echoclient.c) and server (echoserver.c) that establish a connection encrypted by wolfSSL. Like the names indicate, once the connection has been established any mes
Only one typo is a win!

2021-08-03 21:49 UTC, dgarske approved these changes

2021-08-04 19:43 UTC, merged