Fix a race condition in the benchmark example and …
wolfSSL/wolfssl pull request #4297
Opened 2021-08-11 21:17 UTC by anhu

…make all output go to stderr.

2021-08-11 21:23 UTC, dgarske requested changes
Is the reason for piping to `fprintf(stderr,` so the messages can be filtered or captured differently? Interestingly our WOLFSSL_MSG also goes to stderr by default.

2021-08-11 21:27 UTC, anhu commented on examples/benchmark/tls_bench.c
> +    while (info->serverListening == 0) {
ah...right....I remember we talked about that.  Ok.  Will do.

2021-08-11 22:17 UTC, dgarske commented
Also with c99 and `usleep`. Consider using `XSLEEP_MS` macro.

```
./configure --enable-jobserver=4 CFLAGS="-std=c99" --enable-all
examples/benchmark/tls_bench.c:760:9: error: implicit declaration of function ‘usleep’; did you mean ‘sleep’? [-Werror=implicit-function-declaration]
```

2021-08-11 22:20 UTC, anhu commented
Oh dear.... How embarrassing.  :blush: 
I'll get those fixed up.

2021-08-12 15:51 UTC, dgarske approved these changes

2021-08-12 20:51 UTC, merged

2021-08-13 00:44 UTC, anhu commented
Woot!!!