add wolfclu enable option and remove test macro guard
wolfSSL/wolfssl pull request #4362
Opened 2021-09-01 14:52 UTC by JacobBarthelmeh

The removed macro guard was for "./configure --enable-opensslall --disable-ocsp && make check". wolfCLU uses opensslall macros but does not use OCSP.

2021-09-01 18:03 UTC, haydenroche5 requested changes
Suggested a different strategy for the configure.ac changes.

2021-09-02 00:46 UTC, kaleb-himes commented
retest this please

2021-09-08 18:07 UTC, haydenroche5 commented on configure.ac
> +        ENABLED_MD5=no
Should this be here? I'm under the impression that the `ENABLES` go further up, and the CFLAGS get added down here.

2021-09-08 18:11 UTC, haydenroche5 requested changes
Just one question. Otherwise, looks good for final review by PR captain.

2021-09-15 14:48 UTC, haydenroche5 approved these changes
Assigning to @ejohnstown for final review/merge.

2021-09-15 20:57 UTC, merged