call alpn selection call-back at server side only
wolfSSL/wolfssl pull request #4377
Opened 2021-09-07 08:49 UTC by miyazakh

tell SSL object to use alpn when setting it to CTX

2021-09-08 00:01 UTC, SparkiDev requested changes

2021-09-08 00:01 UTC, SparkiDev commented on src/internal.c
> +            #if defined(WOLFSSL_ERROR_CODE_OPENSSL)
bring pre-preprocessor statements back a tab.

2021-09-08 00:02 UTC, SparkiDev commented
Would be good if we had a test case for setting the ALPNs for against the WOLFSSL_CTX given it didn't work.

2021-09-08 23:57 UTC, miyazakh commented
Hi @anhu 
Removed the line so that it resulted different protos

2021-09-09 02:48 UTC, anhu commented
> Hi @anhu
> Removed the line so that it resulted different protos

Hello @miyazakh , 

So, you wanted it to be different on purpose?  I don't really understand why, but it is only a gut feeling that they should be the same so I will mark this as resolved.

2021-09-15 00:02 UTC, SparkiDev approved these changes

2021-09-15 00:02 UTC, merged