cppcheck fixes and a config fix
wolfSSL/wolfssl pull request #4398
Opened 2021-09-14 06:42 UTC by SparkiDev

./configure --disable-rsa --disable-ecc --disable-dsa
--enable-curve25519 --disable-ed25519 --disable-curve448
--disable-ed448 --enable-cryptonly

suites.c, testsuite.c: ensure port is an integer for snprintf.

unit.c: make memFailCount an integer for printf.

aes.c:
  Reduce variable scope.
  Check aes is not NULL before use in GHASH implementations.
XTS check sz is greater than or equal to a AES_BLOCK_SIZE rather than
0 as another block is processed.
  wc_AesXtsEncrypt, wc_AesXtsEncrypt - simplify braces and ifdefs
wc_AesEcbEncrypt - subtracting from sz is unnecessary as is unused
after.

asn.c:
StoreKey, StoreEccKey - compiler doesn't see ret != 0 when publicKey
is NULL.
  DecodeAuthInfo - count is not used when after break.
  DecodeSubtree - don't use min and max as variables (already macros).
SetEccPublicKey - initialize pubSz and set sz regardless for
compiler's sake.
wc_EncodeName_ex - use unique variable 'namesASN'; ret isn't set after
last check.
SetEccPublicKey - simplify code by using else rather than check ret
wasn't set.
  DecodeAsymKey - ret not modified in non-template implementaiton.
  SetAsymKeyDer - ret still at initialized value here.
DecodeResponseData - ensure dataASN is freed when single->next->status
failed to allocate.

test.c:
  curve255519_der_test() can't be compiled when NO_ASN is defined.

types.h:
  cast to the appropriate type in EXIT_TEST
test.h
don't return anything when THREAD_RETURN is void and EXIT_TEST is for
threading with stack size.

2021-09-14 15:03 UTC, dgarske requested changes

2021-09-14 15:03 UTC, dgarske commented on wolfcrypt/src/aes.c
> +        if (sz >= AES_BLOCK_SIZE) {
Can you double check this change? `sz` is decremented above and appears like it could be / should be `sz > 0`. @JacobBarthelmeh , thoughts?

2021-09-14 23:14 UTC, SparkiDev commented
Lines 11340-11344:
'
        /* if Stealing then break out of loop one block early to handle special
         * case */
        if (stl > 0) {
            blocks--;
        }
'

So there will be an extra block of data when stealing - we need to XOR in the partial block into the last block.

Lines 11405-11408:
'
            XMEMCPY(buf, in, AES_BLOCK_SIZE);
            xorbuf(buf, tmp2, AES_BLOCK_SIZE);
            wc_AesDecryptDirect(aes, out, buf);
            xorbuf(out, tmp2, AES_BLOCK_SIZE);
'

Using last full block and XORing in partial block.

If no partial block then all data will be processed and sz will be 0.

2021-09-15 01:19 UTC, dgarske approved these changes

2021-09-15 01:19 UTC, merged