Add Kerberos 5 support
wolfSSL/wolfssl pull request #4442
Opened 2021-10-01 12:26 UTC by julek-wolfssl

2021-10-11 21:55 UTC, haydenroche5 requested changes

2021-12-02 00:06 UTC, haydenroche5 commented on src/ssl.c
> +    if (p7->rng == &rng) {
I don't see the `if` section you're talking about.

2021-12-02 00:09 UTC, haydenroche5 requested changes
Just one issue to resolve.

2021-12-02 09:26 UTC, julek-wolfssl commented on src/ssl.c
> +    if (p7->rng == &rng) {
Unless my git client is lying to me, this is part of the initialization of the function:
```
    if (!p7->rng) {
        if (wc_InitRng(&rng) != 0) {
            WOLFSSL_MSG("wc_InitRng error");
            return WOLFSSL_FAILURE;
        }
        p7->rng = &rng;
    }
```

2021-12-02 15:13 UTC, haydenroche5 commented on src/ssl.c
> +    if (p7->rng == &rng) {
GitHub just isn't showing this snippet, but it's there.

2021-12-02 15:13 UTC, haydenroche5 approved these changes

2021-12-02 17:07 UTC, dgarske approved these changes

2021-12-02 17:07 UTC, merged