Add x509 name attributes and extensions to DER parsing and generation
wolfSSL/wolfssl pull request #4459
Opened 2021-10-08 10:38 UTC by julek-wolfssl

- Postal Code
- Street Address
- External Key Usage
- Netscape Certificate Type
- CRL Distribution Points
- Storing full Authority Key Identifier information
- Add new certificates to `certs/test` for testing
- Update WOLFSSL_ASN_TEMPLATE to match new features

2021-10-10 23:25 UTC, SparkiDev submitted a review, later dismissed

2021-10-28 18:01 UTC, dgarske requested changes

2021-10-28 21:23 UTC, dgarske requested changes
This PR breaks `./configure --enable-all CFLAGS="-DWOLFSSL_ASN_TEMPLATE"` with `test_wolfSSL_CertManagerNameConstraint`. The changes in `./certs/test/cert-ext-nc.der` cause the `ConfirmNameConstraints` to fail, when it expects success at api.c:1603

2021-10-28 21:29 UTC, dgarske approved these changes
Turns out the `WOLFSSL_ASN_TEMPLATE` issue is in master and started with PR #4485. This PR looks good.

2021-10-28 21:30 UTC, merged