Native LwIP support update
wolfSSL/wolfssl pull request #4589
Opened 2021-11-19 18:10 UTC by JacobBarthelmeh

2021-11-19 18:16 UTC, dgarske requested changes
Super excited to see this LWIP Native support back! Thanks Jacob. Just a couple minor things.

2021-11-19 18:16 UTC, dgarske commented on src/internal.c
> +		ctx->CBIORecv = LwIPNativeReceive;
Check indent. space vs tabs.

2021-11-19 18:16 UTC, dgarske commented on src/wolfio.c
> +            return WOLFSSL_CBIO_ERR_GENERAL;
Also indent here

2021-11-19 18:16 UTC, dgarske commented on src/wolfio.c
> +
Extra space or line length, can't tell

2021-11-19 18:16 UTC, dgarske commented on src/wolfio.c
> +    tcp_arg (pcb, (void *)&(ssl->lwipCtx));
Prefer written as `(void*)&ssl->lwipCtx`

2021-11-19 18:16 UTC, dgarske commented on wolfcrypt/src/misc.c
> +    signed char ret = (signed char)ch;
Cool, thanks for the explicit signed char work here.

2021-11-19 18:16 UTC, dgarske commented on wolfcrypt/src/wc_port.c
> +    /* must get time and date here due to STM32 HW bug */
It is the order of these call that is important / bug. Time then date.

2021-11-19 18:16 UTC, dgarske commented on wolfcrypt/test/test.c
> +    #ifndef test_pass
Would an `#undef test_pass` here be better?

2021-11-19 18:16 UTC, dgarske commented on wolfcrypt/test/test.c
> +#ifndef NO_TEST_PRINTF
Top of test.c has some macros for overriding printf`. Perhaps something like `#elif defined(NO_PRINTF #define printf(...) /* not available */`.

2021-11-19 18:16 UTC, dgarske commented on wolfssl/wolfcrypt/settings.h
> +    #define WOLFSSL_USER_IO
Force user IO for LWIP native?

2021-11-30 20:43 UTC, JacobBarthelmeh commented
Thanks for the review David, I addressed some but not all yet. Am testing on the device for the comments regarding test.c and WOLFSSL_USER_IO.

2021-12-01 18:36 UTC, dgarske approved these changes

2021-12-01 18:37 UTC, merged