Actually do a private/public key check for FALCON.
wolfSSL/wolfssl pull request #4641
Opened 2021-12-08 23:07 UTC by anhu

2021-12-08 23:38 UTC, dgarske requested changes

2021-12-08 23:38 UTC, dgarske commented on wolfcrypt/src/falcon.c
> +    byte msg[] = "The wolfSSL team is here to make you ready for quantum computers!!";
This will have a cast warning on some targets. Please add cast to ‘byte*’. Make ‘const’.

2021-12-08 23:38 UTC, dgarske commented on wolfcrypt/src/falcon.c
> +    word32 msglen = sizeof(msg);
Also will produce cast warning. Sizeof returns size_t. You’ll need to cast to word32

2021-12-08 23:38 UTC, dgarske commented on wolfcrypt/src/falcon.c
> +    word32 siglen = sizeof(sig);
Same here. Cast to word32

2021-12-09 21:01 UTC, dgarske requested changes

2021-12-09 22:18 UTC, dgarske approved these changes

2021-12-10 14:42 UTC, anhu commented
@dgarske, I think we're good to go!  Please merge WITHOUT squash as I'd like to preserve the sign/verify check in the commit history in case we want to bring it back.

2021-12-10 14:53 UTC, merged