Make wolfCrypt ASN cert parsing functionality public.
wolfSSL/wolfssl pull request #4645
Opened 2021-12-09 23:50 UTC by haydenroche5

Currently, the `ParseCert` function is only available if `WOLFSSL_ASN_API` is
defined to `WOLFSSL_API`. The only way to achieve this without enabling the
compatibility layer is to define `WOLFSSL_TEST_CERT`. There are users defining
this so that they can parse certs with wolfCrypt, even though this doesn't seem
to be the original intent of the define. This commit adds the function
`wc_ParseCert` to the public wolfCrypt API. It's simply a wrapper around
`ParseCert`. Similarly, this commit adds `wc_InitDecodedCert` and
`wc_FreeDecodedCert` to the public API, which are wrappers around
`InitDecodedCert` and `FreeDecodedCert`, respectively.

2021-12-10 00:05 UTC, dgarske requested changes
Also, I double checked and those internal functions DO have argument checking on them. Luckily.

2021-12-10 00:05 UTC, dgarske commented on wolfssl/wolfcrypt/asn_public.h
> +struct DecodedCert;
Users will still need to include our `wolfssl/wolfcrypt/asn.h` to be able to deference `DecodedCert`. But at least there will be visible API's now!

2021-12-10 00:05 UTC, dgarske commented on wolfssl/wolfcrypt/asn_public.h
> +WOLFSSL_API void wc_InitDecodedCert(struct DecodedCert*, const byte*, word32, void*);
Please add doxy for these new API's.

2021-12-10 20:07 UTC, dgarske approved these changes

2021-12-11 00:05 UTC, cconlon approved these changes

2021-12-11 02:27 UTC, merged