Fix missing include ws2tcpip.h for VS build
wolfSSL/wolfssl pull request #4688
Opened 2021-12-22 15:30 UTC by embhorn

This fixes an issue reported in #4684

2021-12-22 17:01 UTC, dgarske approved these changes

2021-12-23 18:49 UTC, dgarske requested changes

2021-12-23 18:49 UTC, dgarske commented on wolfssl/wolfcrypt/wc_port.h
> +            #include <ws2tcpip.h>
Should this be wrapped with `!defined(WOLFSSL_USER_IO)`? If this is related to sockets we shouldn't add a new include if using custom read/write IO callbacks.

2021-12-23 23:25 UTC, dgarske approved these changes

2021-12-24 01:58 UTC, SparkiDev approved these changes

2021-12-24 01:58 UTC, merged