compatibility for EVP_CipherUpdate with AES-GCM
wolfSSL/wolfssl pull request #4718
Opened 2022-01-04 00:01 UTC by kojo1

2022-02-04 19:21 UTC, dgarske requested changes
Otherwise I like the change... although not sure it should actually by on for all OPENSSL_EXTRA cases....

2022-02-04 19:21 UTC, dgarske commented on wolfssl/wolfcrypt/settings.h
> +#if defined(POENSSL_EXTRA) || defined(OPENSSL_ALL)
Typo... `POENSSL_EXTRA` -> `OENSSL_EXTRA`. Please fix. Thanks

2024-06-17 17:24 UTC, JacobBarthelmeh approved these changes

2024-06-17 18:54 UTC, dgarske approved these changes

2024-06-17 22:48 UTC, SparkiDev approved these changes

2024-06-17 22:48 UTC, merged