Renesas SCE port fix aes128-gcm crypt only usecase
wolfSSL/wolfssl pull request #4728
Opened 2022-01-06 06:25 UTC by miyazakh

Fix aes128-gcm crypt only use-case
Update signed ca certification because ca-cert was updated

2022-01-10 20:24 UTC, cconlon requested changes

2022-01-10 20:24 UTC, cconlon commented on wolfcrypt/src/port/Renesas/renesas_sce_aes.c
> +            WOLFSSL_MSG("AES kes for SCE is not set.");
Spelling - "kes" should be "key"

2022-01-10 20:24 UTC, cconlon commented on wolfcrypt/src/port/Renesas/renesas_sce_aes.c
> +            WOLFSSL_MSG("AES kes for SCE is not set.");
Spelling - "kes" should be "key"

2022-01-11 10:53 UTC, miyazakh commented on wolfcrypt/src/port/Renesas/renesas_sce_aes.c
> +            WOLFSSL_MSG("AES kes for SCE is not set.");
Thanks. Fixed

2022-01-11 10:53 UTC, miyazakh commented on wolfcrypt/src/port/Renesas/renesas_sce_aes.c
> +            WOLFSSL_MSG("AES kes for SCE is not set.");
Thanks. Fixed

2022-01-17 17:28 UTC, cconlon approved these changes

2022-01-17 17:28 UTC, merged