include hmac for deterministic ecc sign build
wolfSSL/wolfssl pull request #4733
Opened 2022-01-07 21:06 UTC by JacobBarthelmeh

fix for build ./configure CPPFLAGS=-DWOLFSSL_ECDSA_DETERMINISTIC_K

2022-01-10 06:34 UTC, SparkiDev commented
On Linux and configuring with:
 configure --disable-shared C_EXTRA_FLAGS="-DWOLFSSL_ECDSA_DETERMINISTIC_K"
results in:
wolfcrypt/src/ecc.c:6390:23: error: comparison of unsigned expression < 0 is always false ...

2022-01-10 16:26 UTC, JacobBarthelmeh commented
> On Linux and configuring with: configure --disable-shared C_EXTRA_FLAGS="-DWOLFSSL_ECDSA_DETERMINISTIC_K" results in: wolfcrypt/src/ecc.c:6390:23: error: comparison of unsigned expression < 0 is always false ...

Thanks Sean. Reproduced it and added a fix.

2022-01-13 21:48 UTC, SparkiDev requested changes

2022-01-13 21:48 UTC, SparkiDev commented on wolfcrypt/src/ecc.c
> +            if (z1Sz < 0 || h1len > WC_MAX_DIGEST_SIZE) {
hashSz is check against WC_MAX_DIGEST_SIZE above.
h1len is assigned to hashSz and not modified.

2022-01-20 03:59 UTC, SparkiDev approved these changes

2022-01-26 18:01 UTC, merged