Enable wolfSSL SP Math all (sp_int.c) by default
wolfSSL/wolfssl pull request #4759
Opened 2022-01-14 22:03 UTC by dgarske

2022-01-16 22:32 UTC, SparkiDev requested changes

2022-01-16 22:32 UTC, SparkiDev commented on configure.ac
>      [AS_HELP_STRING([--enable-sp-math-all],[Enable Single Precision math implementation for full algorithm suite (default: disabled)])],
Changed the default to 'enabled'.

2022-01-16 22:32 UTC, SparkiDev commented on configure.ac
> +AC_ARG_ENABLE([oldmath],
I would prefer 'heapmath' to 'oldmath' - more descriptive.

2022-01-17 23:53 UTC, SparkiDev commented
Looks like I used sp_digit instead of sp_int_digit in sp_int.c.

2022-01-17 23:55 UTC, SparkiDev commented
Casting required for Windows as well.

2022-01-18 19:16 UTC, dgarske commented
@SparkiDev I think this is in a good state now. If there are any issues please go ahead and fix them and push to this PR. Todd asked you finalize the SP math all by default work. Thanks!

2022-06-21 13:14 UTC, anhu commented
So, from some of the comments I'm getting the impression that fips customers should not be using SP-math.  Is that impression correct?

2022-06-21 14:28 UTC, kaleb-himes commented
@SparkiDev happy to help on this if you needed, I've dealt a lot with SP math and FIPS, let's sync up when you start work for the day. I'll start testing things in the meantime and see if I can't narrow it down, I believe this may be a little tricky, we may need to hinge the sp math by default on a few conditions:

is it `HAVE_FIPS_VERSION == 2` and if so is the module version one of the modules that supports sp math (versions listed above in my reply to @anhu )

2022-06-23 06:47 UTC, SparkiDev approved these changes

2022-06-23 16:27 UTC, dgarske commented
The state of this PR looks awesome. Would be nice to finalize this. Seems to just be a a Windows FIPS ACVP issue with build settings.

@kaleb-himes can you review the errors in this failed test case?
https://test.wolfssl.com/jenkins/job/PRB-FIPS-windows-test-part2-ACVP-v2/1076/

2022-06-23 16:46 UTC, dgarske commented
Kaleb provided me a FIPS patch and I fixed the build issue. Let's see what Jenkins thinks now. Assigning back to me for finalization.

2022-06-23 19:14 UTC, kaleb-himes approved these changes

2022-06-23 23:14 UTC, dgarske reviewed
Approved. I opened PR, so can't mark approved, but can merge it. Get ready everyone!

2022-06-23 23:14 UTC, merged