Get rid of HC-128
wolfSSL/wolfssl pull request #4767
Opened 2022-01-17 23:16 UTC by anhu

2022-01-17 23:37 UTC, SparkiDev commented on IDE/Renesas/cs+/Projects/wolfssl_lib/wolfssl_lib.mtpj
> -    <Instance Guid="980e2f67-afb3-4b48-bc51-8de94240ee4f">
Other references to Guid in file.

2022-01-17 23:40 UTC, SparkiDev commented on IDE/MDK-ARM/Projects/MDK-ARM-wolfSSL-Lib.uvopt
> -      <FileNumber>22</FileNumber>
Should be checked to see that renumbering isn't needed.

2022-01-17 23:43 UTC, dgarske requested changes
Please add a few notes like in the configure.ac place or README about depreciation of the HC128 after v5.1.1 (Jan 2022) and if interested in supporting either use an older version or contact us.

2022-01-19 20:17 UTC, dgarske approved these changes

2022-01-19 20:20 UTC, merged