Support for IPSec-Tools Racoon on Android
wolfSSL/wolfssl pull request #4780
Opened 2022-01-20 22:03 UTC by dgarske

# Description

Adds support for IPSec/Racoon on Android
* Added stack of NAME_ENTRIES to compatibility layer
* Added `X509_STORE_CTX_set_flags` stub.
* Make EVP pkey structure expose rsa/dh/dsa/ecc elements for compatibility.
* Added PKCS7 NID types.

# Testing

Tested on Android v8.1 kernel with wolfCrypt FIPS using ExpressVPN.

# Checklist

 - [X ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2022-01-24 03:45 UTC, SparkiDev approved these changes

2022-01-24 04:22 UTC, dgarske commented
Please hold on merge. Customer testing is showing a possible issue in EVP with AES CBC. Could be related to how the IV is being set. Will investigate and update this PR. Thanks @SparkiDev and @haydenroche5

2022-01-28 00:03 UTC, haydenroche5 requested changes
Looks good! Just some cosmetic comments.

2022-01-28 00:03 UTC, haydenroche5 commented on wolfssl/internal.h
> +        WOLFSSL_X509_NAME_ENTRY* nameentry;
Camel case to `nameEntry`.

2022-01-28 18:53 UTC, haydenroche5 approved these changes

2022-01-31 23:10 UTC, merged