Fixes for building without HMAC
wolfSSL/wolfssl pull request #4830
Opened 2022-02-04 23:25 UTC by dgarske

# Description

Fixes for building with without HMAC support in wolfCrypt only. Also fixes some trailing whitespace.

Fixes ZD 13477

# Testing

`./configure --enable-opensslextra --enable-cryptonly CFLAGS="-DNO_HMAC" && make`

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2022-02-05 07:03 UTC, douzzer requested changes
Looks good as far as it goes.  It's not far off from fixing `--enable-opensslextra --enable-all-crypto --enable-cryptonly CFLAGS=-DNO_HMAC`.  That would take a few tweaks in kdf.c, internal.h, and ecc.c -- might be worth the effort to make that work.

See comment about `hkdf_test()`.  Crazy bug around that. that just won't die.

Do you have a `CFLAGS=-DNO_HMAC` test scenario in the pipeline for PRB?

2022-02-05 07:05 UTC, douzzer commented on wolfcrypt/test/test.c
> -/* WOLFSSL_TEST_SUBROUTINE */ static int hkdf_test(void)
I forgot to mention, the `sp-all-asm-smallstack-valgrind-testsuite` test succeeded locally.  `valgrind-3.18.1`

2022-02-07 23:13 UTC, dgarske commented on wolfcrypt/test/test.c
> -/* WOLFSSL_TEST_SUBROUTINE */ static int hkdf_test(void)
I spent about 1 hour trying to debug this on the physical Xilinx target without luck. Enabling debug changes the behavior which indicates stack issues or memory initialization. The issues are specific to the afalg driver on Xilinx. For now I have reverted the workaround on the hkdf_test.

2022-02-08 04:26 UTC, douzzer approved these changes
LGTM -- pity that you didn't strike gold with`hkdf_test()`.  dang bug won't die.

2022-02-08 04:26 UTC, merged