Improve the client certificate checking logic
wolfSSL/wolfssl pull request #4831
Opened 2022-02-07 01:28 UTC by dgarske

# Description

Improve client certificate checking. Make sure wolfSSL_CTX_mutual_auth` is also checked.

Fixes zd13571

# Testing

Custom test. Will add additional 

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2022-02-07 06:50 UTC, SparkiDev requested changes

2022-02-07 06:50 UTC, SparkiDev commented on src/internal.c
> +                         (ssl->options.mutualAuth && ssl->options.failNoCert)) {
Should be mutualAuth || failNoCert?

2022-02-07 18:12 UTC, kareem-wolfssl approved these changes

2022-02-07 22:32 UTC, SparkiDev approved these changes

2022-02-08 22:26 UTC, SparkiDev approved these changes

2022-02-08 22:27 UTC, merged