Modify example app to work with FreeRTOS+IoT
wolfSSL/wolfssl pull request #4864
Opened 2022-02-15 07:23 UTC by TakayukiMatsuo

# Description

Changed the sample application for Renesas board RSK+RX65N-2MB to run on FreeRTOS. Also provided instruction manuals(Engllish and Japanese).

Fixes zd#

# Testing

The sample application was run on the eva-board and tested for TLS communucation with example/server.

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [x ] updated appropriate READMEs
 - [x ] Updated manual and documentation

2022-02-15 22:57 UTC, cconlon requested changes

2022-02-18 23:27 UTC, TakayukiMatsuo commented on IDE/Renesas/e2studio/RX65N/RSK/README_EN.md
> +A sample program for evaluating wolfSSL targeting the Renesas RX72N EnvisionKit evaluation board is provided. For details on the program, refer to the following documents included in the package.
Fixed it. Unfortunately, Renesas only provides the page for RX72N, so I use the reference there as it is.

2022-02-18 23:27 UTC, TakayukiMatsuo commented
Renesas will add the board definition file to be provided. The name is still tentative. I will wait for them to release the file after February 28th and reflect it in the instruction manual. Please keep this PR open until I'm done.

2022-02-21 22:47 UTC, TakayukiMatsuo commented
Since Renesas released a new board definition file on the web, instruction manuals were updated to renew some snap shots.
Please resume the review.

2022-02-22 18:29 UTC, cconlon approved these changes

2022-02-25 23:03 UTC, cconlon commented
@TakayukiMatsuo Does your last comment mean that we can go ahead and merge this PR now (upstream files are in place and ready)?

2022-02-28 00:03 UTC, TakayukiMatsuo commented
Yes, it is. Since Renesas released a new board config file on the web earlier than planned and I have reflected that filename and snap shots in the manuals, we need not to wait the due date.

2022-02-28 16:12 UTC, merged