Fixes for PK callbacks with server side and setting a public key
wolfSSL/wolfssl pull request #4969
Opened 2022-03-18 18:40 UTC by dgarske

# Description

Fixes for allowing server to have a public key set when using external key with PK callbacks.

Fixes ZD13903

# Testing

```
./configure --enable-pkcallbacks CFLAGS="-DTEST_PK_PRIVKEY" --enable-curve25519 --enable-ed25519 --enable-curve448 --enable-ed448 && make
```

Test code: https://github.com/wolfSSL/wolfssl-examples/pull/306
```
./server-tls-pkcallback
./client-tls-pkcallback 127.0.0.1
```

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2022-03-21 16:44 UTC, anhu requested changes
```
./configure --enable-pkcallbacks CFLAGS="-DTEST_PK_PRIVKEY" --enable-curve25519 --enable-ed25519 --enable-curve448 --enable-ed448
.
.
.
FAIL: scripts/unit.test
```

```
SSL_accept error -308, error state on socket
```

2022-03-21 21:31 UTC, anhu requested changes
tiny little nits.

2022-03-21 21:31 UTC, anhu commented on src/internal.c
> +        #endif
trailing whitespace here and and end of another `#endif` below.

2022-03-21 21:31 UTC, anhu commented on src/ssl.c
> +                ret = wc_Ed448PublicKeyDecode(der->buffer, idx, key, der->length);
NIT: line length too long.

2022-03-21 21:31 UTC, anhu commented on src/tls13.c
> +            #endif
Trailing whitespace.

2022-03-22 14:29 UTC, anhu commented on src/tls13.c
> +            #endif
Missed one.

2022-03-22 15:31 UTC, anhu commented
Kudos to @douzzer  's  `wolfssl-multi-test.sh` 
```
warning, overlong lines added:
/src/ssl.c:14878                         WOLFSSL_MSG("Allowing no server private key (external)");
```

2022-03-22 15:39 UTC, anhu reviewed
Looks like we're good to go!  Will merge once tests are all passing.

2022-03-23 14:48 UTC, dgarske commented
Retest this please

2022-03-24 14:23 UTC, anhu commented
Retest this please

2022-03-24 16:40 UTC, merged