Add IAR MSP430 example
wolfSSL/wolfssl pull request #5030
Opened 2022-04-07 10:09 UTC by LinuxJedi

A basic MSP430 example for IAR IDE.

2022-04-07 15:49 UTC, dgarske requested changes

2022-04-07 15:49 UTC, dgarske commented on IDE/IAR-MSP430/include.am
> +# vim:ft=automake
```
Your pull request adds new files, but does not add them to include.am!
missing files (1 total):
----> IDE/IAR-MSP430/include.am
```

2022-04-07 15:49 UTC, dgarske commented on IDE/IAR-MSP430/main.c
> +#define ECC_448_BIT_FIELD 56 /* 448-bit curve field */
This `ECC_448_BIT_FIELD` appears unused? Consider removing the curve448.h

2022-04-07 15:49 UTC, dgarske commented on IDE/IAR-MSP430/main.c
> +static byte generatedCiphertext[1024];
Maybe consider making the 1024 a macro?

2022-04-08 14:41 UTC, LinuxJedi commented
Thanks for the input. Everything should be addressed now and a few extra things in there too.

2022-04-08 15:27 UTC, dgarske approved these changes

2022-04-08 20:15 UTC, merged