Add wolfSSL_EC_KEY_print_fp to compat layer.
wolfSSL/wolfssl pull request #5033
Opened 2022-04-07 20:08 UTC by haydenroche5

# Description

Add wolfSSL_EC_KEY_print_fp to compat layer.

# Testing

Added a unit test.

# Checklist

 - [x] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2022-04-07 20:09 UTC, haydenroche5 commented on src/ssl.c
> +static int PrintBNFieldFp(XFILE fp, int indent, const char* field,
Moved this earlier in the file for use in the new function.

2022-04-08 04:40 UTC, SparkiDev requested changes

2022-04-08 04:40 UTC, SparkiDev commented on src/ssl.c
> +            != WOLFSSL_SUCCESS) {
wolfSSL_BN_is_zero() returns a boolean?
Treat as a boolean if so.

2022-04-25 23:51 UTC, SparkiDev approved these changes

2022-04-25 23:51 UTC, merged