Fixes for minor sniffer and async issues
wolfSSL/wolfssl pull request #5036
Opened 2022-04-08 19:05 UTC by dgarske

# Description

* Sniffer: Remove old restrictions for max strength, encrypt-then-mac and forcing openssl-extra.
* Fix bound warning with strncpy in sniffer.c
* Fix for async DH issue.
* Fix for SP math all not initializing raw big int.
* Fix for array bounds warning with "-O3" on `SetEccPublicKey`.

# Testing

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2022-04-10 22:47 UTC, SparkiDev approved these changes

2022-04-20 22:25 UTC, dgarske commented
@SparkiDev these are ready for merge. Thanks

2022-04-22 15:15 UTC, ejohnstown requested changes
The script sniffer-gen.sh is leaving a wolfSSL server running when it finishes.

2022-04-22 15:35 UTC, ejohnstown approved these changes

2022-04-22 19:24 UTC, merged