with WOLFSSL_NO_DH186 restriction allow odd DH param size generations
wolfSSL/wolfssl pull request #5080
Opened 2022-04-25 21:20 UTC by JacobBarthelmeh

# Description

When WOLFSSL_NO_DH186 is defined allow odd DH param size generations.

# Testing

Added test case to unit tests

# Checklist

 - [x] added tests

2022-04-26 18:15 UTC, dgarske approved these changes
This looks right to me, but I'd like @ejohnstown to confirm. Thanks Jacob.

2022-04-27 17:03 UTC, ejohnstown requested changes

2022-04-27 17:03 UTC, ejohnstown commented on wolfcrypt/test/test.c
>      ret = 0;
This became a dead store when adding your test case.

2022-05-13 15:56 UTC, ejohnstown approved these changes

2022-05-13 15:57 UTC, merged