Refactor wolfSSL_ASN1_TIME_adj to use Get (new API)
wolfSSL/wolfssl pull request #5111
Opened 2022-05-05 21:19 UTC by kaleb-himes

# Description

After evaluating numerous approaches to resolving the ABI-check-test issues reported by GCC 9 on the cloud slaves @dgarske noticed that the code in wolfSSL_ASN1_TIME_adj in ssl.c was awfully similar (nearly a copy/paste) of some code from the function GetAsnTimeString in asn.c. To that end we decided to kill two birds with 1 stone. This PR does a few things:

1) Adds a new internal API (not a public API) `GetUnformattedTimeString` to return just the time string (not compatible with the existing function `GetAsnTime()`). The new function takes input tm structure, a buffer to hold the output and a length to control the XSNPRINTF number of bytes to be printed into that buffer.
2) Refactors `GetAsnTimeString` to call `GetUnformattedTimeString` (a new API for both use cases) before adding the ASN formatting onto the returned string
3) Refactors `wolfSSL_ASN1_TIME_adj` to use this same new API `GetUnformattedTimeString`
4) Resolves the issues reported by the ABI-check-test 
5) Removes stack fluctuations between the UTC and GENERALIZE time cases by using a single buffer `uf_time` to store the unformatted time when called from the original function in asn.c `GetAsnTimeString`

Fixes ABI-check-test

# Testing

Tested using the cloud.

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2022-05-06 06:26 UTC, SparkiDev requested changes

2022-05-06 06:26 UTC, SparkiDev commented on wolfcrypt/src/asn.c
> +    if(data_len <= 0)
Do this check before the length check.

2022-05-06 06:26 UTC, SparkiDev commented on wolfcrypt/src/asn.c
> +    if(data_len <= 0)
Formatting:
 if (data_len <= 0)
and:
 }
 else {

2022-05-06 18:36 UTC, dgarske approved these changes
I pushed a few cleanups. Great refactor!

2022-05-06 18:51 UTC, kaleb-himes reviewed
Thanks so much @dgarske for the welcome text and format cleanups!

- Changes welcome and Approved

2022-05-08 23:15 UTC, SparkiDev approved these changes

2022-05-08 23:15 UTC, merged