CAAM support with QNX i.MX8, add AES-CTR crypto callback
wolfSSL/wolfssl pull request #5145
Opened 2022-05-13 19:27 UTC by JacobBarthelmeh

# Description

Adds support for i.MX8 + QNX + CAAM. Adds AES GCM/CCM/CBC/ECB modes to caam_driver.c.

# Testing

i.MX8 running wolfcrypt/test/test.c

2022-05-24 20:40 UTC, JacobBarthelmeh commented
retest this Jenkins

2022-06-02 23:19 UTC, dgarske requested changes
Looks great. Couple minor cleanups and should be ready to merge.

2022-06-02 23:19 UTC, dgarske commented on wolfcrypt/src/port/caam/caam_driver.c
> +static Error caamCreatePartition(unsigned int* page, unsigned int par,
Above spelling. `parition` -> `partition`

2022-06-02 23:19 UTC, dgarske commented on wolfcrypt/src/port/caam/caam_driver.c
> +    err = caamCreatePartition(&part, part, CAAM_SM_CSP | CAAM_SM_SMAP_LOCK |
Below spelling `partiions` -> `partitions`

2022-06-02 23:19 UTC, dgarske commented on wolfcrypt/src/port/caam/caam_driver.c
> +        reg = CAAM_READ(caam.baseAddr + CAAM_RDSTA);
Below `determinstic` -> `deterministic`

2022-06-02 23:19 UTC, dgarske commented on wolfcrypt/src/ecc.c
> +                    err = wc_export_int(&key->k, d, dLen, keySz + WC_CAAM_MAC_SZ, encType);
Alignment off

2022-06-02 23:19 UTC, dgarske commented on wolfcrypt/src/ecc.c
> +                else {
Should this blank else {} be removed?

2022-06-03 16:49 UTC, dgarske approved these changes

2022-06-03 22:24 UTC, merged