Provide access to "Finished" messages outside the compat layer.
wolfSSL/wolfssl pull request #5160
Opened 2022-05-19 20:45 UTC by haydenroche5

# Description

Prior to this commit, if you wanted access to the Finished messages from a handshake, you needed to turn on the compatibility layer, via one of OPENSSL_ALL, WOLFSSL_HAPROXY, or WOLFSSL_WPAS. With this commit, defining any of these causes WOLFSSL_HAVE_TLS_UNIQUE to be defined (a reference to the tls-unique channel binding which these messages are used for) in settings.h. This allows a user to define WOLFSSL_HAVE_TLS_UNIQUE to access the Finished messages without bringing in the whole compat layer.

Fixes ZD 14192.

# Testing

There are already tests exercising wolfSSL_get_finished and wolfSSL_get_peer_finished; those are still passing after this change. I also verified with gdb and the example server/client that the client/serverFinished fields of a WOLFSSL object do get populated if you configure with just `./configure CFLAGS="-g3 -O0" CPPFLAGS="-DWOLFSSL_HAVE_TLS_UNIQUE"`.

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2022-05-19 22:51 UTC, dgarske requested changes
Please updated api.c tests `test_client_get_finished`, `test_server_nofail` and `test_wolfSSL_reuse_WOLFSSLobj` to use the new macro for `wolfSSL_get_finished` and `wolfSSL_get_peer_finished`. See api.c around lines 4707. Replacing `#if defined(OPENSSL_ALL) || defined(WOLFSSL_HAPROXY) || defined(WOLFSSL_WPAS)` with `WOLFSSL_HAVE_TLS_UNIQUE`. Ideally if providing `WOLFSSL_HAVE_TLS_UNIQUE` the API unit tests will run.

2022-05-19 23:35 UTC, haydenroche5 commented
> Please updated api.c tests `test_client_get_finished`, `test_server_nofail` and `test_wolfSSL_reuse_WOLFSSLobj` to use the new macro for `wolfSSL_get_finished` and `wolfSSL_get_peer_finished`. See api.c around lines 4707. Replacing `#if defined(OPENSSL_ALL) || defined(WOLFSSL_HAPROXY) || defined(WOLFSSL_WPAS)` with `WOLFSSL_HAVE_TLS_UNIQUE`. Ideally if providing `WOLFSSL_HAVE_TLS_UNIQUE` the API unit tests will run.

Forgot to include those changes in the last commit. They're there now. Thanks.

2022-05-20 04:30 UTC, dgarske approved these changes

2022-05-20 04:30 UTC, merged

2022-07-28 12:50 UTC, Neustradamus commented
@haydenroche5, @dgarske: First thanks for your work!

It is official for TLS 1.3 Binding!
- RFC 9266: Channel Bindings for TLS 1.3: https://tools.ietf.org/html/rfc9266

Details:
- tls-unique for TLS =< 1.2
- tls-exporter for TLS = 1.3

Please read the RFC9266.

I have created a request to have a perfect TLS Binding support and security:
- https://github.com/wolfSSL/wolfssl/issues/5409

Thanks in advance.

2023-11-19 04:18 UTC, Neustradamus commented
Dear @wolfSSL team, @embhorn, @haydenroche5, @dgarske,

I think that you have seen the jabber.ru MITM and Channel Binding is the solution:
- https://notes.valdikss.org.ru/jabber.ru-mitm/
- https://snikket.org/blog/on-the-jabber-ru-mitm/
- https://www.devever.net/~hl/xmpp-incident
- https://blog.jmp.chat/b/certwatch

2025-11-13 06:21 UTC, Neustradamus commented
Dear @wolfSSL team, dear all,

After several years of patience, I recall you that:
- tls-unique is not secure, vulnerable
- tls-server-end-point support is always missing
- tls-exporter support is always missing

Thanks in advance.