Add support for some FPKI certificate cases, UUID, FASC-N, PIV extension
wolfSSL/wolfssl pull request #5167
Opened 2022-05-23 16:24 UTC by JacobBarthelmeh

# Description

Add support for some FPKI certificate cases, UUID, FASC-N, PIV extension

# Testing

Tested with wolfSSH connection and with additional unit test cases added in this PR.

# Checklist

 - [X] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2022-06-14 20:59 UTC, dgarske requested changes
Did you test this with `--enable-asn=template`?

2022-06-14 20:59 UTC, dgarske commented on tests/api.c
> +#if defined(WOLFSSL_FPKI)
Please wrap with `!defined(NO_FILESYSTEM)`.

2022-06-14 20:59 UTC, dgarske commented on tests/api.c
> +    fascn = (byte*)XMALLOC(fascnSz, DYNAMIC_TYPE_TMP_BUFFER, NULL);
Should be `fascn = (byte*)XMALLOC(fascnSz, NULL, DYNAMIC_TYPE_TMP_BUFFER);`

2022-06-14 20:59 UTC, dgarske commented on tests/api.c
> +    uuid = (byte*)XMALLOC(uuidSz, DYNAMIC_TYPE_TMP_BUFFER, NULL);
Should be `uuid = (byte*)XMALLOC(uuidSz, NULL, DYNAMIC_TYPE_TMP_BUFFER);`

2022-06-14 20:59 UTC, dgarske commented on tests/api.c
> +    XFREE(fascn, DYNAMIC_TYPE_TMP_BUFFER, NULL);
Should be `XFREE(fascn, NULL, DYNAMIC_TYPE_TMP_BUFFER);`

2022-06-14 20:59 UTC, dgarske commented on tests/api.c
> +    XFREE(uuid, DYNAMIC_TYPE_TMP_BUFFER, NULL);
Should be `XFREE(uuid, NULL, DYNAMIC_TYPE_TMP_BUFFER);`

2022-06-22 16:24 UTC, dgarske requested changes

2022-06-22 16:24 UTC, dgarske commented on wolfcrypt/src/asn.c
> + * WOLFSSL_SUBJ_INFO_ACC: Enable support for SubjectInfoAccess extension.
Can you also document `WOLFSSL_FPKI`?

2022-06-22 16:24 UTC, dgarske commented on wolfcrypt/src/asn.c
> +        return ret;
Does this need to free `cert->hwType` or is that handled by caller?

2022-06-22 16:24 UTC, dgarske commented on wolfcrypt/src/asn.c
> +    if (cert->hwSerialNum == NULL) {
Does this need to free `cert->hwType` or is that handled by caller?

2022-06-22 16:24 UTC, dgarske commented on wolfcrypt/src/asn.c
> +static DNS_entry* wc_GetAltName(struct DecodedCert* cert, int nameType,
Seems odd to use a public named API `wc_GetAltName` for a static. Can you rename to something else?

2022-06-22 16:24 UTC, dgarske commented on wolfssl/wolfcrypt/asn.h
> +    int        oidSum; /* provid oid sum for verification */
Spelling on `provide`.

2022-06-23 21:40 UTC, dgarske approved these changes
Looks good. I think @SparkiDev should also review.

2022-06-23 22:43 UTC, SparkiDev requested changes

2022-06-23 22:43 UTC, SparkiDev commented on wolfcrypt/src/asn.c
>   * Only support HW Name where the type is a HW serial number.
Add to the comment to indicate that what UPN and FASC-N are and how one of these will appear.

2022-06-26 22:25 UTC, SparkiDev approved these changes

2022-06-27 16:06 UTC, merged