Fix to move wolfSSL_ERR_clear_error outside gate for OPENSSL_EXTRA
wolfSSL/wolfssl pull request #5176
Opened 2022-05-24 21:25 UTC by embhorn

# Description

Fix to move `wolfSSL_ERR_clear_error` outside gate for `OPENSSL_EXTRA`.

Fixes zd14227

# Testing

Config with `DEBUG_WOLFSSL_VERBOSE`

Call `wolfSSL_ERR_clear_error` in application.

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2022-05-25 17:08 UTC, dgarske requested changes
Getting lots of build errors with:

2022-05-25 17:08 UTC, dgarske commented on src/ssl.c
> +    void wolfSSL_ERR_clear_error(void)
Do we really need the function wolfSSL_ERR_clear_error to be available in all cases? Perhaps just wrap in #if defined(OPENSSL_EXTRA) || defined(DEBUG_WOLFSSL_VERBOSE)?

2022-05-25 17:08 UTC, dgarske requested changes
```
./configure CFLAGS="-DDEBUG_WOLFSSL_VERBOSE" && make
...
src/ssl.c:6184:17: error: implicit declaration of function 'wolfSSL_ERR_peek_last_error' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                CLEAR_ASN_NO_PEM_HEADER_ERROR(pemErr);
                ^
./wolfssl/internal.h:4659:13: note: expanded from macro 'CLEAR_ASN_NO_PEM_HEADER_ERROR'
    (err) = wolfSSL_ERR_peek_last_error();                  \
            ^
src/ssl.c:6184:17: note: did you mean 'wolfSSL_ERR_peek_error'?
./wolfssl/internal.h:4659:13: note: expanded from macro 'CLEAR_ASN_NO_PEM_HEADER_ERROR'
    (err) = wolfSSL_ERR_peek_last_error();                  \
            ^
./wolfssl/ssl.h:2017:27: note: 'wolfSSL_ERR_peek_error' declared here
WOLFSSL_API unsigned long wolfSSL_ERR_peek_error(void);
                          ^
src/ssl.c:6184:17: error: implicit declaration of function 'ERR_GET_LIB' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                CLEAR_ASN_NO_PEM_HEADER_ERROR(pemErr);
                ^
./wolfssl/internal.h:4660:9: note: expanded from macro 'CLEAR_ASN_NO_PEM_HEADER_ERROR'
    if (ERR_GET_LIB(err) == ERR_LIB_PEM &&                  \
        ^
src/ssl.c:6184:17: error: implicit declaration of function 'ERR_GET_REASON' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
./wolfssl/internal.h:4661:13: note: expanded from macro 'CLEAR_ASN_NO_PEM_HEADER_ERROR'
            ERR_GET_REASON(err) == PEM_R_NO_START_LINE) {   \
            ^
src/ssl.c:6184:17: error: use of undeclared identifier 'ERR_LIB_PEM'
./wolfssl/internal.h:4660:29: note: expanded from macro 'CLEAR_ASN_NO_PEM_HEADER_ERROR'
    if (ERR_GET_LIB(err) == ERR_LIB_PEM &&                  \
                            ^
src/ssl.c:6184:17: error: use of undeclared identifier 'PEM_R_NO_START_LINE'
./wolfssl/internal.h:4661:36: note: expanded from macro 'CLEAR_ASN_NO_PEM_HEADER_ERROR'
            ERR_GET_REASON(err) == PEM_R_NO_START_LINE) {   \
                                   ^
src/ssl.c:7605:21: error: implicit declaration of function 'wolfSSL_ERR_peek_last_error' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                    CLEAR_ASN_NO_PEM_HEADER_ERROR(err);
                    ^
./wolfssl/internal.h:4659:13: note: expanded from macro 'CLEAR_ASN_NO_PEM_HEADER_ERROR'
    (err) = wolfSSL_ERR_peek_last_error();                  \
            ^
src/ssl.c:7605:21: error: implicit declaration of function 'ERR_GET_LIB' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
./wolfssl/internal.h:4660:9: note: expanded from macro 'CLEAR_ASN_NO_PEM_HEADER_ERROR'
    if (ERR_GET_LIB(err) == ERR_LIB_PEM &&                  \
        ^
src/ssl.c:7605:21: error: implicit declaration of function 'ERR_GET_REASON' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
./wolfssl/internal.h:4661:13: note: expanded from macro 'CLEAR_ASN_NO_PEM_HEADER_ERROR'
            ERR_GET_REASON(err) == PEM_R_NO_START_LINE) {   \
            ^
  CC       testsuite/testsuite_test-testsuite.o
src/ssl.c:7605:21: error: use of undeclared identifier 'ERR_LIB_PEM'
./wolfssl/internal.h:4660:29: note: expanded from macro 'CLEAR_ASN_NO_PEM_HEADER_ERROR'
    if (ERR_GET_LIB(err) == ERR_LIB_PEM &&                  \
                            ^
src/ssl.c:7605:21: error: use of undeclared identifier 'PEM_R_NO_START_LINE'
./wolfssl/internal.h:4661:36: note: expanded from macro 'CLEAR_ASN_NO_PEM_HEADER_ERROR'
            ERR_GET_REASON(err) == PEM_R_NO_START_LINE) {   \
                                   ^
10 errors generated.
```

2022-05-25 18:27 UTC, dgarske approved these changes
Thanks

2022-05-26 13:43 UTC, embhorn commented
Had to rebase with master to get the PRB tests passing.

2022-05-26 15:33 UTC, dgarske approved these changes

2022-05-26 15:33 UTC, merged