Support for SEGGER embOS and emNET
wolfSSL/wolfssl pull request #5221
Opened 2022-06-08 14:15 UTC by LinuxJedi

Adds support for embOS memory and mutex functions. Also adds support for
emNET's error codes, it uses a BSD compatible TCP/IP stack for network
functions.

There is no easy native way to detect that you are compiling with emNET
or embOS so these require the user to define `WOLFSSL_EMBOS` /
`WOLFSSL_EMNET`.

# Testing

Tested on SEGGER embOS / emNET with a S32K146 in SEGGER Embedded Studio.

2022-06-08 14:16 UTC, LinuxJedi commented
PR for the documentation for the new flags going to docs tree shortly.

2022-06-08 16:32 UTC, dgarske requested changes

2022-06-08 16:32 UTC, dgarske commented on wolfcrypt/src/memory.c
> +            #elif defined WOLFSSL_EMBOS
For consistency please use `()` `#elif defined(WOLFSSL_EMBOS)`

2022-06-08 16:32 UTC, dgarske commented on wolfcrypt/src/wc_port.c
> +        int iReturn;
Elsewhere we just use `int ret`.

2022-06-09 10:16 UTC, LinuxJedi commented
Closing as there are other issues with this I've found.

2022-06-09 10:16 UTC, closed without merging