zd14249
wolfSSL/wolfssl pull request #5242
Opened 2022-06-14 11:46 UTC by SKlimaRA

# Description

Added build flag to make DoVerifyCallback verify hostname or ip addr only against altnames instead of altnames and common name.

Fixes zd#14249

# Testing

How did you test?

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2022-06-14 15:50 UTC, dgarske commented
OK to test. @SKlimaRA is an approved contributor.

2022-06-15 19:00 UTC, dgarske requested changes
Please share a test case for reproducing. Thanks

2022-06-15 19:00 UTC, dgarske commented on src/internal.c
> +#ifndef ONLY_ALT_NAME_VERIFICATION
Can we rename this to something like `WOLFSSL_HOSTNAME_VERIFY_ALT_NAME_ONLY`? Please add description of build option at top of internal.c with others.

2022-06-15 19:00 UTC, dgarske commented on src/internal.c
> +#endif /* #ifndef ONLY_ALT_NAME_VERIFICATION */
Syntax should be `#endif /* !ONLY_ALT_NAME_VERIFICATION */`

2022-06-20 09:31 UTC, SKlimaRA commented
I will share the test case later. Please wait. Thanks.

2022-06-21 14:44 UTC, SKlimaRA commented
Hey @dgarske ,
could you please desribe the test case you want.
I'm using our server and client to testing this and I can't share the code for these. But I could share the certificates and keys for this test case.
Thanks.

2022-06-21 18:19 UTC, dgarske requested changes
Is it possible to refactor the code to use the common name if subject alternate name (SAN) is not provided in the certificate? Or is it your intention to reject certificates without a SAN with this build option.

Test case is tough since it is a build option and we'll need to add to our internal CI. I'll have to think about it. Perhaps let's discuss in the ZenDesk ticket?

2022-06-28 16:30 UTC, dgarske approved these changes
Thanks @SKlimaRA . I had missed your latest commit. I'd like another engineer @SparkiDev to also review this change before it gets merged.

2022-06-28 22:40 UTC, SparkiDev commented
ProcessPeerCerts() checks domain name.
Did you consider changes to this function as well?

2022-06-29 08:09 UTC, SKlimaRA commented
Hi @SparkiDev 
I guess we could replicate the changes to ProcessPeerCerts() but I don't think it's necessary for us now.
Please let me know if you would prefer making the changes to ProcessPeerCerts().
Thanks

2022-06-29 22:19 UTC, SparkiDev commented
This PR fixes the ticket, so I'll merge this as is.

2022-06-29 22:19 UTC, SparkiDev approved these changes

2022-06-29 22:19 UTC, merged