examples: update usage() with DTLSv1.3 version
wolfSSL/wolfssl pull request #5266
Opened 2022-06-20 05:46 UTC by rizlik

# Description

Update help message of example/client and example/server to include DTLSv1.3

2022-06-20 05:48 UTC, rizlik commented
@miyazakh can you please add to the Japanese part as well?

2022-06-21 07:30 UTC, rizlik commented
> @miyazakh can you please add to the Japanese part as well?

@miyazakh will open a separate PR for the Japanese line

2022-06-21 16:54 UTC, dgarske requested changes

2022-06-21 16:54 UTC, dgarske commented on examples/client/client.c
> +#ifndef WOLFSSL_DTLS13
Can you fix the idents so they match? Does the SCTP DTLS section below need updated too (guessing no)?

2022-06-22 16:50 UTC, rizlik commented on examples/server/server.c
> +#ifndef WOLFSSL_DTLS13
indent fixed. 
No, we do not support SCTP yet.

2022-06-23 16:27 UTC, merged