SP math all: fix div word for ARM32
wolfSSL/wolfssl pull request #5322
Opened 2022-07-06 05:35 UTC by SparkiDev

# Description
i
Fix ASM code for ARM32 sp_div_word() when not using udiv.
Fixup sp_mulmod NULL access.

Fixes zd#

# Testing

Regression tested ARM32 SP math all.

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2022-07-06 17:14 UTC, douzzer requested changes
Seeing a build failure with  `--host=armv7a-unknown-linux-gnueabihf` on new inline asm in sp_int.c:
```
/tmp/tmp.4346_8721/ccXgLCyP.s: Assembler messages:
/tmp/tmp.4346_8721/ccXgLCyP.s:2569: Error: shift expression expected -- `subs r9,r9,1'
/tmp/tmp.4346_8721/ccXgLCyP.s:2993: Error: shift expression expected -- `subs r9,r9,1'
/tmp/tmp.4346_8721/ccXgLCyP.s:4533: Error: shift expression expected -- `subs r9,r9,1'
make[2]: *** [Makefile:5714: wolfcrypt/src/src_libwolfssl_la-sp_int.lo] Error 1
```

FWIW, `aarch64-unknown-linux-gnu` builds and testwolfcrypts successfully with same config.

2022-07-06 22:57 UTC, SparkiDev commented
Updated to fix ARMv7a issue.

2022-07-07 01:41 UTC, dgarske approved these changes

2022-07-07 02:48 UTC, douzzer approved these changes
Cool now, clean builds and unit.tests, --enable-all --enable-sp-asm, on armv7a-unknown-linux-gnueabihf and armv6zk-hardfloat-linux-gnueabi.

2022-07-07 03:18 UTC, merged