Support for asynchronous session ticket callback
wolfSSL/wolfssl pull request #5347
Opened 2022-07-11 23:15 UTC by dgarske

# Description

Support for asynchronous session ticket callback (can return WC_PENDING_E). Requires wolfAsyncCrypt support.
ZD 14420.

# Testing

I tested using:
```
./configure --enable-all --enable-asynccrypt --enable-debug --disable-shared CFLAGS="-DWOLFSSL_NO_DEF_TICKET_ENC_CB"
make
./examples/server/server &
./examples/client/client
```

I added some logic to return a WC_PENDING_E in wc_ChaCha20Poly1305_Encrypt as a test like this:
```
#ifdef WOLFSSL_ASYNC_CRYPT
    static int testAsync;
    if ((testAsync++ % 2) == 0) {
        return WC_PENDING_E;
    }
#endif
```

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2022-07-20 22:20 UTC, SparkiDev requested changes

2022-07-20 22:20 UTC, SparkiDev commented on wolfssl/test.h
> +        if (ret == 0) {
You can pull the if back an indent.

2022-07-20 23:39 UTC, dgarske commented on wolfssl/test.h
> +    wc_AesFree(&aes);
Free still needed, but bugs with the AES GCM case `./configure --enable-session-ticket CFLAGS="-DWOLFSSL_NO_DEF_TICKET_ENC_CB" --disable-chacha --disable-poly1305`. Fixed.

2022-07-20 23:54 UTC, SparkiDev commented on wolfssl/test.h
> +    wc_AesFree(&aes);
init and free can be done outside of function.
Set key should be enough to start new encrypt/decrypt.
Code works as is, so will leave it.

2022-07-20 23:54 UTC, SparkiDev approved these changes

2022-07-21 16:50 UTC, dgarske commented on wolfssl/test.h
> +    wc_AesFree(&aes);
I setup the test case like this for the customer who wants the AES GCM processing to return WC_PENDING_E.

2022-07-21 22:04 UTC, merged