Announce TLSX_PSK_KEY_EXCHANGE_MODES in non-resuming ClientHello
wolfSSL/wolfssl pull request #5382
Opened 2022-07-21 09:04 UTC by icing

# Description

QUIC interop testing revealed that (at least popular QUIC stacks) refrain from
issuing session tickets unless the ClientHello shows this extension.

Can be reverted to previous style by defining NO_TLSX_PSKKEM_PLAIN_ANNOUNCE.

Fixes zd#

# Testing

`make test`

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [x] updated appropriate READMEs
 - [ ] Updated manual and documentation

2022-07-21 16:24 UTC, dgarske commented
OK to test

2022-07-21 22:17 UTC, SparkiDev commented on src/tls.c
> +            if (1) {
Prefer this pattern:
```
ifdef ...
    if (usingPSK)
endif
    {
        ...
    }
```

2022-07-26 22:58 UTC, dgarske requested changes

2022-07-26 22:58 UTC, dgarske commented on README.md
> +* The TLS Extension for PSK Key Exchange Modes is now always included in a ClientHello (with PSK enabled) to improve inter-op.
The change log is compiled at release time. The text you want should be in the Git commit. We toyed with having a future release section above this, but causes lots of merge conflicts. Easier to do at release time.

2022-07-26 22:58 UTC, dgarske commented on src/tls.c
> +            if (1) {
I agree. Please refactor.

2022-07-29 09:27 UTC, icing commented on README.md
> +* The TLS Extension for PSK Key Exchange Modes is now always included in a ClientHello (with PSK enabled) to improve inter-op.
Remove it again.

2022-07-29 09:28 UTC, icing commented on src/tls.c
> +            if (1) {
Changed accordingly. Please review.

2022-07-29 13:42 UTC, dgarske approved these changes

2022-07-31 22:07 UTC, SparkiDev approved these changes

2022-08-03 14:40 UTC, merged

2022-08-03 16:32 UTC, icing commented
Thanks!