doClientKeyExchange improvements
wolfSSL/wolfssl pull request #5402
Opened 2022-07-26 18:16 UTC by rizlik

# Description
Improve doClientKeyExchange code

# Testing
`./configure --enable-all && make check`

2022-07-26 20:56 UTC, dgarske commented
@SparkiDev and @kaleb-himes

I am working on fixing the Jenkins error. I can reproduce only on Ubuntu using:

```
./configure --enable-dtls --enable-dtls-mtu --enable-maxfragment --enable-secure-renegotiation CFLAGS="-DWOLFSSL_STATIC_RSA -DWOLFSSL_STATIC_DH" CC="clang -fsanitize=address"  && make
./examples/server/server -v 2 -l AES128-SHA -2 &
./examples/client/client -v 2 -l AES128-SHA -2

received record layer msg
got CHANGE CIPHER SPEC
growing input buffer
Verify MAC of Encrypted Data
VerifyMacEnc failed
wolfSSL error occurred, error = -305
wolfSSL error occurred, error = -312
```

2022-07-26 22:34 UTC, SparkiDev requested changes

2022-07-26 22:34 UTC, SparkiDev commented on src/internal.c
> +    ctMaskCopy(mask, (byte*)out, (byte*)&outTmp, (byte*)out, sizeof(*out));
Prefer the ctMaskCopy copied over existing buffer when mask is set.
Then you can use:
    r[i] ^= (r[i] ^ a[i]) & mask;

2022-07-26 22:34 UTC, SparkiDev commented on src/internal.c
> +    ctMaskCopy(mask, (byte*)outSz, (byte*)&outSzTmp, (byte*)outSz, sizeof(*outSz));
*outSz ^= (*outSz ^ outSzTmp) & mask;

2022-07-26 22:34 UTC, SparkiDev commented on src/internal.c
> +    ctMaskCopy(mask, (byte*)&ret, (byte*)&zero, (byte*)&ret, sizeof(ret));
ret &= mask

2022-07-26 22:55 UTC, dgarske commented
@SparkiDev , since Marco is out can you please refactor the code how you suggested?

2022-07-27 03:37 UTC, SparkiDev approved these changes

2022-07-27 15:00 UTC, dgarske approved these changes

2022-07-27 15:01 UTC, merged