Add liboqs integration to CMake build system
wolfSSL/wolfssl pull request #5407
Opened 2022-07-27 09:58 UTC by darktohka

# Description
Currently, compiling WolfSSL with liboqs is only possible with the configure system.

I've created this PR to add liboqs support to the CMake build system. Now, CMake can detect liboqs and link to it when building with WOLFSSL_OQS on.

I've added a new CMake option: `WOLFSSL_OQS`, which is disabled by default. When enabled, CMake will look for the liboqs library, and, if found, will link and include it to the wolfssl library. This matches the behavior of the configure system.

# Testing

I've tested this option with multiple configurations:
- WOLFSSL_OQS off, no liboqs installed on system --> nothing happens
- WOLFSSL_OQS on, no liboqs installed on system --> nothing happens
- WOLFSSL_OQS on, liboqs installed on system as shared library --> liboqs is successfully linked to wolfssl dynamically
- WOLFSSL_OQS on, liboqs installed on system as static library --> liboqs is successfully linked to wolfssl statically

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2022-07-27 13:51 UTC, anhu requested changes

2022-07-27 13:51 UTC, anhu commented on CMakeLists.txt
> +    "Enable integration with the OQS (Open Quantum Safe) library (default: disabled)"
"library" ---> "liboqs library"

2022-07-27 14:01 UTC, darktohka commented
Thank you @anhu! I've e-mailed the address you've given me and will update this thread when I hear back.

2022-07-27 14:17 UTC, anhu commented
On-hold until contributor agreement has been approved.

2022-07-27 14:18 UTC, anhu approved these changes

2022-08-01 13:30 UTC, embhorn commented
Approved as contributor.

2022-08-04 15:42 UTC, dgarske commented
retest this please

2022-08-11 19:25 UTC, anhu commented
retest this please

2022-08-12 14:45 UTC, anhu commented
Hi @darktohka , 

The failing test indicates that you will need to add an entry into `cmake/include.am` for the new file that you created. 

Warm regards, Anthony

2022-08-12 20:16 UTC, darktohka commented
Thank you @anhu, I have made the requested change.

2022-08-12 20:22 UTC, anhu commented
Excellent!  Once the tests pass, I will squash and merge your changes.

2022-08-12 20:23 UTC, merged