Add missing BIO_should_read and BIO_should_write functions
wolfSSL/wolfssl pull request #5410
Opened 2022-07-27 14:40 UTC by darktohka

# Description
Currently, BIO_should_retry exists as a component of the OpenSSL compatibility layer. However, there is no way to check the should_read/should_write flag of a BIO object - the BIO_should_read and BIO_should_write functions from OpenSSL are not implemented.

I've implemented the two missing functions as `wolfSSL_BIO_should_read` and wolfSSL_BIO_should_write` by letting wolfSSL check the flags of the BIO, then created the compatibility definitions for `BIO_should_read` and `BIO_should_write` in the OpenSSL compatibility header.

# Testing

I've created two unit tests, `test_wolfSSL_BIO_should_read` and `test_wolfSSL_BIO_should_write`. They each test the respective function before creating the connection and when a read or write is expected to happen.

I've ran the unit_test program after creating these unit tests, and all unit tests completed successfully.

# Checklist

 - [X] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2022-08-01 13:31 UTC, embhorn commented
Approved as contributor.

2022-08-01 13:31 UTC, embhorn commented
Okay to test

2022-08-02 21:17 UTC, dgarske commented
retest this please

2022-08-03 14:26 UTC, dgarske commented
@darktohka :

```
Testing: ./configure --enable-all
Running: make check
make[2]: warning: -j5 forced in submake: resetting jobserver mode.
tests/api.c:40013:10: error: unused variable 'ret' [-Werror,-Wunused-variable]
    int  ret;
         ^
tests/api.c:40051:14: error: variable 'bio' is uninitialized when used here [-Werror,-Wuninitialized]
    BIO_read(bio, reply, sizeof(reply));
             ^~~
tests/api.c:40014:13: note: initialize the variable 'bio' to silence this warning
    BIO* bio;
            ^
             = NULL
tests/api.c:40048:26: error: variable 'ssl' is uninitialized when used here [-Werror,-Wuninitialized]
    wolfSSL_SSLSetIORecv(ssl, EmbedReceive);
                         ^~~
tests/api.c:40009:21: note: initialize the variable 'ssl' to silence this warning
    WOLFSSL*     ssl;
                    ^
                     = NULL
tests/api.c:40084:10: error: unused variable 'ret' [-Werror,-Wunused-variable]
    int  ret;
         ^
tests/api.c:40121:14: error: variable 'bio' is uninitialized when used here [-Werror,-Wuninitialized]
    BIO_read(bio, reply, sizeof(reply));
             ^~~
tests/api.c:40085:13: note: initialize the variable 'bio' to silence this warning
    BIO* bio;
            ^
             = NULL
tests/api.c:40118:26: error: variable 'ssl' is uninitialized when used here [-Werror,-Wuninitialized]
    wolfSSL_SSLSetIORecv(ssl, EmbedReceive);
                         ^~~
tests/api.c:40080:21: note: initialize the variable 'ssl' to silence this warning
    WOLFSSL*     ssl;
                    ^
                     = NULL
6 errors generated.
```

2022-08-03 14:28 UTC, dgarske requested changes
Please fix the compiler errors in api.c.

2024-06-17 17:37 UTC, JacobBarthelmeh commented
BIO_should_read and BIO_should_write was added here https://github.com/wolfSSL/wolfssl/pull/6235

2024-06-17 17:37 UTC, closed without merging