Fix so curl can do FTPS on TLS 1.3.
wolfSSL/wolfssl pull request #5424
Opened 2022-07-29 21:14 UTC by anhu

Session cache seems to be incompatible with calling get_session() early in TLS 1.3

2022-07-29 21:23 UTC, anhu commented
Steps for testing....
Build wolfssl with following configuration:

`./configure --enable-curl`

Build curl with following configuration: 

`./configure --with-wolfssl`

Configure a filezilla server to support explicit ftps and point it to the right server cert and key and then connect to it via curl: 

`curl -T README ftps://www.wolfssl.com:21/out.txt --tlsv1.2 --cacert ca.cert -u user:password`

If you use wolfssl without this PR the transmission will fail and the following message will be seen in filezilla-server logs: 

`425 Unable to build data connection: TLS session of data connection not resumed.`

With this PR , it will successfully transfer and there will be no error message.

2022-07-29 22:55 UTC, anhu commented
Assigned to @dgarske as he has a different approach.

2022-08-01 19:10 UTC, dgarske commented
@anhu needs help reproducing. Tried on Mac, Linux and Windows with FileZilla and not able to get it working with curl. The steps for setting up FileZilla need expanded.

2022-08-01 22:24 UTC, dgarske commented
All Fixed. @julek-wolfssl please take a look. Let me know if you want help to reproduce. The code in curl that relies on the session pointer is here: https://github.com/curl/curl/blob/master/lib/vtls/wolfssl.c#L818

2022-08-02 10:53 UTC, julek-wolfssl requested changes
I don't agree that this is a safe solution to provide backwards compatibility. Previously, `wolfSSL_get_session` would always return a persistent pointer into the session cache if a cache entry existed or `NULL` otherwise. This was retracted to only apply to the client side since the server doesn't have much of a use case for the session after the connection is done. I don't think that sometimes returning a persistent pointer and sometimes an allocated pointer is the correct or safe solution. Users don't even have a way of knowing which is which.

This is the exact use case that `NO_SESSION_CACHE_REF` was written for ie: for users that are ready to observe the rule that `SSL_get_session` returns allocated pointers with the lifespan of the `SSL` object and `SSL_get1_session` returns pointers that can be used to resume sessions but need to be free'd.

Looking at `wolfssl_connect_step3`, I think that defining `NO_SESSION_CACHE_REF` should be the safe and correct solution. Is there any reason why this path wasn't taken?

2022-08-02 14:30 UTC, dgarske commented
> I don't agree that this is a safe solution to provide backwards compatibility. Previously, `wolfSSL_get_session` would always return a persistent pointer into the session cache if a cache entry existed or `NULL` otherwise. This was retracted to only apply to the client side since the server doesn't have much of a use case for the session after the connection is done. I don't think that sometimes returning a persistent pointer and sometimes an allocated pointer is the correct or safe solution. Users don't even have a way of knowing which is which.
> 
> This is the exact use case that `NO_SESSION_CACHE_REF` was written for ie: for users that are ready to observe the rule that `SSL_get_session` returns allocated pointers with the lifespan of the `SSL` object and `SSL_get1_session` returns pointers that can be used to resume sessions but need to be free'd.
> 
> Looking at `wolfssl_connect_step3`, I think that defining `NO_SESSION_CACHE_REF` should be the safe and correct solution. Is there any reason why this path wasn't taken?

That is how @anhu originally fixed it. But it doesn't feel right to me to set it for all of Curl to resolve a backwards compatibility issue. However you are right the FTP code is comparing pointers so the only safe solution is `NO_SESSION_CACHE_REF`. I'll put it back.

Thanks

2022-08-02 14:41 UTC, dgarske approved these changes

2022-08-02 14:45 UTC, julek-wolfssl requested changes

2022-08-02 14:45 UTC, julek-wolfssl commented on configure.ac
> +    # FTPS server requires peristent pointer to session cache
Let's just update this comment. The FTPS server requires a `NO_SESSION_CACHE_REF` to always have a session pointer. It does not need to be "peristent".

2022-08-02 21:08 UTC, julek-wolfssl approved these changes

2022-08-02 21:22 UTC, merged

2022-08-02 21:24 UTC, julek-wolfssl commented
Let's encourage more `NO_SESSION_CACHE_REF` usage!