Expand error queue usage with new macro WOLFSSL_ERROR_VERBOSE.
wolfSSL/wolfssl pull request #5431
Opened 2022-08-02 20:58 UTC by haydenroche5

# Description

We have users who need to debug errors coming out of libwolfssl in production,
where --enable-debug isn't an option. Our error queue implementation is the
solution, but our usage of WOLFSSL_ERROR isn't consistent. This commit greatly
expands our usage of WOLFSSL_ERROR. There are too many error cases to tackle
all at once, and not all error cases are particularly meaningful or likely to be
hit in regular operation of the library. I've tried to focus on errors that
users are likely to hit, and I've chosen to ignore things like the mountain of
BUFFER_E and BAD_FUNC_ARG cases (for the most part). I've also tried to expand
WOLFSSL_ERROR usage in files where we haven't been using it historically
(e.g. aes.c), so the pattern is now there for other developers to follow. In
order to prevent these additions from exploding the size of libwolfssl, they're
all behind a new macro, WOLFSSL_ERROR_VERBOSE. If WOLFSSL_VERBOSE_ERRORS is
defined, WOLFSSL_ERROR_VERBOSE just maps to WOLFSSL_ERROR.

# Testing

No tests added.

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2022-08-04 21:48 UTC, dgarske requested changes

2022-08-04 21:48 UTC, dgarske commented on src/tls13.c
> +        /* TODO: HAYDEN: stopped here. */
? Is this still valid

2022-08-04 21:54 UTC, haydenroche5 commented on src/tls13.c
> +        /* TODO: HAYDEN: stopped here. */
Definitely not valid. Will cleanup.

2022-08-05 17:57 UTC, dgarske approved these changes

2022-08-05 22:14 UTC, merged