Allow Post Quantum Keyshare for DTLS 1.3
wolfSSL/wolfssl pull request #5518
Opened 2022-08-28 06:13 UTC by CallumMcLoughlin

# Description

Adds support for specifying post quantum key exchange within DTLS 1.3 through `wolfSSL_UseKeyShare`.

# Testing

- `wolfSSL_get_curve_name` on both a test client and server return specified post quantum curve, e.g `KYBER_LEVEL5`. 
- Tracing through the associated calls shows `server_generate_pqc_ciphertext` is reached on the server side of the connection. 
- Tested with all kyber KEM versions, and SECP256R1/521R1
- Tested with RSA certificate chains, and Dilithium certificate chains

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2022-08-30 06:55 UTC, CallumMcLoughlin commented
Yep, looks like I missed a couple checks on the server and client examples. 

I have tested on a few post quantum curves and it all looks good, an example output using `./server/server -u -v 4 --pqc KYBER_LEVEL5`:
```
Using Post-Quantum KEM: KYBER_LEVEL5
Alternate cert chain used
 issuer : /C=US/ST=Montana/L=Bozeman/O=wolfSSL_2048/OU=Programming-2048/CN=www.wolfssl.com/emailAddress=info@wolfssl.com
 subject: /C=US/ST=Montana/L=Bozeman/O=wolfSSL_2048/OU=Programming-2048/CN=www.wolfssl.com/emailAddress=info@wolfssl.com
 altname = example.com
 serial number:01:1a:eb:56:ab:dc:8b:f3:a6:1e:f4:93:60:89:b7:05:07:29:01:2c
SSL version is DTLSv1.3
SSL cipher suite is TLS_AES_128_GCM_SHA256
SSL signature algorithm is (null)
SSL curve name is KYBER_LEVEL5
Server Random : E510949788D37C51D6F4A9AAEFE5F9320A26799A4C9644B8F445FD56EF68DC47
Client message: hello wolfssl!
```

With the corresponding client `./client/client -u -v 4 --pqc KYBER_LEVEL5`
```
Using Post-Quantum KEM: KYBER_LEVEL5
Alternate cert chain used
 issuer : /C=US/ST=Montana/L=Bozeman/O=Sawtooth/OU=Consulting/CN=www.wolfssl.com/emailAddress=info@wolfssl.com
 subject: /C=US/ST=Montana/L=Bozeman/O=wolfSSL/OU=Support/CN=www.wolfssl.com/emailAddress=info@wolfssl.com
 altname = example.com
 serial number:01
SSL version is DTLSv1.3
SSL cipher suite is TLS_AES_128_GCM_SHA256
SSL signature algorithm is (null)
SSL curve name is KYBER_LEVEL5
Session timeout set to 500 seconds
Client Random : CFFA0B1628E1C6D21F046FA66CBDAE1948F227DFF8F7B0F00CE19C3E7794B780
I hear you fa shizzle!
```

Having a mismatched `--pqc` flag (e.g `KYBER_LEVEL1` and `KYBER_LEVEL3`) raises this error on the server side:
```
Using Post-Quantum KEM: KYBER_LEVEL1
SSL_accept error -173, Bad function argument
wolfSSL error: SSL_accept failed
```

However, I did notice that my changes on the examples made it so that you're able to `--force-curve` using DTLS 1.3 whereas previously you were unable to using the examples.

For example, before my changes `./server/server -u -v 4 --force-curve SECP521R1`  and `./client/client -u -v 4` resulted in `SSL curve name is SECP256R1`, and after my changes the same commands resulted in `SSL curve name is SECP521R1` which I assume is (now) expected behaviour?

Let me know if theres anything else I missed -- i'm still a little new to this whole thing :-)

2022-08-30 07:40 UTC, rizlik requested changes
Hi @CallumMcLoughlin,
Thanks for the nice work!
I left you a small comment

2022-08-30 07:40 UTC, rizlik commented on src/tls13.c
> +            (ssl->ctx->method->version.minor != TLSv1_3_MINOR &&
I would use ` IsAtLeastTLSv1_3` instead

2022-08-30 08:02 UTC, CallumMcLoughlin commented on src/tls13.c
> +            (ssl->ctx->method->version.minor != TLSv1_3_MINOR &&
Done, thanks for that!

2022-08-30 16:46 UTC, anhu commented
Built with the following configuration: 

`./configure --enable-dtls --enable-dtls13 --with-liboqs`

...and tested with the example server and client as above.

2022-08-30 16:51 UTC, dgarske commented
FYI: Eric sent @CallumMcLoughlin the contributor agreement, waiting for it to come back. ZD 14705.

2022-08-30 17:12 UTC, anhu approved these changes

2022-08-30 17:14 UTC, anhu commented
Thanks for your efforts making the changes and tracing through the code.  This is excellent!

2022-08-31 07:33 UTC, rizlik approved these changes

2022-08-31 14:25 UTC, embhorn commented
Okay to test

2022-08-31 14:25 UTC, embhorn commented
@CallumMcLoughlin - you are an approved contributor to the wolfSSL project!

2022-08-31 16:12 UTC, dgarske commented
OK to test

2022-08-31 17:20 UTC, dgarske approved these changes

2022-08-31 19:29 UTC, merged