Add test case for partial EVP_CipherInit
wolfSSL/wolfssl pull request #5527
Opened 2022-08-31 08:31 UTC by icing

# Description

This test shows the failure in setting key and iv separately on a EVP_CIPHER_CTX for EVP_chacha20_poly1305. An API behaviour that OpenSSL allows.

# Testing

make test

# Checklist

 - [ x] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2022-08-31 17:30 UTC, dgarske requested changes
The API unit test is failing with `./configure --enable-all`.

```
wc_ChaCha20Poly1305_UpdateAad failed
   test_wolfssl_EVP_chacha20_poly1305:
ERROR - tests/api.c line 52054 failed with:
    expected: wolfSSL_EVP_CipherUpdate(ctx, ((void *)0), &outSz, aad, sizeof(aad)) == WOLFSSL_SUCCESS
    result:   0 != 1
```

2022-09-01 14:28 UTC, icing commented
> The API unit test is failing with `./configure --enable-all`.
> 
> ```
> wc_ChaCha20Poly1305_UpdateAad failed
>    test_wolfssl_EVP_chacha20_poly1305:
> ERROR - tests/api.c line 52054 failed with:
>     expected: wolfSSL_EVP_CipherUpdate(ctx, ((void *)0), &outSz, aad, sizeof(aad)) == WOLFSSL_SUCCESS
>     result:   0 != 1
> ```

Exactly what I wanted to show in the test. The fix for this is now included as well.

2022-09-01 14:57 UTC, dgarske requested changes
```In file included from ./wolfssl/internal.h:27,
                 from src/ssl.c:37:
./wolfcrypt/src/evp.c: In function ‘int wolfSSL_EVP_CipherInit(WOLFSSL_EVP_CIPHER_CTX*, const WOLFSSL_EVP_CIPHER*, const byte*, const byte*, int)’:
./wolfssl/wolfcrypt/types.h:505:67: error: invalid conversion from ‘void*’ to ‘byte*’ {aka ‘unsigned char*’} [-fpermissive]
  505 |                 #define XMALLOC(s, h, t)     ((void)(h), (void)(t), wolfSSL_Malloc((s)))
      |                                              ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
      |                                                                   |
      |                                                                   void*
./wolfcrypt/src/evp.c:6636:32: note: in expansion of macro ‘XMALLOC’
 6636 |                     ctx->key = XMALLOC(ctx->keyLen, NULL,
      |                                ^~~~~~~```

2022-09-01 15:21 UTC, icing commented
> from src/ssl.c:37:
> ./wolfcrypt/src/evp.c: In function ‘int wolfSSL_EVP_CipherInit(WOLFSSL_EVP_CIPHER_CTX*, const WOLFSSL_EVP_CIPHER*, const byte*, const byte*, int)’:
> ./wolfssl/wolfcrypt/types.h:505:67: error: invalid conversion from ‘void*’ to ‘byte*’ {aka ‘unsigned char*’} [-fpermissive]
>   505 |                 #define XMALLOC(s, h, t)     ((void)(h), (void)(t), wolfSSL_Malloc((s)))
>       |                                              ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
>       |                                                                   |
>       |                                                                   void*
> ./wolfcrypt/src/evp.c:6636:32: note: in expansion of macro ‘XMALLOC’
>  6636 |                     ctx->key = XMALLOC(ctx->keyLen, NULL,
>       |                                ^~~~~~~```

One day, I'll learn this. Pushed a fix.

2022-09-01 16:28 UTC, dgarske requested changes

2022-09-01 16:28 UTC, dgarske commented on wolfcrypt/src/evp.c
> +                XFREE(ctx->key, NULL, DYNAMIC_TYPE_OPENSSL);
This is allocated with `DYNAMIC_TYPE_TMP_BUFFER` and free'd with `DYNAMIC_TYPE_OPENSSL`. The XMALLOC and XFREE dynamic types need to match.

2022-09-01 17:57 UTC, dgarske approved these changes

2022-09-01 20:23 UTC, merged