Check return from call to wc_Time
wolfSSL/wolfssl pull request #5531
Opened 2022-08-31 18:29 UTC by embhorn

# Description

`wc_ValidateDate` should check that the system time returned is a valid value (`>=0`). This can occur if a 32-bit clib time function is used after Jan. 19, 2038

Fixes zd14665

# Testing

* Install 32-bit lib:
`sudo apt-get install gcc-multilib`
* Build with:
`./configure --enable-debug --enable-32bit CFLAGS="-m32" LDFLAGS="-m32"`
`make && sudo make install`
* Set system clock to 2038 (I just used GUI clock settings)
* Run any cert verify app. I used wolfssl-examples/certmanager/certverify.c

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2022-08-31 19:42 UTC, dgarske requested changes

2022-08-31 19:42 UTC, dgarske commented on wolfcrypt/src/asn.c
> +    if (ltime < 0){
It appears `time_t` is typically signed and is a `long`. For 32-bit systems long is 32-bits. This check seems valid.

2022-08-31 19:42 UTC, dgarske commented on wolfcrypt/src/asn.c
> +        return(0);
Prefer syntax `return 0;`. To match our coding style.

2022-08-31 19:42 UTC, dgarske commented on wolfcrypt/src/asn.c
> +        /* This could be because 32-bit and the year is >=2038 */
How about: `A negative response here could be due to a 32-bit time_t where the year is 2038 or later.`

2022-08-31 20:36 UTC, dgarske approved these changes

2022-09-01 14:35 UTC, douzzer approved these changes
LGTM!

2022-09-01 14:35 UTC, merged