Add wolfSSL_EVP_PKEY_new_CMAC_key to OpenSSL compatible API
wolfSSL/wolfssl pull request #5538
Opened 2022-09-01 09:44 UTC by satoshiyamaguchi

# Description

This PR adds wolfSSL_EVP_PKEY_new_CMAC_key() to the OpenSSL compatible API.
Details:
- add CMAC_CTX parameter to EVP_PKEY structure, because CMAC generation needs CMAC_CTX.
- generate CMAC_CTX and register it to EVP_PKEY in wolfSSL_EVP_PKEY_new_CMAC_key().
  (It was created with reference to an existing API, wolfSSL_EVP_PKEY_new_mac_key())
- add a constant EVP_PKEY_CMAC.

wolfSSL_EVP_PKEY_new_CMAC_key() is for generating EVP_PKEY data having a CMAC key.
The generated EVP_PKEY is given to EVP_DigestSignInit().
And the following APIs are used for generating CMAC. 
 - EVP_DigestSignInit()
 - EVP_DigestSignUpdate()
 - EVP_DigestSignFinal()

# Testing

Built example app using wolfSSL_EVP_PKEY_new_CMAC_key() and ran it.
Checked if wolfSSL_EVP_PKEY_new_CMAC_key() returns EVP_PKEY structure
and if EVP_PKEY_id() can return EVP_PKEY_CMAC (==894).

# Checklist

 - [x] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2022-09-01 15:04 UTC, dgarske commented
OK to test

2022-09-01 18:03 UTC, dgarske requested changes
```
Testing: ./configure --enable-all
Running: make check
make[2]: warning: -j5 forced in submake: resetting jobserver mode.
In file included from src/ssl.c:180:
./wolfcrypt/src/evp.c:3439:29: error: implicit conversion loses integer precision: 'size_t' (aka 'unsigned long') to 'int' [-Werror,-Wshorten-64-to-32]
            pkey->pkey_sz = len;
                          ~ ^~~
1 error generated.
```

2022-09-05 11:06 UTC, kaleb-himes commented
retest this please

2022-09-17 15:05 UTC, satoshiyamaguchi commented
@dgarske  EVP_KEY data was not freed in unit test. So I changed unit test and  wolfSSL_EVP_PKEY_free so that EVP_KEY is freed correctly.

2022-09-19 16:34 UTC, dgarske requested changes

2022-09-19 16:34 UTC, dgarske commented on wolfcrypt/src/evp.c
> +        return NULL;
This will leak `ctx`.

2022-09-20 15:10 UTC, satoshiyamaguchi commented
@dgarske I have fixed it. Thank you.

2022-09-20 16:51 UTC, dgarske approved these changes

2022-09-20 20:01 UTC, merged