Add WOLFSSL_ATECC_TFLXTLS for Atmel port
wolfSSL/wolfssl pull request #5573
Opened 2022-09-08 16:50 UTC by embhorn

# Description

- No need to have precise buffer sizes, thus now the code works anyway also with legacy TNGTLS certificates
- Support of custom PKI on TFLXTLS devices; use `WOLFSSL_ATECC_TFLXTLS` for the purpose

Fixes zd14802

# Testing

Customer confirmed

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [X] updated appropriate READMEs
 - [ ] Updated manual and documentation

2022-09-09 06:14 UTC, ronnytittoto reviewed
I confirm these are my proposed changes, I did test them on Microchip SAME54 Curiosity Ultra and on PIC32MZ Curiosity 2.0 along with the modified wolfsll_tcp_client example from Microchip Harmony v3 using MPLABX 6.00 and XC32 compiler v4.10.

2022-09-12 17:47 UTC, embhorn commented
Jenkins, please test this

2022-09-12 17:49 UTC, embhorn commented
@ronnytittoto you have been approved as a contributor!

2022-09-12 18:18 UTC, dgarske requested changes

2022-09-12 18:18 UTC, dgarske commented on wolfcrypt/src/port/atmel/atmel.c
> +ret = tng_atcacert_max_signer_cert_size(&signerCertSize);
Indent is off here.

2022-09-12 18:18 UTC, dgarske commented on wolfcrypt/src/port/atmel/atmel.c
> +       printf("Failed to get max signer cert size\r\n");
All `printf` calls need wrapped with `#ifdef WOLFSSL_ATECC_DEBUG`

2022-09-12 18:18 UTC, dgarske commented on wolfcrypt/src/port/atmel/atmel.c
> +    /*Read TNGTLS signer cert*/
Cleanup `/* ` -> add spaces before and after.

2022-09-12 18:18 UTC, dgarske commented on wolfcrypt/src/port/atmel/atmel.c
> +       printf("Signer TFLXTLS CA cert buffer too small, need to increase at least to %d\r\n", signerCertSize);
Line length issue.

2022-09-12 18:18 UTC, dgarske commented on wolfcrypt/src/port/atmel/atmel.c
> +       SYS_CONSOLE_PRINT("Failed to read TFLXTLS signer public key!\r\n");
Replace `SYS_CONSOLE_PRINT` with printf.

2022-09-12 18:18 UTC, dgarske commented on wolfcrypt/src/port/atmel/atmel.c
> +    memcpy(&certBuffer[deviceCertSize], signerBuffer, signerCertSize);
`XMEMCPY`

2022-09-12 18:19 UTC, dgarske commented
@embhorn please fix these issues (or assign to another wolf engineer to fix). Thanks

2022-09-12 20:40 UTC, dgarske commented on wolfcrypt/src/port/atmel/atmel.c
> +        return ret = status;
This isn't typical coding convention, but it works. Why not just `return (int)status;`?

2022-09-13 15:35 UTC, dgarske requested changes

2022-09-13 15:35 UTC, dgarske commented on wolfcrypt/src/port/atmel/atmel.c
>          ret = atmel_ecc_translate_err(ret);
It looks like places status is returned we should be doing `ret = atmel_ecc_translate_err(status)` or `return atmel_ecc_translate_err(status)`?

2022-09-15 15:26 UTC, dgarske approved these changes

2022-09-15 15:59 UTC, merged