wolfSSL_set1_curves_list(), wolfSSL_CTX_set1_curves_list() improvements.
wolfSSL/wolfssl pull request #5585
Opened 2022-09-12 12:35 UTC by icing

# Description

- Use wolfSSL API wolfSSL_set_groups() and wolfSSL_CTX_set_groups() to configure curves list
- This sets ssl->groups and ctx->groups accordingly and makes TLSX_KEY_SHARE generation respect the selection and precedence.
- Add tests in quic to assert the order of selections.

# Testing

The added tests in the quic unit.tests verify that the selection and precedence is respected this way.

# Checklist

 - [x] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2022-09-12 16:39 UTC, dgarske requested changes

2022-09-12 18:01 UTC, JacobBarthelmeh commented
ok to test

2022-09-12 18:13 UTC, dgarske requested changes

2022-09-12 18:13 UTC, dgarske commented on src/ssl.c
> +    groups = (byte*)XMALLOC(sizeof(int)*WOLFSSL_MAX_GROUP_COUNT,
Case issue here? Should be `int*`. 
```[src/ssl.c:33942:12: error: assignment to ‘int *’ from incompatible pointer type ‘byte *’ {aka ‘unsigned char *’} [-Werror=incompatible-pointer-types]](x-webdoc://EE3ADE7E-6356-4474-89FD-7E103ED25C98/log_content.html#ERROR1)```

2022-09-12 22:40 UTC, SparkiDev approved these changes

2022-09-13 11:08 UTC, icing commented on src/ssl.c
> +    groups = (byte*)XMALLOC(sizeof(int)*WOLFSSL_MAX_GROUP_COUNT,
Fixed.

2022-09-13 11:08 UTC, icing commented
@dgarske I have no insight why the reported failures happened.

2022-09-13 14:38 UTC, dgarske approved these changes

2022-09-13 14:43 UTC, dgarske commented
> @dgarske I have no insight why the reported failures happened.

The failures were on the external.test due to a momentary network outages, so I hit "retry" on them.

2022-09-13 16:35 UTC, JacobBarthelmeh approved these changes

2022-09-13 16:36 UTC, merged