Clean up some FIPS versioning logic in configure.ac and WIN10 user_settings.h.
wolfSSL/wolfssl pull request #5607
Opened 2022-09-19 16:51 UTC by haydenroche5

# Description

configure.ac: Get rid of v5-RC8, v5-RC9, v5-RC10, v5-RC11, v5-ready, and v5-dev. v5-ready is now just ready and v5-dev just dev.
IDE/WIN10/user_settings.h: Make the FIPS blocks define HAVE_FIPS. Change WCv5.0 block to WCv5.0-RC12. Change FIPS Ready block to use HAVE_FIPS_VERSION_MINOR 3 instead of HAVE_FIPS_VERSION_MINOR 2.

# Testing

```
./fips-check.sh linuxv5-ready
./fips-check.sh linuxv5-dev
./fips-check.sh linuxv5
```

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2022-09-19 17:56 UTC, haydenroche5 commented on configure.ac
> +#   v5-ready - Alias for ready. HAVE_FIPS_VERSION = 5,
This is a list of old, retired options, so it wouldn't make sense to change the old name (v5-ready) to the new name (ready).

2022-09-19 18:05 UTC, kaleb-himes commented
@haydenroche5,

The failures are being caused by the `FIPS_OPTION` variables in fips-check.sh. Below is a suggestive patch:

```
diff --git a/fips-check.sh b/fips-check.sh
index f7c76a14f..e48c6115a 100755
--- a/fips-check.sh
+++ b/fips-check.sh
@@ -11,7 +11,7 @@
 #
 #     $ ./fips-check [flavor] [keep]
 #
-#     - flavor: linux (default), ios, android, windows, freertos, linux-ecc, netbsd-selftest, linuxv2, fipsv2-OE-ready, fips-ready, stm32l4-v2, linuxv5, linuxv5-ready, linuxv5-dev
+#     - flavor: linux (default), ios, android, windows, freertos, linux-ecc, netbsd-selftest, linuxv2, fipsv2-OE-ready, fips-ready, stm32l4-v2, linuxv5, ready, dev
 #
 #     - keep: (default off) XXX-fips-test temp dir around for inspection
 #
@@ -37,8 +37,8 @@ Flavor is one of:
     wolfrand
     solaris
     linuxv5 (current FIPS 140-3)
-    linuxv5-ready (ready FIPS 140-3)
-    linuxv5-dev (dev FIPS 140-3)
+    ready (ready FIPS 140-3)
+    dev (dev FIPS 140-3)
 Keep (default off) retains the XXX-fips-test temp dir for inspection.
 
 Example:
@@ -233,28 +233,28 @@ linuxv5)
   RNG_VERSION="WCv5.0-RC12"
   FIPS_SRCS=( fips.c fips_test.c wolfcrypt_first.c wolfcrypt_last.c )
   FIPS_INCS=( fips.h )
-  FIPS_OPTION="v5-RC12"
+  FIPS_OPTION=v5
   COPY_DIRECT=( wolfcrypt/src/aes_asm.S wolfcrypt/src/aes_asm.asm
                 wolfcrypt/src/aes_gcm_asm.S
                 wolfcrypt/src/sha256_asm.S wolfcrypt/src/sha512_asm.S )
   ;;
-linuxv5-ready|fips-ready|fips-v5-ready)
+ready)
   FIPS_REPO="git@github.com:wolfSSL/fips.git"
   FIPS_VERSION="master"
   CRYPT_INC_PATH=wolfssl/wolfcrypt
   CRYPT_SRC_PATH=wolfcrypt/src
   FIPS_SRCS=( fips.c fips_test.c wolfcrypt_first.c wolfcrypt_last.c )
   FIPS_INCS=( fips.h )
-  FIPS_OPTION=v5-ready
+  FIPS_OPTION=ready
   ;;
-linuxv5-dev|fips-dev)
+dev)
   FIPS_REPO="git@github.com:wolfSSL/fips.git"
   FIPS_VERSION="master"
   CRYPT_INC_PATH=wolfssl/wolfcrypt
   CRYPT_SRC_PATH=wolfcrypt/src
   FIPS_SRCS+=( wolfcrypt_first.c wolfcrypt_last.c )
   FIPS_INCS=( fips.h )
-  FIPS_OPTION=v5-dev
+  FIPS_OPTION=dev
   ;;
 
 stm32l4-v2)
 ```

2022-09-19 21:10 UTC, kaleb-himes commented on configure.ac
> +#   v5-ready - Alias for ready. HAVE_FIPS_VERSION = 5,
Ultimately went with the original value `fips-ready`

2022-09-19 22:05 UTC, douzzer requested changes
The incumbent configure.ac logic depends on all v5 variants starting with "v5":
```
# FIPS feature and macro setup
AS_CASE([$FIPS_VERSION],
    [v5*], [ # FIPS 140-3
```
So you'll need to change `[v5*]` to `[v5*|ready|dev]` to make things work right.

As it is, it seems like `ready` and `dev` are working, but really it's not doing a FIPS builds at all:
```
$ ./configure --quiet --enable-fips=ready --disable-jobserver CFLAGS='-DNO_WOLFSSL_CIPHER_SUITE_TEST -pedantic'
$ make -j 24
[...]
wolfcrypt/src/wolfcrypt_last.c:55: error: ISO C forbids an empty translation unit [-Werror=pedantic]
cc1: all warnings being treated as errors
wolfcrypt/src/wolfcrypt_first.c:54: error: ISO C forbids an empty translation unit [-Werror=pedantic]
make[2]: *** [Makefile:5763: wolfcrypt/src/src_libwolfssl_la-wolfcrypt_last.lo] Error 1
```
(`-pedantic` is handy for teasing out things like this.)

2022-09-19 22:37 UTC, douzzer approved these changes
LGTM.  tested with `wolfssl-multi-test.sh ... fips-140-2-optest linuxkm-all-fips-140-3-dev-dyn-hash fips-140-3-optest-acvp-defaults fips-140-3-ready-optest-acvp-sp-asm fips-140-3-dev-optest-acvp-sp-asm`

btw-and-incidentally, note that I had to populate the version map in `wolfssl-multi-test.sh` as follows:
```
FIPS_VERSION_CONFIG_ARG_MAP=(
    [v5-ready]='ready'
    [v5-dev]='dev'
)
```
the map mechanism was preexisting, but wasn't needed until now.  the map works on current `master` too, so I've deployed it for nightlies without delay.

2022-09-20 02:31 UTC, kaleb-himes approved these changes

2022-09-20 02:48 UTC, merged