DTLS 1.2: Reset state when sending HelloVerifyRequest
wolfSSL/wolfssl pull request #5657
Opened 2022-10-04 14:23 UTC by julek-wolfssl

2022-10-05 12:24 UTC, rizlik requested changes
can you add a test?

2022-10-05 13:55 UTC, julek-wolfssl commented on src/dtls.c
> +    ssl->msgsReceived.got_client_hello = 0;
Should only be once.

2022-10-05 13:56 UTC, julek-wolfssl commented on src/internal.c
> +            ssl->msgsReceived.got_client_hello = 0;
I was reading the function wrong. I thought that when `IsEncryptionOn(ssl, 1)` we are returning `sendSz` always. No need for this.

2022-10-05 14:47 UTC, julek-wolfssl commented
Added testing (expanded `test_wolfSSL_dtls_stateless`).

2022-10-05 16:43 UTC, rizlik approved these changes

2022-10-09 16:30 UTC, haydenroche5 approved these changes

2022-10-09 16:31 UTC, merged