adjust saving new OCSP cert
wolfSSL/wolfssl pull request #5708
Opened 2022-10-17 16:02 UTC by JacobBarthelmeh

ZD14840

2022-10-25 17:12 UTC, dgarske approved these changes

2022-10-26 19:47 UTC, haydenroche5 requested changes
Looks good. Just one comment about redundant code.

2022-10-26 19:47 UTC, haydenroche5 commented on src/ocsp.c
> +    XMEMSET(ocspResponse, 0, sizeof(OcspResponse));
InitOcspResponse should do this already, I think:

```
void InitOcspResponse(OcspResponse* resp, OcspEntry* single, CertStatus* status,
                      byte* source, word32 inSz, void* heap)
{
    WOLFSSL_ENTER("InitOcspResponse");

    XMEMSET(status, 0, sizeof(CertStatus));
    XMEMSET(single,  0, sizeof(OcspEntry));
    XMEMSET(resp,   0, sizeof(OcspResponse));
    .
    .
    .
```

2022-10-26 20:09 UTC, haydenroche5 approved these changes

2022-10-26 21:29 UTC, douzzer approved these changes
clean run under `wolfssl-multi-test.sh ... super-quick-check` (includes `clang-tidy`, sanitizers, `cppcheck`).

2022-10-26 22:43 UTC, merged