Improve TLS1.2 client authentication to use TSIP
wolfSSL/wolfssl pull request #5709
Opened 2022-10-18 05:40 UTC by TakayukiMatsuo

# Description

This PR add support client authentication in TLS1.2 with TSIP acceleration. Both client certificates including RSA-2048/ ECC-P256 key can be handled.

# Testing

Tested by running example clients on following Renesas boards:
- RX72N Envision kit
- RSK-RX65N-2MB
- GR-ROSE

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [☑] updated appropriate READMEs
 - [☑] Updated manual and documentation

2022-12-28 18:06 UTC, cconlon requested changes

2023-02-10 22:53 UTC, TakayukiMatsuo commented on wolfcrypt/src/port/Renesas/renesas_common.c
> + * And tries to verify the signature passed to it by decrypting with a public
Rephrased it.

2023-02-10 22:54 UTC, TakayukiMatsuo commented on wolfcrypt/src/port/Renesas/renesas_tsip_util.c
> +                    out[idx++] = ASN_SEQUENCE | ASN_CONSTRUCTED;
The buffer size is checked immediately after the case statement that precedes this statement.

2023-02-10 22:54 UTC, TakayukiMatsuo commented on wolfssl/wolfcrypt/port/Renesas/renesas-tsip-crypt.h
> +}wolfssl_TSIP_KEY_TYPE;
Fixed it as suggested.

2023-02-10 22:54 UTC, TakayukiMatsuo commented on wolfcrypt/src/port/Renesas/renesas_common.c
> +    /* be called for signing
Changed as suggested.

2023-02-10 22:54 UTC, TakayukiMatsuo commented on wolfcrypt/src/port/Renesas/renesas_tsip_util.c
> +            #if !defined(NO_RSA) && defined(USE_CERT_BUFFERS_4096)
Removed USE_CERT_BUFFER_XXX macro guards.

2023-02-10 22:55 UTC, TakayukiMatsuo commented on wolfcrypt/src/port/Renesas/renesas_tsip_util.c
> + *   info->pk.eccsign.outlen: the buffer where the length of signature is out
Reworded the description.

2023-02-10 22:55 UTC, TakayukiMatsuo commented on wolfcrypt/src/port/Renesas/renesas_tsip_util.c
> +/*   perform signing with the client's ECC private key on hash value of messages
Capitalized it.

2023-02-10 22:55 UTC, TakayukiMatsuo commented on wolfcrypt/src/port/Renesas/renesas_tsip_util.c
> +                #if defined(USE_CERT_BUFFERS_4096)
Removed USE_CERT_BUFFER_XXX macro guards.

2023-02-10 22:56 UTC, TakayukiMatsuo commented on wolfcrypt/src/port/Renesas/renesas_tsip_util.c
> + *   info->pk.rsa.outlen: the buffer where the length of signature is out
Reworded the description.

2023-02-10 22:56 UTC, TakayukiMatsuo commented on wolfcrypt/src/port/Renesas/renesas_tsip_util.c
> +/*  perform signing with the client's RSA private key on hash value of messages
Capitalized it.

2023-02-10 22:58 UTC, TakayukiMatsuo commented on wolfcrypt/src/port/Renesas/renesas_tsip_util.c
> +                #if defined(USE_CERT_BUFFERS_1024)
Removed USE_CERT_BUFFER_XXX macro guards.

2023-02-18 00:01 UTC, cconlon approved these changes

2023-02-18 00:02 UTC, merged