Change NID_* from enum to #define
wolfSSL/wolfssl pull request #5720
Opened 2022-10-20 15:10 UTC by julek-wolfssl

2022-10-21 21:12 UTC, haydenroche5 requested changes

2022-10-21 21:12 UTC, haydenroche5 commented on wolfcrypt/src/evp.c
> +            case NULL_CIPHER_TYPE :
Should we gate this on HAVE_NULL_CIPHER?

2022-10-25 11:13 UTC, julek-wolfssl commented on wolfcrypt/src/evp.c
> +    int wolfSSL_EVP_CIPHER_CTX_nid(const WOLFSSL_EVP_CIPHER_CTX *ctx)
Added a small test.

2022-10-25 11:14 UTC, julek-wolfssl commented on wolfcrypt/src/evp.c
> +            WOLFSSL_MSG("Bad parameters");
Fixed.

2022-10-25 11:14 UTC, julek-wolfssl commented on wolfcrypt/src/evp.c
> +            case ARC4_TYPE :
This is how this switch statement is defined in `ssl.c` too.

2022-10-25 11:14 UTC, julek-wolfssl commented on wolfcrypt/src/evp.c
> +                WOLFSSL_MSG("Null cipher has no NID");
Fixed.

2022-10-25 17:34 UTC, haydenroche5 approved these changes

2022-10-25 17:34 UTC, merged