ECC cofactor: fix check scalar bits
wolfSSL/wolfssl pull request #5737
Opened 2022-10-26 06:59 UTC by SparkiDev

# Description

For shared secrets, when a curve has a cofactor, the private key (in range of order) is multiplied by the cofactor before use.

If there is a cofactor involved, check bit size of scalar against modulus instead of order.

Fixes zd#15017

# Testing

Modified test.c to use SECP112R2 instead of SECP112R1.

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2022-10-26 14:51 UTC, dgarske approved these changes

2022-11-03 16:57 UTC, haydenroche5 requested changes

2022-11-03 16:57 UTC, haydenroche5 commented on wolfcrypt/src/ecc.c
> +                #endif /* WOLFSSL_ASYNC_CRYPT_SW */
WOLFSSL_ASYNC_CRYPT_SW -> !WOLFSSL_ASYNC_CRYPT_SW

2022-11-03 17:08 UTC, haydenroche5 approved these changes

2022-11-04 20:31 UTC, merged