Prevent WOLFSSL_NO_MALLOC from breaking RSA certificate verfication
wolfSSL/wolfssl pull request #5739
Opened 2022-10-26 16:18 UTC by anhu

Will  updated manual if this is accepted.

2022-10-26 20:17 UTC, dgarske approved these changes

2022-10-28 15:18 UTC, dgarske requested changes
I think you need to still honor the WOLFSSL_DYN_CERT. It was added specifically for cases with WOLFSSL_NO_MALLOC. See ZD 13952  and https://github.com/wolfSSL/documentation/blob/master/wolfSSL/src/chapter02.md#wolfssl_dyn_cert

2022-10-28 17:49 UTC, dgarske approved these changes

2022-11-02 18:57 UTC, anhu commented
Received confirmation that this fixed the issue for the customer.  (ZD 14992)

@dgarske , please merge at your convenience.

2022-11-03 21:24 UTC, haydenroche5 approved these changes

2022-11-03 21:24 UTC, merged