20221110-wc_DhAgree_Sync-uninited-use
wolfSSL/wolfssl pull request #5791
Opened 2022-11-10 22:49 UTC by douzzer

`wolfcrypt/src/dh.c`: fix benign use of uninited var in `wc_DhAgree_Sync()`, introduced in #5782 -- see oss-fuzz #53177.

tested with `wolfssl-mult-test.sh ... super-quick-check all-clang-sp-all-Os all-sp-all-Os-sanitizer`

2022-11-10 23:01 UTC, dgarske approved these changes

2022-11-10 23:34 UTC, SparkiDev commented on wolfcrypt/src/dh.c
> +        if ((ret == 0) && ((*agreeSz == 0) || ((*agreeSz == 1) && (agree[0] == 1)))) {
Multiple instances of this - 2048,  3072 and 4096.

2022-11-10 23:35 UTC, SparkiDev requested changes

2022-11-10 23:35 UTC, SparkiDev commented on wolfcrypt/src/dh.c
> +        if ((ret == 0) && ((*agreeSz == 0) || ((*agreeSz == 1) && (agree[0] == 1)))) {
Multiple instances of this - 2048, 3072 and 4096.
Change in other places too.

2022-11-11 17:01 UTC, dgarske approved these changes

2022-11-11 17:01 UTC, merged