Add dynamic session cache which allocates sessions from the heap.
wolfSSL/wolfssl pull request #5840
Opened 2022-12-01 23:42 UTC by kareem-wolfssl

# Description

Adds a dynamically allocated session cache.

Fixes zd#14646

# Testing

Built in tests including API test.

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2023-02-13 16:49 UTC, dgarske requested changes

2023-02-13 16:49 UTC, dgarske commented on src/ssl.c
> +#ifdef SESSION_CACHE_DYNAMIC_MEM
Please document the new `SESSION_CACHE_DYNAMIC_MEM` option at top of ssl.c.

2023-02-13 16:49 UTC, dgarske commented on src/ssl.c
> +/* TODO: Add SESSION_CACHE_DYNAMIC_MEM support for PERSIST_SESSION_CACHE.
Consider adding a settings.h rule to not allow `SESSION_CACHE_DYNAMIC_MEM` with `PERSIST_SESSION_CACHE`?
Please add `*` for comment section.

2023-02-13 16:49 UTC, dgarske commented on src/ssl.c
> +                XFREE(&SessionCache[i].Sessions[j], NULL, DYNAMIC_TYPE_SESSION);
Does the `&SessionCache[i].Sessions[j]` need the leading `&`? Is heap hint not available here?

2023-02-13 16:49 UTC, dgarske commented on src/ssl.c
> +    cacheSession = (WOLFSSL_SESSION*) XMALLOC(sizeof(WOLFSSL_SESSION), NULL,
Same, is heap hint available?

2023-02-13 16:49 UTC, dgarske commented on src/ssl.c
> +                            row->Sessions[idx]->timeout) ) {
Move the `{` out of the macro logic.
```
{
    now++;
}
```

2023-02-13 16:49 UTC, dgarske commented on src/ssl.c
> +                    XFREE(cacheSession, NULL, DYNAMIC_TYPE_SESSION);
Heap hint?

2023-02-16 00:43 UTC, kareem-wolfssl commented
Heap hint added, but I had to add it to SessionRow, so SessionCache will have SESSION_ROWS heap hints/pointers.
Not sure if there's a better spot for it, I need a heap hint which is available in wolfSSL_Init/Cleanup.

2023-02-17 17:28 UTC, dgarske commented
Retest this please

2023-02-17 20:16 UTC, dgarske requested changes
Kareem, is it possible to have `make check` work with this enabled?

```
./configure --enable-all --disable-savesession CFLAGS="-DSESSION_CACHE_DYNAMIC_MEM" && make

$ ./tests/unit.test 
starting unit tests...
 Begin API Tests
     1: test_fileAccess                                     : skipped
     2: test_wolfSSL_Init                                   : passed (  0.00015)
     3: test_wolfSSL_Method_Allocators                      : passed (  0.00005)
     4: test_wolfSSL_CTX_new                                : passed (  0.00007)
     5: test_for_double_Free                                : passed (  0.00145)
     6: test_wolfSSL_get_finished                           :Client message: hello wolfssl!
Server response: I hear you fa shizzle!
 passed (  0.02621)
     7: test_wolfSSL_CTX_add_session                        :Client message: hello wolfssl!
Server response: I hear you fa shizzle!
Client message: hello wolfssl!

ERROR - tests/api.c line 7259 failed with:
Server response: I hear you fa shizzle!
    expected: wolfSSL_session_reused(ssl) == 1
    result:   0 != 1
ERROR - tests/api.c line 7259 failed with:
    expected: wolfSSL_session_reused(ssl) == 1
    result:   0 != 1



Aborted (core dumped)
```

2023-02-22 03:24 UTC, dgarske approved these changes

2023-02-22 05:13 UTC, SparkiDev approved these changes

2023-02-22 05:14 UTC, merged