Add docker
wolfSSL/wolfssl pull request #5895
Opened 2022-12-15 17:39 UTC by bandi13

# Description

Adding in some short scripts for the use of a contained environment to build WolfSSL.

2022-12-15 19:12 UTC, tatowicz commented
Thank you for making this! 

Ran into a small issue when testing locally that could use clarification. This is on MAC

```
[+] Building 21.3s (6/6) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                   0.0s
 => => transferring dockerfile: 346B                                                                                                                                   0.0s
 => [internal] load .dockerignore                                                                                                                                      0.0s
 => => transferring context: 2B                                                                                                                                        0.0s
 => [internal] load metadata for docker.io/library/ubuntu:22.04                                                                                                        2.8s
 => [1/3] FROM docker.io/library/ubuntu:22.04@sha256:27cb6e6ccef575a4698b66f5de06c7ecd61589132d5a91d098f7f3f9285415a9                                                  2.3s
 => => resolve docker.io/library/ubuntu:22.04@sha256:27cb6e6ccef575a4698b66f5de06c7ecd61589132d5a91d098f7f3f9285415a9                                                  0.0s
 => => sha256:27cb6e6ccef575a4698b66f5de06c7ecd61589132d5a91d098f7f3f9285415a9 1.42kB / 1.42kB                                                                         0.0s
 => => sha256:e77aa65a8a2bccbc47b96b4256995dd7ff447024ed5319527040f7cc465f6511 529B / 529B                                                                             0.0s
 => => sha256:4c2c87c6c36efcba52fe55e88b05af548de25e295d2ebddf10dacbf605ac78b7 1.48kB / 1.48kB                                                                         0.0s
 => => sha256:10175de2f0c4f7d306f660ee073bce12b824c8012dd19b3c140aae053fabd1cc 28.38MB / 28.38MB                                                                       1.6s
 => => extracting sha256:10175de2f0c4f7d306f660ee073bce12b824c8012dd19b3c140aae053fabd1cc                                                                              0.6s
 => [2/3] RUN DEBIAN_FRONTEND=noninteractive apt update && apt install -y build-essential autoconf libtool                                                            16.0s
 => ERROR [3/3] RUN groupadd -g 20 docker && useradd -ms /bin/bash docker -u 501 -g 20                                                                                 0.2s
------
 > [3/3] RUN groupadd -g 20 docker && useradd -ms /bin/bash docker -u 501 -g 20:
#6 0.146 groupadd: GID '20' already exists
------
executor failed running [/bin/sh -c groupadd -g ${GID} docker && useradd -ms /bin/bash ${USER} -u ${UID} -g ${GID}]: exit code: 4
Exited with error code 1
```

2022-12-16 00:21 UTC, dgarske requested changes
```
$ docker --version
Docker version 20.10.12, build 20.10.12-0ubuntu2~20.04.1
```

```
$ uname -a
Linux pop-os 5.17.5-76051705-generic #202204271406~1653440576~20.04~6277a18-Ubuntu SMP PREEMPT Thu Ma x86_64 x86_64 x86_64 GNU/Linux
```

1) Running it required `sudo`:

```
$ ./run.sh 
Running with ""...
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/build?buildargs=%7B%22GID%22%3A%221000%22%2C%22UID%22%3A%221000%22%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&shmsize=0&t=wolfssl&target=&ulimits=null&version=1": dial unix /var/run/docker.sock: connect: permission denied
Exited with error code 1

2) Requires "builtin" prerequisite to run from `Docker` folder... Can we avoid the use of `builtin`?

```
$ sudo ./run.sh 
[sudo] password for davidgarske: 
Running with ""...
./run.sh: 4: builtin: not found
unable to prepare context: path "/home/davidgarske/GitHub/wolfssl/Docker/Docker" not found
Exited with error code 1
```

3) Error with `useradd` not unique:

```
$ sudo Docker/run.sh 
Running with ""...
Docker/run.sh: 4: builtin: not found
Sending build context to Docker daemon   5.12kB
Step 1/8 : ARG DOCKER_BASE_IMAGE=ubuntu:22.04
Step 2/8 : FROM $DOCKER_BASE_IMAGE
 ---> 6b7dfa7e8fdb
Step 3/8 : RUN DEBIAN_FRONTEND=noninteractive apt update && apt install -y build-essential autoconf libtool
 ---> Using cache
 ---> 18c90475930e
Step 4/8 : ARG USER=docker
 ---> Using cache
 ---> 83c48d71c757
Step 5/8 : ARG UID=1000
 ---> Using cache
 ---> 64a4e44ab871
Step 6/8 : ARG GID=1000
 ---> Using cache
 ---> 0771ec12fb39
Step 7/8 : RUN groupadd -f -g ${GID} docker && useradd -ms /bin/bash ${USER} -u ${UID} -g ${GID}
 ---> Running in c169706b6428
useradd: UID 0 is not unique
The command '/bin/sh -c groupadd -f -g ${GID} docker && useradd -ms /bin/bash ${USER} -u ${UID} -g ${GID}' returned a non-zero code: 4
Exited with error code 4
```

Still not working for me. Can you add some details to the README.md that might help?

2022-12-16 17:37 UTC, dgarske commented
@bandi13 

Fixed the sudo issue by adding myself to the `docker` group (as you suggested). -> `sudo usermod -aG docker $USER` and to avoid logout/login used `newgrp docker`. Please document this in the `README.md`

Next issue is I have symbolic links for the `async.c`. So getting:

```
Successfully tagged wolfssl:latest
./autogen.sh: 51: cannot create ./wolfcrypt/src/async.c: Directory nonexistent
```

```
$ ls -la ../wolfcrypt/src
total 42156
drwxrwxr-x  5 davidgarske davidgarske   20480 Dec 16 09:32 .
drwxrwxr-x  6 davidgarske davidgarske    4096 Feb  4  2021 ..
...
lrwxrwxrwx  1 davidgarske davidgarske      45 Jun  1  2022 async.c -> ../../../wolfAsyncCrypt/wolfcrypt/src/async.c
```

Please review and suggest a solution. Thanks

2022-12-16 20:58 UTC, dgarske approved these changes

2022-12-20 17:37 UTC, tatowicz approved these changes

2022-12-23 01:19 UTC, merged