Fix StartTLS_Init
wolfSSL/wolfssl pull request #5907
Opened 2022-12-17 13:31 UTC by yota22721

Fixed starttlsCmd comparison inside the StartTLS_Init function
I fixed XSTRCMP to XSTRNCMP for comparing STARTTLS commands correctly.

2022-12-18 15:44 UTC, dgarske commented
OK to test

2022-12-18 15:46 UTC, dgarske approved these changes
@yota22721 the changes look fine to convert these strcmp functions to safer strncmp. To be clear the startTLS was working correctly before. The goal here is to avoid the use of strncmp, correct?

2022-12-19 03:33 UTC, yota22721 commented
When using smtp STARTTLS, tmpBuf would be like ```220 smtp.gmail.com ESMTP 13-20020a170902c24d00b00189348ab156sm5773120plg.283 - gsmtp```. tmpBuf won't match with starttlsCmd, so I changed XSTRNCMP at the first commit. Now at https://github.com/wolfSSL/wolfssl/pull/5907/commits/67c6d73a8fa5506970251789c024c19639168be8,  
I added memcpy to avoid the use of strncmp.

2022-12-19 17:12 UTC, dgarske requested changes

2022-12-19 17:12 UTC, dgarske commented on examples/client/client.c
> +    XMEMCPY(buf,tmpBuf,XSTRLEN(starttlsCmd[0]));
Please use spaces after the comma's `, `. Shouldn't the copy include the null terminating character? So use `XSTRLEN() + 1`?

2022-12-19 17:12 UTC, dgarske commented on examples/client/client.c
> +    char buf[4];
Add trailing code comment. `/* 3 digit number plus 1 null char */`

2022-12-19 19:16 UTC, douzzer requested changes

2022-12-20 21:00 UTC, dgarske requested changes

2022-12-20 21:00 UTC, dgarske commented on examples/client/client.c
> +    char buf[3];     /* 3 digit number */
The `buf` should still have a NULL terminator. Please make `buf[4]`. The XMEMCPY needs to be `XSTRLEN()+1`.
Also you still need to add spaces after the comma's `, ` for function arguments.

2022-12-21 17:04 UTC, douzzer requested changes

2022-12-21 17:04 UTC, douzzer commented on examples/client/client.c
> +    XMEMCPY(buf, tmpBuf, XSTRLEN(starttlsCmd[0])+1);
Before each `XMEMCPY()`, you need to check that `XSTRLEN(tmpBuf) >= XSTRLEN(starttlsCmd[the number])+1`, and check that `tmpBuf[XSTRLEN(starttlsCmd[the number]] == ' '` to confirm that the input has a space character where expected.

In the alternative you can skip the extra `buf` and the `XMEMCPY()`s, and use the simpler approach I showed in my earlier comment.

2022-12-23 01:09 UTC, dgarske commented on examples/client/client.c
>      if (!XSTRCMP(tmpBuf, starttlsCmd[0])) {
@yota22721 please use this suggestion from douzzer for the fix. Thanks

2022-12-27 04:47 UTC, douzzer approved these changes
Looks good -- tested (after rebasing) with `wolfssl-multi-test.sh ... super-quick-check`, notably the sanitizers, `cppcheck`, and `clang-tidy`.

2022-12-27 17:22 UTC, dgarske requested changes

2022-12-27 17:22 UTC, dgarske commented on examples/client/client.c
> +    if ((!XSTRNCMP(tmpBuf, starttlsCmd[0], XSTRLEN(starttlsCmd[0])))&&
Please use space before `&&`. See for other two.

2022-12-27 17:25 UTC, dgarske commented
@yota22721 please quash the PR. It won't pass the FIPSv2 test because some of the commits conflict.

2022-12-29 16:21 UTC, dgarske approved these changes

2022-12-29 16:21 UTC, dgarske commented
@yota22721 please update this PR with the steps used to test this change. Thank you

2023-01-03 17:27 UTC, dgarske approved these changes
Thanks Yota.

2023-01-03 17:28 UTC, merged