append git version info during Espressif install
wolfSSL/wolfssl pull request #5955
Opened 2023-01-04 21:42 UTC by gojimmypi

# Description

As noted in https://github.com/wolfSSL/wolfssl/issues/5948#issuecomment-1370526871 there can be several Espressif wolfSSL component installs in multiple directories for various ESP-IDF versions.

As the installation is a file copy process, the GitHub version information is currently lost at install time. The user at runtime only has the `LIBWOLFSSL_VERSION_STRING` and `LIBWOLFSSL_VERSION_HEX` release values available.

This update will add a few `#DEFINE` values to the installed component wolfssl `version.h` file such as:

```
#undef  LIBWOLFSSL_VERSION_GIT_HASH
#define LIBWOLFSSL_VERSION_GIT_HASH adb406e1eebf05e452afca98fa9bf3ccd7abcfca
#undef  LIBWOLFSSL_VERSION_GIT_SHORT_HASH
#define LIBWOLFSSL_VERSION_GIT_SHORT_HASH adb406e1e
#undef  LIBWOLFSSL_VERSION_GIT_HASH_DATE
#define LIBWOLFSSL_VERSION_GIT_HASH_DATE "Sat Jan 5 09:00:00 2013 +0100"
```

The Espressif `./setup.sh` now exists with a value of `0` instead of `1` if all was successful.

Fixes zd# n/a

# Testing

Run the `./setup.sh` for Espressif component install as explained in the [Setup for Linux](https://github.com/wolfSSL/wolfssl/blob/master/IDE/Espressif/ESP-IDF/README.md#setup-for-linux) and observe the update to `version.h` as noted in the output.

The command can also be run manually as desired:

```
./append_wolfssl_git_version.sh
```

resulting in this example output:
```
Adding git version info to file: /mnt/c/SysGCC/esp32/esp-idf/v5.0/components/wolfssl/wolfssl/version.h
Update complete.
```  

Windows install does not yet have this feature at this time. WSL can be used as a substitute. 

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2023-01-10 00:08 UTC, dgarske requested changes
It seems that none of the ESP-IDF stuff gets included with `make dist`?

The include.am only has these three files:

```
EXTRA_DIST+= IDE/Espressif/ESP-IDF/setup_win.bat
EXTRA_DIST+= IDE/Espressif/ESP-IDF/dummy_test_paths.h
EXTRA_DIST+= IDE/Espressif/ESP-IDF/compileAllExamples.sh
```

2023-01-11 20:45 UTC, gojimmypi commented
@dgarske  I've added the Espressif updates to `include.am` to https://github.com/wolfSSL/wolfssl/pull/5956 in [50820b6](https://github.com/wolfSSL/wolfssl/pull/5956/commits/50820b64fba7cf147dfcf4b632c4013c52dde557). 

It seemed more relevant there and as this PR's `append_wolfssl_git_version.sh` is specifically not included in the the dist since there will be no git info to append.

2023-01-13 21:19 UTC, dgarske approved these changes

2023-01-19 20:25 UTC, gojimmypi commented
I've converted this to a draft to consider other options.

2023-01-31 15:20 UTC, bandi13 reviewed
Is this something that might be useful for the entire project not just Espressif?

2023-01-31 18:58 UTC, gojimmypi commented
> Is this something that might be useful for the entire project not just Espressif?

I would definitely like to see version information everywhere. If it were up to me, I'd have date/version info in each source file.

Admittedly this PR _modifying_ source code is a little wonky. 

Thanks @douzzer for the makefile idea as [implemented](https://github.com/gojimmypi/wolfssl/blob/59880d5cc18214011c529ac6657c269f12a4fd67/IDE/Espressif/ESP-IDF/examples/wolfssl_test/main/CMakeLists.txt#L57) for Espressif in https://github.com/wolfSSL/wolfssl/pull/6018

If everyone likes the idea, I'll create a new PR that includes [runtime display](https://github.com/gojimmypi/wolfssl/blob/59880d5cc18214011c529ac6657c269f12a4fd67/IDE/Espressif/ESP-IDF/examples/wolfssl_test/main/main.c#L138) in [version.h](https://github.com/wolfSSL/wolfssl/blob/master/wolfssl/version.h)

2023-02-16 19:49 UTC, gojimmypi commented
As https://github.com/wolfSSL/wolfssl/pull/6018 was merged, I think it is a better idea to have a more soft version detection, something other than _modification of source files_. 

See the `LIBWOLFSSL_SAVE_INFO` [CMake function](https://github.com/wolfSSL/wolfssl/blob/0a6dedab039472c85fe9c0be83f04b84b3b3daa6/IDE/Espressif/ESP-IDF/examples/wolfssl_test/main/CMakeLists.txt#L37) for examples of saving various interesting version attributes at compile time.

Here's an [example](https://github.com/wolfSSL/wolfssl/blob/0a6dedab039472c85fe9c0be83f04b84b3b3daa6/IDE/Espressif/ESP-IDF/examples/wolfssl_test/main/main.c#L141) of displaying those values at runtime in the Espressif embedded environment:

```
#if defined(LIBWOLFSSL_VERSION_GIT_HASH)
    ESP_LOGI(TAG, "LIBWOLFSSL_VERSION_GIT_HASH = %s", LIBWOLFSSL_VERSION_GIT_HASH);
#endif

#if defined(LIBWOLFSSL_VERSION_GIT_SHORT_HASH )
    ESP_LOGI(TAG, "LIBWOLFSSL_VERSION_GIT_SHORT_HASH = %s", LIBWOLFSSL_VERSION_GIT_SHORT_HASH);
#endif

#if defined(LIBWOLFSSL_VERSION_GIT_HASH_DATE)
    ESP_LOGI(TAG, "LIBWOLFSSL_VERSION_GIT_HASH_DATE = %s", LIBWOLFSSL_VERSION_GIT_HASH_DATE);
#endif
```

2023-02-16 19:49 UTC, closed without merging