Check final SHA buffer blocksize
wolfSSL/wolfssl pull request #5998
Opened 2023-01-22 18:51 UTC by gojimmypi

# Description

During the final block processing of the SHA2 hash, there's an `0x80` byte value added to the buffer and the remaining buffer bytes are set to zero. This PR ensures a reasonable `buffLen` is passed for `wc_ShaFinal()`, `Sha256Final()`, and `Sha512Final()`.

If a valid `buffLen`  value is not found, the function will return with `BAD_FUNC_ARG`.

It should be relatively unlikely that the wrong size would be encountered. This check should have relatively small impact. However, if every possible bit of performance is desired, this feature can be disabled with `#define WC_NO_HARDEN`.

The length was problematic while testing a variety of scenarios related to https://github.com/wolfSSL/wolfssl/issues/5948 and https://github.com/wolfSSL/wolfssl/pull/5997, thus this PR was created for a more graceful handling of a bad buffer length.  

Fixes zd# n/a

# Testing

Confirmed [wolfcrypt/test](https://github.com/wolfSSL/wolfssl/tree/master/wolfcrypt/test) completed with success. (In my case on the ESP32, but expected to pass on other platforms as well)

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2023-01-24 14:34 UTC, bandi13 approved these changes

2023-01-24 19:07 UTC, dgarske requested changes

2023-01-24 19:07 UTC, dgarske commented on wolfcrypt/src/sha.c
> +#ifndef WC_NO_HARDEN
Please move all this down to where the `0x80` is set. Use `BUFFER_E` as the failure. Inline with the error check on the update. Please fix other algos to use this too.

```
% git diff
diff --git a/wolfcrypt/src/sha.c b/wolfcrypt/src/sha.c
index bcfd1005d..3037d7cab 100644
--- a/wolfcrypt/src/sha.c
+++ b/wolfcrypt/src/sha.c
@@ -719,8 +719,6 @@ int wc_ShaFinal(wc_Sha* sha, byte* hash)
         return BAD_FUNC_ARG;
     }

-    local = (byte*)sha->buffer;
-
 #ifdef WOLF_CRYPTO_CB
     if (sha->devId != INVALID_DEVID) {
         ret = wc_CryptoCb_ShaHash(sha, NULL, 0, hash);
@@ -737,6 +735,11 @@ int wc_ShaFinal(wc_Sha* sha, byte* hash)
     }
 #endif /* WOLFSSL_ASYNC_CRYPT */

+    if (sha->buffLen > WC_SHA_BLOCK_SIZE - 1) {
+        return BUFFER_E;
+    }
+
+    local = (byte*)sha->buffer;
     local[sha->buffLen++] = 0x80;  /* add 1 */

     /* pad with zeros */
```

2023-01-24 19:07 UTC, dgarske commented on wolfcrypt/src/sha.c
> +#ifndef WC_NO_HARDEN
Just remove the `#ifndef WC_NO_HARDEN`

2023-01-24 22:08 UTC, SparkiDev requested changes
Otherwise fine.

2023-01-24 22:08 UTC, SparkiDev commented on wolfcrypt/src/sha.c
> +        return BAD_FUNC_ARG;
This is an internal error.
It shouldn't happen when the implementation is working appropriately.
The best error code I've found for this kind of issue is BAD_STATE_E.

2024-06-21 07:13 UTC, closed without merging

2024-06-21 07:13 UTC, gojimmypi commented
I'm closing this lingering PR. I'd still like to do this at some point. 

I've added this to my Mothball section in https://github.com/wolfSSL/wolfssl/issues/6234