Fix for calling 'mp_clear(tmp)' without having called 'mp_init(tmp)'
wolfSSL/wolfssl pull request #6072
Opened 2023-02-08 18:09 UTC by bandi13

# Description

Fixes zd#15620

2023-02-08 18:14 UTC, dgarske requested changes

2023-02-08 18:14 UTC, dgarske commented on wolfcrypt/src/dsa.c
> +    if (err == MP_OKAY)
Move `tmp` to the `mp_init_multi` call.

2023-02-08 18:31 UTC, dgarske approved these changes

2023-02-09 00:18 UTC, SparkiDev approved these changes

2023-02-09 00:18 UTC, merged