20230223-refactor-test-c-error-codes
wolfSSL/wolfssl pull request #6135
Opened 2023-02-25 08:39 UTC by douzzer

`wolfcrypt/test/test.{c,h}`: refactor to capture and encode error retvals using `WC_TEST_RET_*()` macros (based on line numbers), and print line and return code in `err_sys()`.

tested with `wolfssl-multi-test.sh ... super-quick-check`

2023-02-27 01:54 UTC, SparkiDev approved these changes

2023-02-27 16:58 UTC, dgarske commented
Can you add code comments for `print_fiducials`?
Can you explain what “fiducials: 7430 22853 33195 45196” means?

Can you describe in a code comment an example failure:
```
SHA      test failed!
 error L=2466 C=2
```

Maybe add a new "test" and build option to show an example for each type of failures?

2023-02-27 16:58 UTC, dgarske requested changes
Can you add code comments for `print_fiducials`?
Can you explain what “fiducials: 7430 22853 33195 45196” means?

Can you describe in a code comment an example failure:
```
SHA      test failed!
 error L=2466 C=2
```

Maybe add a new "test" and build option to show an example for each type of failures?

2023-02-28 16:57 UTC, dgarske approved these changes
Excellent refactor!

Examples of errors:

```
SHA      test failed!
 error L=2510 i=0
 [fiducial line numbers: 7493 22969 33329 45416]
```

```
SHA-512  test failed!
 error L=3029 i=2
 [fiducial line numbers: 7493 22969 33329 45416]
```

2023-02-28 17:27 UTC, dgarske approved these changes

2023-02-28 20:04 UTC, douzzer commented
for posterity, this is the search I used to track down several hidden flubs where internal test routines, returning fully cooked codes, were wrongly reencoded: ```$ pcre2grep --line-number --after-context=5 -e '^ *ret = (?:(?!wc_|wolfSSL_|mp_|0|WC_TEST_RET_ENC|EVP_|Base64_|Base16_|XMEMCMP|ParseCert|\(int\)XFWRITE|randNum).)+$' wolfcrypt/test/test.c | less```
the idea here is to find codepoints where `ret` is set to a value returned by a routine without a recognized library prefix, presumptively an internal routine, keep 5 lines of context afterwards, and then manually scrutinize it in `less` for matches of `WC_TEST_RET_ENC`.

2023-02-28 20:29 UTC, douzzer commented
examples of error reports:

```
AES192   test failed!
 error L=10870 code=-173 (Bad function argument)
 [fiducial line numbers: 7502 22978 33338 45465]
Exiting main with return code: -1
```
above, I tweaked a `wc_AesInit()` call in `aes192_test()` to pass a null `Aes *`.

```
RSA      test failed!
 error L=16029 code=-140 (ASN parsing error, invalid input)
 [fiducial line numbers: 7502 22978 33338 45465]
```
above is a report for an actual bug in master, teased out by `CFLAGS=-DWOLFSSL_TEST_CERT`.

(fix for this is currently in flight.)

```
RSA NOPAD test failed!
 error L=15571 errno=2 (No such file or directory)
 [fiducial line numbers: 7502 22978 33338 45465]
```
above, I tweaked an `XFOPEN()` to fail in `rsa_no_pad_test()`.

```
AES      test failed!
 error L=10343 i=5
 [fiducial line numbers: 7502 22978 33338 45465]
Exiting main with return code: -1
```
above, I corrupted the constant `ctr192Cipher`, and `i=5` records that it was the `XMEMCMP()` in the 6th iteration through the `testVec` that failed.

```
RSA      test failed!
 error L=16516 i=0
 [fiducial line numbers: 7502 22978 33338 45465]
Exiting main with return code: -1
```
here, the line number corresponds to a call to `SaveDerAndPem()` in `rsa_keygen_test()`, and the `i=0` records that it was the `XFOPEN()` that failed.

2023-02-28 21:02 UTC, dgarske approved these changes

2023-02-28 21:02 UTC, merged

2023-02-28 21:48 UTC, gojimmypi commented
The good thing is that this works well on the Espressif ESP32. Very cool feature!

![image](https://user-images.githubusercontent.com/13059545/221987601-da030015-230e-4100-82e3-0fcc179a4556.png)

However there may be a new problem with `wc_export_int` in the master branch, probably unrelated to this PR. It was helpful in generating the above error by commenting out the problem lines:

```
[5/7] Linking CXX executable wolfssl_test.elf
FAILED: wolfssl_test.elf 
cmd.exe /C "cd . && C:\SysGCC\esp32-8.4\tools\xtensa-esp32-elf\esp-2021r2-patch3\xtensa-esp32-elf\bin\xtensa-esp32-elf-g++.exe -mlongcalls -Wno-frame-address -g  @CMakeFiles\wolfssl_test.elf.rsp -o wolfssl_test.elf  && cd ."
c:/sysgcc/esp32-8.4/tools/xtensa-esp32-elf/esp-2021r2-patch3/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: esp-idf/wolfssl/libwolfssl.a(ecc.c.obj):(.literal.wc_ecc_export_ex+0x0): undefined reference to `wc_export_int'
c:/sysgcc/esp32-8.4/tools/xtensa-esp32-elf/esp-2021r2-patch3/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: esp-idf/wolfssl/libwolfssl.a(ecc.c.obj): in function `wc_ecc_export_ex':
C:/temp/wolfssl_dgarske_6123/wolfcrypt/src/ecc.c:10213: undefined reference to `wc_export_int'
c:/sysgcc/esp32-8.4/tools/xtensa-esp32-elf/esp-2021r2-patch3/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:/temp/wolfssl_dgarske_6123/wolfcrypt/src/ecc.c:10225: undefined reference to `wc_export_int'
c:/sysgcc/esp32-8.4/tools/xtensa-esp32-elf/esp-2021r2-patch3/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:/temp/wolfssl_dgarske_6123/wolfcrypt/src/ecc.c:10235: undefined reference to `wc_export_int'
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

I have a bunch of changes in the works and will get this fixed up in my next PR.