Wssl alerts
wolfSSL/wolfssl pull request #6169
Opened 2023-03-07 17:43 UTC by rizlik

# Description

In TLS 1.2, send Alerts whenever an error is encountered in the handshake. Regroup part of the alerts in a single place.

Fixes zd#15674

# Testing

Custom tests were added

2023-03-13 21:17 UTC, SparkiDev requested changes

2023-03-13 21:17 UTC, SparkiDev commented on src/internal.c
> +void MaybeSendAlert(WOLFSSL *ssl, int error)
Rename: SendFatalAlertOnly?

2023-03-14 14:48 UTC, rizlik commented
removed test on missing cipher spec.
If an end doesn't receive the cipher spec then it will interpret the following encrypted message as non-encrypted (basically random data). While it will result in an alert most of the time it can't be ruled out that the message may don't produce an alert right away. Eg: can have a valid handshake header with a length larger than the message payload, in this case the peer will just wait for other data on the wire. Another (remote) possibility is that the message is a valid alert message, in this case the connection is closed but no alert is sent.

2023-03-14 21:31 UTC, SparkiDev approved these changes

2023-03-14 21:48 UTC, merged