Nuttx hw acel
wolfSSL/wolfssl pull request #6289
Opened 2023-04-11 18:08 UTC by jpbland1

# Description

Add `__HAL_RCC_CRYP_CLK_ENABLE` and `__HAL_RCC_CRYP_CLK_DISABLE` calls to the wolfcrypt benchmark so it can use the hardware acceleration on stm32 platforms.

# Testing

Ran the benchmark on the NUCLEO-H753ZI board

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2023-04-11 18:51 UTC, dgarske requested changes

2023-04-11 18:51 UTC, dgarske commented on wolfcrypt/benchmark/benchmark.c
> +    __HAL_RCC_CRYP_CLK_ENABLE();
What about having this in stm32.c in `wc_Stm32_Aes_Init` wrapped with a macro that is off by default? If you need add a `wc_Stm32_Aes_Cleanup`.

2023-06-27 21:17 UTC, jpbland1 commented
rebased and force pushed again

2023-06-27 21:21 UTC, dgarske approved these changes
Looks good. Please confirm with customer and document `STM32_HW_CLOCK_AUTO` somewhere (like the PR description).

2023-06-28 16:32 UTC, merged