dtls13: support Authentication and Integrity-Only Cipher Suites
wolfSSL/wolfssl pull request #6298
Opened 2023-04-13 10:05 UTC by rizlik

# Description

Support Authentication and Integrity-Only Cipher Suites (TLS13-SHA256-SHA256 and TLS13-SHA384-SHA384) in DTLSv1.3 (see RFC 9150)

# Testing
A new test was added, also it can be tested using `-v4 -u -l TLS13-SHA256-SHA256` options for `./examples/server/server` and `./examples/client/client`

2023-04-18 21:10 UTC, julek-wolfssl requested changes
I like the testing you set up. Please also add the ciphers to `tests/test-dtls13.conf` like in `tests/test-tls13.conf`.

2023-05-18 13:24 UTC, julek-wolfssl requested changes

2023-05-18 13:24 UTC, julek-wolfssl commented on tests/test-dtls13.conf
> +# server TLSv1.3 Integrity-only SHA256
`TLSv1.3` -> `DTLSv1.3`
Same in all other occurrences in this file.

2023-05-18 13:24 UTC, julek-wolfssl commented on tests/api.c
> +    for (i = 0; i < buf_size; i++) {
If you do `i < buf_size - string_size - 1` you can skip the size check inside the loop.

2023-05-18 13:24 UTC, julek-wolfssl commented on tests/api.c
> +            continue;
Skip this. `XSTRCMP` already takes care of this.

2023-05-19 08:37 UTC, julek-wolfssl approved these changes

2023-05-19 08:37 UTC, julek-wolfssl commented on tests/api.c
> +    test_str_size = XSTRLEN("test") + 1;
You could just use `sizeof("test")` but this is not important for testing code.

2023-05-19 16:13 UTC, JacobBarthelmeh approved these changes

2023-05-19 16:13 UTC, merged