Update Japanese comments
wolfSSL/wolfssl pull request #6304
Opened 2023-04-16 23:00 UTC by TakayukiMatsuo

# Description

This PR is to update Japanese comments correspond to following PRs: 
- #6129 "Ed25519 doxygen update"
- #6192 "Document use of wc_AesFree"
- #6263 "Add missing semicolon"
- #6273 "Documentation fixup for wolfSSL__get_chain_cert()"

# Checklist

 - [ ] added tests
 - [* ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2023-04-23 23:56 UTC, TakayukiMatsuo commented
Jenkins retest this please

2023-04-27 07:23 UTC, miyazakh requested changes

2023-04-27 08:55 UTC, TakayukiMatsuo commented on doc/dox_comments/header_files-ja/ssl.h
>      \brief  この関数は、証明書のチェーンからのピアのwolfssl_x509_209_Certificateをインデックス（IDX）で取得します。
WOLFSSL_X509構造体が正しいしいようです。変更しておきました。

2023-04-27 22:03 UTC, miyazakh approved these changes

2023-04-27 22:06 UTC, merged