Add in creator of DEB packages
wolfSSL/wolfssl pull request #6344
Opened 2023-04-26 17:18 UTC by bandi13

Adding in a scripted way to quickly build DEB packages of wolfSSL.

2023-05-01 16:06 UTC, JacobBarthelmeh commented
I think this should go in our scripts directory (maybe under wolfARC for release bundle generation).

2023-05-01 18:10 UTC, bandi13 commented
> I think this should go in our scripts directory (maybe under wolfARC for release bundle generation).

The objective here is to have this as a public facing thing. It is for resolving issues like https://wolfssl.zendesk.com/agent/tickets/16050.

2023-06-27 20:34 UTC, dgarske requested changes

2023-06-27 20:34 UTC, dgarske commented on Docker/deb_packager/createPackage.sh
> +cd ..
```[check-source-text] [3 of 29] [e36ceb5cb3]
weird control chars, hard tabs, CRs, trailing whitespace:
./Docker/deb_packager/createPackage.sh:12:cd ..
```

2025-01-24 22:19 UTC, JacobBarthelmeh commented
Moved to here https://github.com/wolfSSL/scripts/pull/462

2025-01-24 22:19 UTC, closed without merging