DTLS v1.3: fix epoch 0 check on plaintext message
wolfSSL/wolfssl pull request #6392
Opened 2023-05-09 13:47 UTC by rizlik

# Description

Fix a wrong check that allows client hello with epoch != 0 to get parsed. 

# Testing

A new test is added in the PR
Also, to test DLTSv1.2 downgrade:
```
./configure --enable-dtls --enable-dtls13 --enable-secure-renegotiation 
./example/server/server -vd -u -M -r
./example/client/client -v3 -u -R -r
```

2023-05-09 22:06 UTC, dgarske commented
Retest this please

2023-05-10 11:07 UTC, julek-wolfssl requested changes
Nice job finding the fix. I really like the testing you added.

2023-05-10 11:07 UTC, julek-wolfssl commented on tests/api.c
> +    /* disable hrr cookie so we can later check msgsReceivece.got_client_hello
`msgsReceivece` -> `msgsReceived`

2023-05-10 11:07 UTC, julek-wolfssl commented on tests/api.c
> +
Add a call to `test_memio_do_handshake` to make sure that we can recover from this.

2023-05-10 16:40 UTC, rizlik commented
Jenkins retest this please

2023-05-11 12:24 UTC, julek-wolfssl approved these changes

2023-05-12 20:01 UTC, JacobBarthelmeh commented
Retest this please Jenkins. I noticed it has only 22 successful checks listed which is less than usual.

2023-05-16 16:07 UTC, merged