Dsa sha256
wolfSSL/wolfssl pull request #6428
Opened 2023-05-19 21:31 UTC by jpbland1

# Description

Dsa was using sha1, updated to use sha256 and added _ex function to change digest size if needed

Fixes zd# 16177

# Testing

Make test

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2023-05-19 21:33 UTC, jpbland1 commented
is there something wrong with my setup? I've pulled but I'm still getting all these merge master commits

2023-05-19 21:59 UTC, dgarske commented
> is there something wrong with my setup? I've pulled but I'm still getting all these merge master commits

You need to update your local master you are branching from. And don’t use merges use rebase

2023-05-23 01:50 UTC, jpbland1 commented on wolfcrypt/src/asn.c
> +                    ret = wc_DsaVerify_ex(sigCtx->digest, WC_SHA_DIGEST_SIZE,
Something is not right with `ConfirmSignature` I had to change this to `WC_SHA_DIGEST_SIZE` despite the test csr hashing the signature with sha256 and setting the digestSz to 32. I'm not sure if this is a part of CSR logic that I don't understand but it doesn't pass when I try to use the full 32 bytes

2023-05-23 20:29 UTC, dgarske requested changes

2023-05-23 20:29 UTC, dgarske commented on src/pk.c
> +    if (!digest || !dsa || inLen != WC_SHA256_DIGEST_SIZE) {
Won't this break backwards compatibly for anyone using DSA with SHA-1? Should there be a way to use either?

2023-05-25 16:49 UTC, closed without merging