Miscellaneous fixes for sanitizer
wolfSSL/wolfssl pull request #6436
Opened 2023-05-23 19:58 UTC by lealem47

# Description

Please describe the scope of the fix or feature addition.

Fixes zd#

# Testing

How did you test?

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2023-05-23 20:33 UTC, dgarske approved these changes
These all make sense. The HMAC expand performance implication is justifiable. Please assign to Sean for final review when ready.

2023-06-05 22:39 UTC, SparkiDev requested changes

2023-06-05 22:39 UTC, SparkiDev commented on wolfcrypt/src/sp_int.c
> +            for (j = SP_WORD_SIZE - 8; j >= 0 && i>=0; j -= 8) {
space around operator with new condition.

2023-06-05 22:54 UTC, SparkiDev approved these changes

2023-06-06 01:55 UTC, merged