added test case for wolfSSL_configure_args
wolfSSL/wolfssl pull request #6444
Opened 2023-05-24 23:35 UTC by night1rider

Made a simple unit test case for wolfSSL_configure_args that is found in the wolfcrypt/src/logging.c

Using this as an on-boarding process for wolfSSL's GitHub approval process

2023-05-26 15:06 UTC, cconlon commented
Retest this please Jenkins

2023-05-26 20:32 UTC, cconlon requested changes

2023-05-26 20:32 UTC, cconlon commented on tests/api.c
> +#if (defined(LIBWOLFSSL_CONFIGURE_ARGS) && defined(HAVE_WC_INTROSPECTION))
We can skip the outer set of parenthesis here, so just having:

```
#if defined(LIBWOLFSSL_CONFIGURE_ARGS) && defined(HAVE_WC_INTROSPECTION)
```

2023-05-30 14:52 UTC, night1rider commented
Retest this please Jenkins

2023-05-30 19:02 UTC, cconlon approved these changes

2023-05-30 19:03 UTC, merged