Allow option to create SSL without key/cert in ctx
wolfSSL/wolfssl pull request #6455
Opened 2023-05-30 17:38 UTC by lealem47

# Description

Allow build option to create SSL without key/cert in ctx

Fixes zd#zd168

# Testing

Removed calls to load key/cert into the ctx object in https://github.com/wolfSSL/wolfssl-examples/blob/master/tls/server-tls.c and added calls to by load the key/cert into the ssl object.

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2023-05-30 19:43 UTC, bandi13 commented
Jenkins retest this please

2023-06-23 18:48 UTC, dgarske requested changes

2023-06-29 19:59 UTC, lealem47 commented on src/internal.c
> +#ifdef INIT_SSL_NO_CTX_KEY
Renamed and added documentation

2023-06-29 20:27 UTC, dgarske approved these changes

2023-06-30 16:14 UTC, lealem47 commented
Retest this please

2023-06-30 17:35 UTC, merged