add sanity check on hash size with STM32 port
wolfSSL/wolfssl pull request #6477
Opened 2023-06-05 20:52 UTC by JacobBarthelmeh

ZD16261

2023-06-06 22:43 UTC, JacobBarthelmeh commented
retest this please Jenkins

2023-06-07 23:47 UTC, SparkiDev requested changes
Do you need to handle P521?
If so, then you need to shift right at the bit level.

2023-06-08 12:21 UTC, SparkiDev approved these changes

2023-06-08 12:21 UTC, merged

2023-06-08 21:23 UTC, JacobBarthelmeh commented
@SparkiDev Good catch, I agree that P521 and other curve sizes that do not fit nicely will need addressed. Lets add a follow up code change.