Test api.c: change more tests to use Expect instead of Assert
wolfSSL/wolfssl pull request #6500
Opened 2023-06-13 06:40 UTC by SparkiDev

# Description

Changed EXPECT_DECL to start of as TEST_SKIPPED.
Modified other EXPECT macros appropriately.
Change test functions to not use 'res' when EXPECT_DECL is used.

memory.c:
  wc_MemFailCount_Init(): don't declare variable after a statement

conf.c:
wolfSSL_TXT_DB_read(): free the whole WOLFSSL_TXT_DB on failure instead of just the memory
wolfSSL_CONF_add_string(): pop the value added into section->value (sk) if it can't be pushed onto conf->data
  wolfSSL_NCONF_load(): free the new value if it wasn't able to be added

ocsp.c:
  wolfSSL_OCSP_cert_to_id():
free the decoded certificate if parsing failed (is freed after use otherwise)
free the certificate id on failure and make it NULL and continue freeing other variables

pk.c:
wolfSSL_RSA_set0_crt_params(): set dmp1, dmq1 and iqmp fields to NULL if setting the internal failed - returns error and caller needs to free the passed in BNs
wolfSSL_RSA_set0_factors(): set p and q fields to NULL if setting the internal failed - returns error and caller needs to free the passed in BNs
wolfSSL_RSA_set0_key(): set n, e abd d fields to NULL if setting the internal failed - returns error and caller needs to free the passed in BNs

x509.c:
wolfSSL_X509_set_serialNumber(): explicit NULL
checkwolfSSL_X509_REQ_add1_attr_by_NID(): check whether push succeeded and on failure free attribute

asn.c:
ConfirmSignature(): for DSA, allocate separately to ensure no leak on memory allocation failure.

dh.c:
wc_DhGenerateParams(): ensure tmp and tmp2 are able to be cleared on error

evp.c:
wolfSSL_EVP_PKEY_CTX_add1_hkdf_info(): fix realloc use to no leak on failure
  wolfSSL_EVP_CIPHER_CTX_iv_length(): handle ctx being NULL.

# Testing

Memory allocation failure testing as well.

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2023-06-13 13:13 UTC, SparkiDev commented
retest this please

2023-06-21 21:44 UTC, dgarske requested changes
```tests/api.c: In function ‘test_wolfSSL_i2d_DHparams’:
./wolfssl/wolfcrypt/wc_port.h:664:24: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
  664 |     #define XFILE      FILE*
      |                        ^~~~
tests/api.c:59106:5: note: in expansion of macro ‘XFILE’
59106 |     XFILE f = XBADFILE;
      |     ^~~~~
cc1: all warnings being treated as errors```

2023-06-21 23:30 UTC, SparkiDev commented
fixed

2023-06-22 00:17 UTC, dgarske approved these changes

2023-06-22 00:17 UTC, merged