fix pthread macro protection in tls_bench
wolfSSL/wolfssl pull request #6545
Opened 2023-06-26 19:57 UTC by bigbrett

Fixes unprotected access to a variable who's definition is guarded by `HAVE_PTHREAD` 

If you build the benchmark program (`tls_bench.c`) on a platform that **doesn't define** `HAVE_PTHREAD` in addition to **not defining** both `NO_WOLFSSL_SERVER` and `NO_WOLFSSL_CLIENT`, then you will get a compiler error when accessing `info->serverListening`, as the definition is protected by `HAVE_PTHREAD`.

I don't think this is a valid use case (we clearly don't test for it in CI if it hasn't been caught yet) but the guarding is still wrong and should be fixed as the compiler error can be hit when building with user_settings.h if you don't know which macros you need to define, and you wouldn't actually know what the problem was until you dug through the source. 

I also added add a compile time validity check banning the configuration - please let me know if we actually do want to allow this configuration through.

2023-06-26 20:03 UTC, bigbrett commented
Also, I noticed the following in some of the macro checks at the top of the file:
```
/* PTHREAD requires server and client enabled */
#if defined(NO_WOLFSSL_CLIENT) || defined(NO_WOLFSSL_SERVER)
    #if defined(HAVE_PTHREAD)
        #ifdef __GNUC__  /* GCC compiler */
            #pragma message "PTHREAD requires server and client enabled."
        #elif defined(_MSC_VER) /* Microsoft Visual C++ compiler */
            #pragma message("PTHREAD requires server and client enabled.")
        #else
            #warning "PTHREAD requires server and client enabled."
        #endif
        #undef HAVE_PTHREAD
    #endif
#endif
```
If we detect a bad configuration, is the appropriate course of action really just to warn and then undefine `HAVE_PTHREAD`? This should probably be a compilation-stopping error, no? 

`HAVE_PTHREADS` should be defined by the user (or by configure.ac) to reflect the system, and so should never be conditionally manipulated by the source code itself...

I can make these changes in a subsequent commit if the reviewer agrees

2023-06-26 20:15 UTC, dgarske commented
> Also, I noticed the following in some of the macro checks at the top of the file:
> 
> ```
> /* PTHREAD requires server and client enabled */
> #if defined(NO_WOLFSSL_CLIENT) || defined(NO_WOLFSSL_SERVER)
>     #if defined(HAVE_PTHREAD)
>         #ifdef __GNUC__  /* GCC compiler */
>             #pragma message "PTHREAD requires server and client enabled."
>         #elif defined(_MSC_VER) /* Microsoft Visual C++ compiler */
>             #pragma message("PTHREAD requires server and client enabled.")
>         #else
>             #warning "PTHREAD requires server and client enabled."
>         #endif
>         #undef HAVE_PTHREAD
>     #endif
> #endif
> ```
> 
> If we detect a bad configuration, is the appropriate course of action really just to warn and then undefine `HAVE_PTHREAD`? This should probably be a compilation-stopping error, no?
> 
> `HAVE_PTHREADS` should be defined by the user (or by configure.ac) to reflect the system, and so I would think it should never be conditionally manipulated by the source code itself...
> 
> I can make these changes in a subsequent commit if the reviewer agrees

The tls_bench supports a way to run without threading. No error required.

2023-06-26 20:15 UTC, dgarske commented
> Also, I noticed the following in some of the macro checks at the top of the file:
> 
> ```
> /* PTHREAD requires server and client enabled */
> #if defined(NO_WOLFSSL_CLIENT) || defined(NO_WOLFSSL_SERVER)
>     #if defined(HAVE_PTHREAD)
>         #ifdef __GNUC__  /* GCC compiler */
>             #pragma message "PTHREAD requires server and client enabled."
>         #elif defined(_MSC_VER) /* Microsoft Visual C++ compiler */
>             #pragma message("PTHREAD requires server and client enabled.")
>         #else
>             #warning "PTHREAD requires server and client enabled."
>         #endif
>         #undef HAVE_PTHREAD
>     #endif
> #endif
> ```
> 
> If we detect a bad configuration, is the appropriate course of action really just to warn and then undefine `HAVE_PTHREAD`? This should probably be a compilation-stopping error, no?
> 
> `HAVE_PTHREADS` should be defined by the user (or by configure.ac) to reflect the system, and so I would think it should never be conditionally manipulated by the source code itself...
> 
> I can make these changes in a subsequent commit if the reviewer agrees

The tls_bench supports a way to run without threading. No error required.

2023-06-27 20:24 UTC, dgarske requested changes

2023-06-27 20:24 UTC, dgarske commented on examples/benchmark/tls_bench.c
> +    #error "pthreads must be enabled if building benchmark suite to run both client and server. Please define HAVE_PTHREAD if your platform supports it."
Line length (max 80)... Use `\` to separate lines.

2023-06-28 16:53 UTC, bigbrett commented
> The tls_bench supports a way to run without threading. No error required.

Ah, are you saying that the check I put in (below) is actually guarding against a valid configuration and we shouldn't error?
```
#if !defined(NO_WOLFSSL_SERVER) && !defined(NO_WOLFSSL_CLIENT) && !defined(HAVE_PTHREAD)
```

2023-06-28 16:58 UTC, dgarske commented
> 

That looks like a valid check. If both server and client are disable and also pthread then this file should not be built. There should also be a check for WOLFCRYPT_ONLY. I suspect this file is already properly macro guarded.

2023-07-13 21:10 UTC, dgarske approved these changes

2023-07-14 20:13 UTC, JacobBarthelmeh approved these changes

2023-07-14 20:14 UTC, merged