add HW error codes to tfm.h, sp_int.h, integer.h
wolfSSL/wolfssl pull request #6565
Opened 2023-06-30 21:40 UTC by gojimmypi

# Description

Adds new hardware-acceleration-specific return error code definitions to math library header files.

Also makes return codes consistent between `tfm.h`, `sp_int.h`, and `integer.h`.

The intention is to allow better visibility to math errors with hardware acceleration. This change will also allow the ability to fall back to SW if hardware fails, is busy, etc.

These changes are needed for my current WIP for Espressif HW acceleration.

Fixes zd#  n/a

# Testing

How did you test?

ran wolfcrypt benchmark and test apps.

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2023-07-03 17:45 UTC, dgarske requested changes
Why are we adding return codes that are not used anywhere? Why not use the error codes / values from error-crypt.h?

2023-07-03 17:59 UTC, gojimmypi commented
> Why are we adding return codes that are not used anywhere? 

This is in prep for my upcoming Espressif hardware acceleration changes, PR soon. The new error codes will allow a [graceful fallback to software math](https://github.com/gojimmypi/wolfssl/blob/040c5c52835e7ef3cbf121306f40863434c34f54/wolfcrypt/src/tfm.c#L3174).

> Why not use the error codes / values from error-crypt.h?

I had considered that, but I thought other platforms that might use hardware acceleration would also use these same error codes, instead of having something specific to each platform. This would allow propagation of math errors to higher levels for improved visibility as to root causes of problems.

For example: I ended up working on the math acceleration only because some corner cases in the math acceleration did not work properly. The original symptom was an RSA padding error. It would have been tremendously helpful if the RSA error actually indicated there was an underlying math problem.

2023-07-10 20:35 UTC, dgarske requested changes
Please include this change with the PR that will actually use these. My preference is to use error-crypt values, not these math values.

2023-07-10 22:06 UTC, gojimmypi commented
ok. that's why this was in a separate PR: so that we could discuss issues in advance and without cluttering the big PR.

I'll renumber the exit code values to include in `esp32-crypt.h`, perhaps offset by 100 to ensure no future collisions with SP exit values:

```
#define MP_HW_ERROR    (-106) /* hardware error, consider SW fallback  */
#define MP_HW_BUSY     (-107) /* assigned -7 to match SP_HW_BUSY       */
#define MP_HW_FALLBACK (-108) /* signal to caller to fall back to SW   */
#define MP_HW_VALIDATION_ACTIVE (-109) /* optional HW validation active */
```

What do you think of the other consistency changes? (i.e. all the lines without "HW")

2023-07-10 22:16 UTC, dgarske commented
> ok. that's why this was in a separate PR: so that we could discuss issues in advance and without cluttering the big PR.
> 
> I'll renumber the exit code values to include in `esp32-crypt.h`, perhaps offset by 100 to ensure no future collisions with SP exit values:
> 
> ```
> #define MP_HW_ERROR    (-106) /* hardware error, consider SW fallback  */
> #define MP_HW_BUSY     (-107) /* assigned -7 to match SP_HW_BUSY       */
> #define MP_HW_FALLBACK (-108) /* signal to caller to fall back to SW   */
> #define MP_HW_VALIDATION_ACTIVE (-109) /* optional HW validation active */
> ```
> 
> What do you think of the other consistency changes? (i.e. all the lines without "HW")

Why can't you just extend and use the existing wolfCrypt error codes in error-crypt.h and error.c?

2023-07-10 22:47 UTC, gojimmypi commented
> Why can't you just extend and use the existing wolfCrypt error codes in error-crypt.h and error.c?

Yes, I will ([already did](https://github.com/gojimmypi/wolfssl/commit/73d447d1d03811eaac5998ded634db5a1a76c1f2)), good suggestion about `errors.c`.  I'll append to the end and adjust `WC_LAST_E` and `MIN_CODE_E`.

What I am referring to is the _other_ changes:

Missing from `sp_int.h`: `#define MP_ERROR (-1)` and `#define MP_WOULDBLOCK (-4)` and `#define MP_SIZE SP_INT_DIGITS`

Missing from `tfm.h`:  `#define MP_SIZE (FP_MAX_SIZE/DIGIT_BIT) /* for compatibility with SP_INT */`

But I suppose since they are not being used... perhaps not important. I just thought it would be good to be consistent.

2023-07-11 00:11 UTC, gojimmypi commented
On the topic of error codes: although I was able to successfully add [new values](https://github.com/gojimmypi/wolfssl/blob/70e98439d16ce7912a23d08123e05b7227dafef2/wolfssl/wolfcrypt/error-crypt.h#L266) to `error.c` that works with wolfcrypt test, this modification fails with the benchmark due to a conflict with a [separate set of error codes](https://github.com/wolfSSL/wolfssl/blob/f26b8bdf6213139946b5fa9104abc7781b68528b/wolfssl/error-ssl.h#L34) referenced in [ssl.c](https://github.com/wolfSSL/wolfssl/blob/f26b8bdf6213139946b5fa9104abc7781b68528b/src/ssl.c#L21863).

Specifically the [wolfssl/openssl/ssl.h](https://github.com/wolfSSL/wolfssl/blob/f26b8bdf6213139946b5fa9104abc7781b68528b/wolfssl/openssl/ssl.h#L1472) does this:

```
#define PEM_R_BAD_PASSWORD_READ         (-MIN_CODE_E + 3)
```

As `MIN_CODE_E` has a new value of `-303`, making it positive and adding `3` ends causing the OpenSSL values to conflict with the [wolfssl/error-ssl.h values](https://github.com/wolfSSL/wolfssl/blob/f26b8bdf6213139946b5fa9104abc7781b68528b/wolfssl/error-ssl.h#L34).

and we end up with `duplicate case value` error:

```
C:/workspace/wolfssl-gojimmypi/src/ssl.c: In function 'wolfSSL_ERR_GET_LIB':
C:/workspace/wolfssl-gojimmypi/src/ssl.c:21868:5: error: duplicate case value
21868 |     case PEM_R_BAD_PASSWORD_READ:
      |     ^~~~
C:/workspace/wolfssl-gojimmypi/src/ssl.c:21863:5: note: previously used here
21863 |     case -SSL_R_HTTP_REQUEST:
      |     ^~~~
```

I'd rather not fudge the new hardware codes with misleading and unintuitive approximate matches to existing codes. But it looks like there's no practical room for new error codes in `error-crypt.h`.

What do you prefer that I do here?

2023-08-31 16:43 UTC, JacobBarthelmeh requested changes
Would like to see the new error additions get put in error.c but understand why its being added here

2023-08-31 16:43 UTC, JacobBarthelmeh commented on wolfssl/wolfcrypt/sp_int.h
> +#define MP_HW_ERROR     (-6)
Lets use the existing WC_HW_E

2023-08-31 16:43 UTC, JacobBarthelmeh commented on wolfssl/wolfcrypt/sp_int.h
> +#define MP_HW_BUSY      (-7)
Lets use the existing WC_HW_WAIT_E

2023-08-31 16:43 UTC, JacobBarthelmeh commented on wolfssl/wolfcrypt/sp_int.h
> +#define MP_HW_FALLBACK  (-8)
Can NOT_COMPILED_IN or BAD_STATE_E be used instead?

2023-08-31 16:43 UTC, JacobBarthelmeh commented on wolfssl/wolfcrypt/sp_int.h
> +#define MP_HW_ERROR     (-6)
Debug logs with WOLFSSL_MSG could be used to narrow down location of hardware error and distinguish between math hardware acceleration and others if wanted.

2024-06-18 17:42 UTC, gojimmypi commented
Closing this lingering draft PR, as I believe this issue has been resolved in other PRs.

2024-06-18 17:42 UTC, closed without merging