New and updated VisualGDB Project and solution files
wolfSSL/wolfssl pull request #6609
Opened 2023-07-13 15:39 UTC by gojimmypi

# Description

This is a no-code-change update that only adds VisualGDB project and solution files to the test and benchmark Espressif examples.

Fixes zd# n/a

# Testing

How did you test? n/a

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2023-07-13 16:59 UTC, gojimmypi commented
The failing PRB is not likely related to this PR.

2023-07-13 21:14 UTC, dgarske requested changes
"+1,492 −28" -> My preference is for these to be in wolfssl-examples. The VisualGDB creates a lot of cruft for something very few people use. You are welcome to dispute my remark.

2023-07-14 00:22 UTC, gojimmypi commented
> "+1,492 −28" -> My preference is for these to be in wolfssl-examples. The VisualGDB creates a lot of cruft for something very few people use. You are welcome to dispute my remark.

Well, since you left the door open to discussion... :)

I certainly agree that there are more project files than desired. I reached out to the Sysprogs folks regarding the [difficulties changing targets](https://sysprogs.com/w/forums/topic/difficulties-switching-espressif-esp-idf-version-or-chipset/#post-34130). As of now [it is a known problem with no easy resolution](https://sysprogs.com/w/forums/topic/difficulties-switching-espressif-esp-idf-version-or-chipset/#post-34131).

My objective here is to make things as easy for the new user as possible. Having the project files for the different chipssets that are _just ready to go_ is extremely convenient. Very little instruction is needed. This is much more likely to give a positive first impression.

I fully understand that development in [Visual Studio with VisualGDB](https://visualgdb.com/) for embedded targets does not have as big of an audience as it could have. I'm trying to grow that audience. I want to show all those Windows developers that they can easily get into the embedded world using familiar tools. I happen to be working on Espressif chipsets, but [VisualGDB supports over 1000 devices](https://visualgdb.com/?features=embedded) in a single IDE.

I plan to feature VisualGDB in my upcoming webinar. It is an incredibly productive tool. 

To put the [wolfssl Espressif example](https://github.com/wolfSSL/wolfssl/tree/master/IDE/Espressif/ESP-IDF/examples) project and solution files in the separate [wolfssl-examples](https://github.com/wolfSSL/wolfssl-examples/tree/master/ESP32) would be awkward and cumbersome. I suppose we could _duplicate_ the TLS client/server, test, and benchmark apps there... but having duplicate code and keeping them in sync is not very desirable.

I suppose we could cut the file count in half by omitting the solution `.sln` files, and perhaps even only include the most recent ESP-IDF versions. However it is nice to have the pre-defined `Solution Items` file shortcuts available for quick reference:

![image](https://github.com/wolfSSL/wolfssl/assets/13059545/f1a26a5b-8700-4ed3-b2e6-7c687197350b)

I could update the respective `README.md` files to inform the end users of the key files that may be of interest to add to the solution, such as the wolfssl `user_settings.h` if you'd be willing to have all the project files, but no solution files.

It's certainly _possible_ to have just one project file per example (total)... but the instructions would need to be considerably longer.

Keep in mind I plan to also [propose to] add project files to the TLS client & server Espressif examples as well.

Given this information, please let me know what you prefer.

2023-09-18 18:28 UTC, dgarske approved these changes

2024-06-18 17:45 UTC, gojimmypi commented
Closing this lingering PR as the project files are typically updated with each example.

2024-06-18 17:45 UTC, closed without merging