Apple "universal binary framework" build script and project example
wolfSSL/wolfssl pull request #6610
Opened 2023-07-13 17:47 UTC by bigbrett

# Description

Adds a script that shows how to build a "universal binary" library framework for all Apple devices that can be easily imported into a a multi-platform Xcode project. It also includes an example swiftUI application that calls a C driver function wolfCrypt tests and runs a simple TLS example

Gory details and demo app instructions can be found in the `README`

I added this to the IDE directory, but let me know if it should instead belong to another place or in another repo

2023-07-13 18:40 UTC, dgarske requested changes

2023-07-13 19:04 UTC, bigbrett commented
@dgarske added license header to the build script and swift files too, let me know if that is excessive and I can remove.

2023-07-13 21:21 UTC, dgarske requested changes

2023-07-13 21:21 UTC, dgarske commented on IDE/apple-universal/README.md
> +    │   ├── simple_client_example.c # <-- Simple TLS example that conects to wolfssl.com
Typo `conects` -> `connects`.

2023-07-13 21:21 UTC, dgarske commented on IDE/apple-universal/README.md
> +This example shows how to build a wolfSSL static library for Apple targets on all architectures using GNU autotools/`configure` and demonstrates how to create a [universal binary framework]() suitabl
Please document what version of Xcode this is tested with... My 13.2.1 could not open the wolfssl-multiplatform.xcodeproj (too old).

2023-07-13 21:21 UTC, dgarske commented on IDE/apple-universal/build-wolfssl-framework.sh
> +#!/bin/bash
Great script! Thank you

2023-07-13 21:21 UTC, dgarske commented on IDE/apple-universal/wolfssl-multiplatform/wolfssl-multiplatform/simple_client_example.c
> +    /* Load CA certificate into WOLFSSL_CTX
Line length cleanups. 80 chars max. Thanks

2023-07-13 22:40 UTC, dgarske submitted a review, later dismissed
Over to @JacobBarthelmeh

2023-07-14 15:52 UTC, JacobBarthelmeh requested changes
would be nice to have in the dist bundle for users, please update a include.am file for `make dist`

2023-07-14 18:30 UTC, bigbrett commented
> would be nice to have in the dist bundle for users, please update a include.am file for `make dist`

@JacobBarthelmeh done

2023-07-17 19:33 UTC, JacobBarthelmeh approved these changes
Re-ran the Jenkins tests, they look ok just the status did not get updated.

Thanks Brett!

2023-07-17 20:50 UTC, bigbrett commented
Added support for passing additional options to configure on the command line

2023-07-19 21:38 UTC, JacobBarthelmeh approved these changes

2023-07-19 21:39 UTC, JacobBarthelmeh commented
> Added support for passing additional options to configure on the command line

Tested running the script with an added --enable-<option> and it picked it up. Thanks Brett!

2023-07-19 21:39 UTC, merged