WOLFSSL_NO_HASH_RAW Hmac_UpdateFinal() properties for SM3
wolfSSL/wolfssl pull request #6647
Opened 2023-07-24 16:32 UTC by gojimmypi

# Description

Update the Hmac_UpdateFinal() properties needed when SM3 is enabled.

Fixes zd# n/a

Fixes https://github.com/wolfSSL/wolfssl/issues/6643

Thanks @JacobBarthelmeh for the SM3 help and suggestions.

# Testing

How did you test?

Tested with manual install of SM cipher suite with upcoming ESP32 example & Windows & Linux client.

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2023-07-24 18:19 UTC, bandi13 commented
retest this please

2023-07-25 21:38 UTC, SparkiDev requested changes

2023-07-25 21:38 UTC, SparkiDev commented on src/tls.c
> +#if defined(WOLFSSL_SM3)
Not needed as hash.h includes all the algorithm headers.

2023-07-26 00:41 UTC, SparkiDev approved these changes

2023-07-26 01:32 UTC, merged