Update Japanese API comments
wolfSSL/wolfssl pull request #6663
Opened 2023-07-31 05:04 UTC by TakayukiMatsuo

# Description

This PR is to update Japanese API comments to match them in PR6417.

2023-08-04 05:44 UTC, miyazakh requested changes

2023-08-04 05:44 UTC, miyazakh commented on doc/dox_comments/header_files-ja/aes.h
> +    \return BAD_FUNC_ARG  keyの長さが無効な場合は返されます。
"key" -> "鍵"?

2023-08-04 05:44 UTC, miyazakh commented on doc/dox_comments/header_files-ja/aes.h
> +    \param aes  付属のkeyを保管するためのAES構造
"key" -> "鍵"?

2023-08-04 05:44 UTC, miyazakh commented on doc/dox_comments/header_files-ja/aes.h
> +    \brief  この関数は、CCMを使用してAESオブジェクトの鍵を設定します（CBC-MACのカウンタ）。AES構造体へのポインタを取り、付属のkeyで初期化します。
"key" -> "鍵"?

2023-08-04 05:44 UTC, miyazakh commented on doc/dox_comments/header_files-ja/chacha20_poly1305.h
> +    \param inKey  復号に使用する32バイトのキーを含むバッファへのポインタ
"キー" -> "鍵"?

2023-08-08 04:48 UTC, TakayukiMatsuo commented on doc/dox_comments/header_files-ja/chacha20_poly1305.h
> +    \param inKey  復号に使用する32バイトのキーを含むバッファへのポインタ
"鍵"に変更しました。

2023-08-08 04:48 UTC, TakayukiMatsuo commented on doc/dox_comments/header_files-ja/aes.h
> +    \brief  この関数は、CCMを使用してAESオブジェクトの鍵を設定します（CBC-MACのカウンタ）。AES構造体へのポインタを取り、付属のkeyで初期化します。
"付属のkey”　->　”引数で与えられたkey”に変更しました。

2023-08-08 04:48 UTC, TakayukiMatsuo commented on doc/dox_comments/header_files-ja/aes.h
> +    \param aes  付属のkeyを保管するためのAES構造
”引数key”と変更しました。

2023-08-08 04:48 UTC, TakayukiMatsuo commented on doc/dox_comments/header_files-ja/aes.h
> +    \return BAD_FUNC_ARG  keyの長さが無効な場合は返されます。
”key"は引数の名前なので訳さずそのままにして”引数key”と変更しました。

2023-08-08 04:48 UTC, TakayukiMatsuo commented on doc/dox_comments/header_files-ja/aes.h
> +    指定された鍵、iv（初期化ベクトル）、および暗号化dir（方向）でAESオブジェクトを初期化します。
調査したら、この関数はwc_AesEncryptDirect/wc_AesDecryptDirect に使用する鍵の設定に使用する関数で、このどちらの関数向けに使用するかの引数を第5引数のdirで指定することになっています。あるH/Wアクセラレータでは鍵データの内部配置を暗号化と復号で変更が必要なようで、この関数の内部でそのような処理を行っています。

この説明部分ではこの引数dirに関する説明が欠けていたので追加し、関係している関数についての説明を追加しました。

2023-08-11 03:28 UTC, TakayukiMatsuo commented
Jenkins retest this please

2023-08-11 22:03 UTC, TakayukiMatsuo commented
Jenkins retest this please

2023-08-11 23:05 UTC, miyazakh approved these changes

2023-08-11 23:05 UTC, merged