Update Japanese API comments
wolfSSL/wolfssl pull request #6665
Opened 2023-08-01 05:12 UTC by TakayukiMatsuo

# Description

This PR is to update Japanese API comments to match them in PR6472.

2023-08-01 23:38 UTC, TakayukiMatsuo commented
jenkins retest this please

2023-08-02 21:52 UTC, miyazakh requested changes

2023-08-02 21:52 UTC, miyazakh commented on doc/dox_comments/header_files-ja/rsa.h
> +    \brief  RSAアルゴリズムに使用される個々の要素（E、N）にRsaKey構造体を平らにします。
”平ら”でもいいようなきがしますが、”均一にする”の方がしっくりきませんか？もしくは、”フラットにする”ともとのままにするか。細かいですが。

2023-08-03 01:32 UTC, TakayukiMatsuo commented on doc/dox_comments/header_files-ja/rsa.h
> +    \brief  RSAアルゴリズムに使用される個々の要素（E、N）にRsaKey構造体を平らにします。
この”Flatten”は処理を追ってみたら、桁の大きい整数値を配列データとしてバッファに”ばらして”取り出す処理のことを意味しているようです。ユーザーからみて、”平ら”、”均一”、"フラットにする"はどれも関数が実行する機能を連想させないので、この関数の概要説明では単純に”バッファに取り出す”にしようと思います。

2023-08-04 05:37 UTC, miyazakh approved these changes

2023-08-04 05:37 UTC, merged