Add some OpenSSL compat error strings.
wolfSSL/wolfssl pull request #6672
Opened 2023-08-04 15:24 UTC by anhu

Fixes ZD 16534

2023-08-04 18:07 UTC, anhu commented
jenkins retest this please

2023-08-07 21:01 UTC, JacobBarthelmeh requested changes

2023-08-07 21:01 UTC, JacobBarthelmeh commented on src/internal.c
> +#if defined(OPENSSL_EXTRA) || defined(OPENSSL_EXTRA_X509_SMALL) || \
The OPENSSL_EXTRA_X509_SMALL initial work was trimmed where every byte of code size mattered. Can this section of extra error messages not be included for OPENSSL_EXTRA_X509_SMALL?

2023-08-09 04:07 UTC, anhu commented
jenkins retest this please

2023-08-09 14:27 UTC, anhu commented
jenkins retest this please

2023-08-09 15:28 UTC, JacobBarthelmeh approved these changes

2023-08-09 15:28 UTC, merged