Ech hello retry request
wolfSSL/wolfssl pull request #6805
Opened 2023-09-25 05:53 UTC by jpbland1

# Description

Refactor Hpke to allow multiple uses of a context instead of just one shot mode. Refactor ECH to handle hello retry request with a different ech acceptance scheme and to re-use the hpke context after a hello retry request when sending the second client hello

Fixes https://github.com/wolfSSL/wolfssl/issues/6802

# Testing

Tested the regular  ECH through unit tests, need to figure out how to trigger an HRR

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2023-09-25 16:51 UTC, dgarske submitted a review, later dismissed
Looks good. Would like to see customer feedback. Assigned to PR cap wolfssl-bot.

2023-09-25 19:36 UTC, JacobBarthelmeh commented
AArch64 test failed, possibly from network hiccup? Retest this please Jenkins

```
mutex    test passed!
memcb    test passed!
Test complete

wolfSSL error: tcp connect failed: Connection refused

Running simple test
SSL version is TLSv1.2
SSL cipher suite is TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
SSL curve name is SECP256R1
```

2023-09-26 20:49 UTC, JacobBarthelmeh commented
Looks like CI is flagging a valgrind test. Please also rebase onto master rather than merge in, seems like github has issues when merging in the master branch as seen here with lots of extra commits showing.

2024-09-23 18:37 UTC, dgarske commented
@jpbland1 please resolve merge conflicts.

2025-03-10 22:38 UTC, SparkiDev requested changes

2025-03-10 22:38 UTC, SparkiDev commented on src/internal.c
> +    ssl->hsHashes = ssl->hsHashesEch;
Assigning to be freed seems silly.
Make a function that takes a HsHashes* and frees it.
Either name it FreeHanshakeHashes and change callers or have FreeHanshakeHashes call the new function.

2025-03-12 23:17 UTC, SparkiDev approved these changes

2025-03-12 23:17 UTC, merged