SM2 named curve disabled: value outside of supported values
wolfSSL/wolfssl pull request #6880
Opened 2023-10-17 06:27 UTC by SparkiDev

# Description

SM2 named curve value is specified in specification. Values 0-14 aren't used, so, those bits in disabledCurves are used for values over 31.
Add range checks.

# Testing

Standard

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2023-10-17 16:03 UTC, JacobBarthelmeh approved these changes

2023-10-17 16:07 UTC, JacobBarthelmeh requested changes
the master + openvpn is expected to fail but looks like there is an additional failure reported with the PRB tests that needs investigation before merging:

```
Requires AEAD
Verified suite validity
Unable to get supported curve
Unsupported cipher suite, ClientHello 1.3
wolfSSL Leaving DoTls13ClientHello, return -421
```

2023-10-17 21:16 UTC, SparkiDev commented
retest this please

2023-10-18 03:36 UTC, SparkiDev commented
retest this please

2023-10-18 16:50 UTC, JacobBarthelmeh approved these changes

2023-10-18 16:51 UTC, merged