Fix static analyzer possible leak
wolfSSL/wolfssl pull request #6894
Opened 2023-10-19 14:58 UTC by julek-wolfssl

crl would never be null there but clean up code to make sure newcrl->crlLock gets free'd

2023-10-23 12:25 UTC, julek-wolfssl commented
Retest this please

2023-10-23 14:17 UTC, bandi13 commented on src/crl.c
> +            FreeCRL(crl, 1);
`FreeCRL` should also check `crl != NULL` and return BAD_ARG_ERR or something. It will crash if NULL is passed.

2023-10-23 14:18 UTC, bandi13 requested changes
I have some questions that should be addressed.

2023-10-24 08:30 UTC, julek-wolfssl commented on src/crl.c
> +            FreeCRL(crl, 1);
`crl` will never be `NULL` here as its checked right after allocation. I agree that `FreeCRL` should be performing a check internally though.

2023-10-24 13:13 UTC, bandi13 approved these changes

2023-10-24 13:13 UTC, merged