Add MSYS2 build CI test
wolfSSL/wolfssl pull request #6932
Opened 2023-10-31 20:56 UTC by lealem47

# Description

Add MSYS2 build CI github actions test

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2024-05-16 16:39 UTC, dgarske requested changes

2024-05-16 16:39 UTC, dgarske commented on tests/api.c
> +    SOCKET_T clientfd;
Usually we use `SOCKET_INVALID`.

2024-05-16 16:39 UTC, dgarske commented on tests/api.c
> +#ifdef USE_WINDOWS_API
Seems unnecessary. Either case should be happy with `(char*)`

2024-05-16 16:39 UTC, dgarske commented on tests/api.c
> +    int freeClientfd = 0;
Shouldn't be required.

2024-05-16 16:39 UTC, dgarske commented on tests/api.c
> +    if (freeClientfd)
`clientFd != SOCKET_INVALID`

2025-01-22 16:34 UTC, lealem47 commented
Closing this. Being handled in https://github.com/wolfSSL/wolfssl/pull/8367

2025-01-22 16:34 UTC, closed without merging