Add streaming support for PKCS7_VerifySignedData.
wolfSSL/wolfssl pull request #6961
Opened 2023-11-10 05:37 UTC by TakayukiMatsuo

# Description

Extend PKCS7_VerifySignedData streaming to support  PKCS7 bundle which has multiple part octet.
Please note that In the PR,  added a small change to wc_PKCS7_AddDataToStream to fix the accumulation issue. Therefore, this change may impact other APIs that rely on this function. I would like reviewers to focus on this point. 

Fixes zd#16606

# Testing

Run an application and data provided in zd#16606.

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2023-12-11 09:51 UTC, TakayukiMatsuo commented
Hi　@JacobBarthelmeh ,

In this PR, I made a small change to wc_PKCS7_AddDataToStream. This change resets pksc7->stream>idx to 0 after reading the input data that satisfies the argument expected. Without this modification, If pksc7->stream>idx is not reset to 0, the input data will be skipped in the next wc_PKCS7_AddDataToStream call.

I thought this was a bug, so made a change in this PR. However, this change caused errors in existing streaming test cases.
Am wondering if this change is wrong, or if I'm calling wc_PKCS7_AddDataToStream incorrectly. I would be happy to hear your opinions on the changes I have made.

Thanks,
Tak

2023-12-20 20:06 UTC, douzzer requested changes
Hi Tak.  Most of the change requests from my review are for reports from automated analysis.

The one bigger problem is regarding the change to `wc_PKCS7_AddDataToStream()`.  In order to get the existing unit tests to pass, I had to comment that out.

I don't yet understand the problem you were addressing with that clause, but whatever it is, we need to include new test(s) in `wolfcrypt/test/test.c` and/or `tests/api.c` that test for it and fail without the fix.

2023-12-20 20:06 UTC, douzzer commented on wolfcrypt/src/pkcs7.c
> +            detached  = pkcs7->stream->detached;
These assignments are producing
```
wolfssl/wolfcrypt/src/pkcs7.c:5403:13: warning: Value stored to 'multiPart' is never read [clang-analyzer-deadcode.DeadStores]
wolfssl/wolfcrypt/src/pkcs7.c:5404:13: warning: Value stored to 'detached' is never read [clang-analyzer-deadcode.DeadStores]
```

2024-01-17 18:24 UTC, JacobBarthelmeh commented
FYI for the current failing PRB master it looks to be a build when PKCS7 streaming mode is disabled (defining the macro NO_PKCS7_STREAM):

```
wolfcrypt/src/pkcs7.c:5273:18: error: ‘PKCS7’ has no member named ‘stream’
 5273 |         if (pkcs7->stream->content != NULL) {

      |                  ^~

In file included from ./wolfssl/wolfcrypt/pkcs7.h:29,

                 from wolfcrypt/src/pkcs7.c:31:

wolfcrypt/src/pkcs7.c:5274:24: error: ‘PKCS7’ has no member named ‘stream’
 5274 |             XFREE(pkcs7->stream->content, pkcs7->heap, DYNAMIC_TYPE_PKCS7);
      |                        ^~
./wolfssl/wolfcrypt/types.h:573:63: note: in definition of macro ‘XFREE’
```

Not as sure on the krb5 actions test, it would need farther investigation.

2024-01-19 06:51 UTC, TakayukiMatsuo commented
@douzzer , @JacobBarthelmeh  and @dgarske ,  thank you for your help. It's been a while, but I will adjust my time to complete this PR.

2024-01-30 07:30 UTC, TakayukiMatsuo commented on wolfcrypt/src/pkcs7.c
> +                    /* set indef-length count. used for skipping trailing zeros */
fixed the length.

2024-01-30 07:31 UTC, TakayukiMatsuo commented on wolfcrypt/src/pkcs7.c
> +            pkiMsg2Sz = (pkcs7->stream->length > 0)? pkcs7->stream->length:srcSz;
fixed the length.

2024-01-30 07:34 UTC, TakayukiMatsuo commented on wolfcrypt/src/pkcs7.c
> +            pkiMsg2Sz = (pkcs7->stream->length > 0)? pkcs7->stream->length:srcSz;
fixed the length.

2024-01-30 07:34 UTC, TakayukiMatsuo commented on wolfcrypt/src/pkcs7.c
> +            pkiMsg2Sz = (pkcs7->stream->length > 0)? pkcs7->stream->length:srcSz;
fixed the length.

2024-01-30 07:35 UTC, TakayukiMatsuo commented on wolfcrypt/src/pkcs7.c
> +            detached  = pkcs7->stream->detached;
removed those two lines.

2024-01-30 07:37 UTC, TakayukiMatsuo commented on wolfcrypt/src/pkcs7.c
> +        }
removed the portion.

2024-02-05 20:12 UTC, bandi13 commented
retest this please

2024-02-20 00:35 UTC, cconlon commented
@TakayukiMatsuo Is this ready for re-review?

Thanks,
Chris

2024-02-20 00:39 UTC, TakayukiMatsuo commented
@cconlon , yes, it is ready.

2024-02-20 00:42 UTC, cconlon commented
Thanks @TakayukiMatsuo, I'm assigning over to @JacobBarthelmeh for re-review.  @JacobBarthelmeh, feel free to have @douzzer re-review his comments if you would like.

2024-02-21 19:47 UTC, JacobBarthelmeh requested changes
There appears to be some issues when trying this out. Could you let me know if these tests are invalid?

Steps to recreate:

Create a test SMIME bundle
```
cd wolfssl-examples/pkcs7
openssl smime -sign -in ~/Documents/wolfssl/configure.ac -out test-signed -signer ../certs/ca-cert.pem -nodetach -nocerts -binary -outform DER -stream -inkey ../certs/ca-key.pem 
```

Alter the pkcs7-verify.c example to take in an argument and verify in chunks:

```
--- a/pkcs7/pkcs7-verify.c
+++ b/pkcs7/pkcs7-verify.c
@@ -42,7 +42,7 @@ int main(int argc, char** argv)
 #endif
 
     /* load DER PKCS7 */
-    derFile = fopen("signed.p7s", "rb");
+    derFile = fopen(argv[1], "rb");
     if (derFile) {
         fseek(derFile, 0, SEEK_END);
         derSz = (int)ftell(derFile);
@@ -70,9 +70,14 @@ int main(int argc, char** argv)
     if (rc != 0) goto exit;
     rc = wc_PKCS7_InitWithCert(&pkcs7, NULL, 0);
     if (rc != 0) goto exit;
-    rc = wc_PKCS7_VerifySignedData(&pkcs7, derBuf, derSz);
-    if (rc != 0) goto exit;
 
+    int z, chunkSz = 1;
+    for (z = 0; z < derSz;) {
+        int sz = (z + chunkSz > derSz)? derSz - z : chunkSz;
+        rc = wc_PKCS7_VerifySignedData(&pkcs7, derBuf+z, sz);
+        z+=sz;
+    }
+    if (rc != 0) goto exit;
     printf("PKCS7 Verify Success\n");
 
 exit:
```

With chunkSz set to 1 it fails out with -270 (want more data), but set to 10 it succeeds with -272 (needs sig verify) which is expected here since -nocerts was used when creating the test bundle.


Moving on to a bundle that has certificates in it:

```
openssl smime -sign -in ~/Documents/wolfssl/configure.ac -out test-signed -signer ../certs/ca-cert.pem -nodetach -binary -outform DER -stream -inkey ../certs/ca-key.pem 
```

The test application is getting -270 with chunkSz set to 10:

```
bash-3.2$ ./pkcs7-verify test-signed 
Der 318126
RC=-270
```

Upping chunkSz to 100 then saw it verify successfully.

2024-02-21 20:27 UTC, douzzer requested changes
looks mostly good -- `super-quick-check` found one trivial defect.

2024-02-21 20:27 UTC, douzzer commented on wolfcrypt/src/pkcs7.c
> +                pkcs7->contentDynamic   = XMALLOC(pkcs7->stream->contentSz,
This is warning on C++:
```
[all-g++] [7 of 31] [2bce5fef9f]
    configure...   real 0m21.405s  user 0m8.403s  sys 0m14.967s
    build...In file included from ./wolfssl/wolfcrypt/pkcs7.h:29,
                 from wolfcrypt/src/pkcs7.c:31:
wolfcrypt/src/pkcs7.c: In function ‘int PKCS7_VerifySignedData(PKCS7*, const byte*, word32, byte*, word32, byte*, word32)’:
9386a882b9 (<juliusz@wolfssl.com> 2021-10-19 15:51:29 +0200 571)                 #define XMALLOC(s, h, t)     ((void)(h), (void)(t), wolfSSL_Malloc((s)))
./wolfssl/wolfcrypt/types.h:571:67: error: invalid conversion from ‘void*’ to ‘byte*’ {aka ‘unsigned char*’} [-fpermissive]
  571 |                 #define XMALLOC(s, h, t)     ((void)(h), (void)(t), wolfSSL_Malloc((s)))
      |                                              ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
      |                                                                   |
      |                                                                   void*
2bce5fef9f (<tak@wolfssl.com> 2023-11-07 13:09:38 +0900 5363)                 pkcs7->contentDynamic   = XMALLOC(pkcs7->stream->contentSz,
wolfcrypt/src/pkcs7.c:5363:43: note: in expansion of macro ‘XMALLOC’
 5363 |                 pkcs7->contentDynamic   = XMALLOC(pkcs7->stream->contentSz,
      |                                           ^~~~~~~
make[2]: *** [Makefile:7251: wolfcrypt/src/src_libwolfssl_la-pkcs7.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:8064: all-recursive] Error 1
make: *** [Makefile:4782: all] Error 2
   real 0m14.125s  user 1m20.695s  sys 0m8.076s
    all-g++ fail_build
    failed config: '--enable-all' '--enable-testcert' '--enable-srtp' '--enable-sp-math-all' 'CC=g++' 'CPPFLAGS=-DNO_WOLFSSL_CIPHER_SUITE_TEST -DWOLFSSL_OLD_PRIME_CHECK'
```

2024-02-24 03:14 UTC, TakayukiMatsuo commented on wolfcrypt/src/pkcs7.c
> +                pkcs7->contentDynamic   = XMALLOC(pkcs7->stream->contentSz,
Added a cast to XMALLOC.

2024-02-24 03:15 UTC, TakayukiMatsuo commented
Hi Jacob,  

Probably need to modify the code fragment you use a bit to be able to handle the return code from wc_PKCS7_VerifySignedData, like this:
```
 for (z = 0; z < derSz;) {
        int sz = (z + chunkSz > derSz)? derSz - z : chunkSz;
        rc = wc_PKCS7_VerifySignedData(&pkcs7, derBuf + z, sz);
        if (rc < 0) {
            if (rc == WC_PKCS7_WANT_READ_E) {
                z += sz;
                continue;
            }
            printf("Error z:%d %d: %s\n", z, rc, wc_GetErrorString(rc));
            break;
        }
        else {
            break;
        }
    }
```

With this code, could get expected result with the test bundle file.
Tak

2024-02-26 08:24 UTC, JacobBarthelmeh commented
> Hi Jacob,
> 
> Probably need to modify the code fragment you use a bit to be able to handle the return code from wc_PKCS7_VerifySignedData, like this:
> 
> ```
>  for (z = 0; z < derSz;) {
>         int sz = (z + chunkSz > derSz)? derSz - z : chunkSz;
>         rc = wc_PKCS7_VerifySignedData(&pkcs7, derBuf + z, sz);
>         if (rc < 0) {
>             if (rc == WC_PKCS7_WANT_READ_E) {
>                 z += sz;
>                 continue;
>             }
>             printf("Error z:%d %d: %s\n", z, rc, wc_GetErrorString(rc));
>             break;
>         }
>         else {
>             break;
>         }
>     }
> ```
> 
> With this code, could get expected result with the test bundle file. Tak

Tak, adding an early bail on error case does succeed. This likely means that the last bytes of the bundle are not being parsed though and that it is reaching the (-272) error in this case early. With indef it should only be 0's but I think we should have it confirm that they are. Adding `derBuf[derSz - 2] = derBuf[derSz - 2] + 1;  ` before verifying the bundle seems to still return success.

2024-02-27 14:26 UTC, bandi13 commented
retest this please

2024-02-27 18:06 UTC, TakayukiMatsuo commented
Hi Jacob, added trailing zero's check.

2024-02-28 14:40 UTC, JacobBarthelmeh commented
Hi @TakayukiMatsuo , Please double check the case of altering the last bytes in the bundle before verification.

2024-02-29 02:04 UTC, TakayukiMatsuo commented
Hi @JacobBarthelmeh , Confirmed ASN_PARSE_E(-140) is returned when the last byte of the bundle is altered by adding  `derBuf[derSz - 2] = derBuf[derSz - 2] + 1; `  to the sample code.

2024-03-01 15:34 UTC, JacobBarthelmeh approved these changes
Thanks @TakayukiMatsuo for all your hard work on this!

2024-03-01 15:38 UTC, merged