Add STM32H725 to default_conf.ftl
wolfSSL/wolfssl pull request #6975
Opened 2023-11-15 16:12 UTC by lealem47

# Description

Fixes https://github.com/wolfSSL/wolfssl/issues/6969

# Testing

Tested by reporter

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2023-11-15 16:20 UTC, dgarske requested changes

2023-11-15 16:20 UTC, dgarske commented on IDE/STM32Cube/default_conf.ftl
> +#elif defined(STM32H725xx)
Please add it to the line 110 as `||`

2023-11-15 20:13 UTC, lealem47 commented
Jenkins Retest this please

2023-11-16 05:15 UTC, dgarske approved these changes

2023-11-16 05:15 UTC, merged