rpm: switched source to GitHub
wolfSSL/wolfssl pull request #7002
Opened 2023-11-25 18:09 UTC by sergey-safarov

# Description

I found relase sources from Github and from  http://wolfssl.com/ does not equal.
Sources from  http://wolfssl.com/ do not contains `autogen.sh`
Also `autogen.sh` is recomented to use in the bulid process.

This PR changes this in RPM spec file.

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2023-11-26 06:42 UTC, sergey-safarov commented
Here maybe questions for this change
```diff
diff --git a/rpm/include.am b/rpm/include.am
index 5d15a1ca0..f549078c8 100644
--- a/rpm/include.am
+++ b/rpm/include.am
@@ -4,6 +4,12 @@ rpm-build: rpm/spec dist
        @rm -f *.rpm
        rpmdev-setuptree
        find ~/rpmbuild/RPMS ~/rpmbuild/SRPMS -name "$(PACKAGE)-$(VERSION)*.rpm" | xargs rm -f
+       @rm -Rf $(PACKAGE)-$(VERSION)-stable
+       @tar xzf $(PACKAGE)-$(VERSION).tar.gz
+       @mv $(PACKAGE)-$(VERSION) $(PACKAGE)-$(VERSION)-stable
+       @cp autogen.sh $(PACKAGE)-$(VERSION)-stable
+       @rm -f $(PACKAGE)-$(VERSION).tar.gz
+       @tar czf $(PACKAGE)-$(VERSION).tar.gz $(PACKAGE)-$(VERSION)-stable
        @cp $(PACKAGE)-$(VERSION).tar.gz ~/rpmbuild/SOURCES/
        @rpmbuild -ba --clean rpm/spec
        @cp ~/rpmbuild/RPMS/*/$(PACKAGE)-$(VERSION)*.rpm .
```
We maybe need include `autogen.sh` into tar archive and do not use
```
+       @cp autogen.sh $(PACKAGE)-$(VERSION)-stable
```
Also propable we need to include `wolfssl/options.h` into tar archive.

I have added suffix `stable` into sourcedir to match archive used on github.
```
+       @mv $(PACKAGE)-$(VERSION) $(PACKAGE)-$(VERSION)-stable
```

2023-11-27 20:32 UTC, JacobBarthelmeh requested changes
@sergey-safarov do these changes help resolve an issue experienced with the RPM bundling?

2023-11-27 20:32 UTC, JacobBarthelmeh commented on rpm/include.am
> +	@cp autogen.sh $(PACKAGE)-$(VERSION)-stable
autogen.sh is really for recreating the configure file and initial setup after the repository is cloned. Existing bundles, or new bundles created with make dist, should not need autogen.sh though. If running into a case where configure.ac needs altered and configure needs re-created `autoreconf -fi` could be ran.

2023-11-27 20:32 UTC, JacobBarthelmeh commented on rpm/spec.in
> +%{_libdir}/libwolfssl@LIBSUFFIX@.so.*
These changes here to "so" and "libdir" are correct, there was another recent report about it.

2023-12-01 14:17 UTC, sergey-safarov commented
Hello @JacobBarthelmeh 
I have used `autoreconf -fi`. This simplified changes.
Could you now check PR.

2023-12-12 16:20 UTC, dgarske commented
Hi @sergey-safarov ,

Thank you for the suggestions. This has been fixed in PR: https://github.com/wolfSSL/wolfssl/pull/7055

Thanks,
David Garske, wolfSSL

2023-12-12 16:20 UTC, closed without merging

2023-12-12 18:51 UTC, dgarske commented
HI @sergey-safarov ,

We decided not to take these changes. For building the RPM package from sources directly use the `./autogen.sh` or `autoreconf -fi` locally before.

```
./autogen.sh
./configure --enable-distro
make rpm
```

Thanks,
David Garske, wolfSSL