ECC: generate values in range of order by rejection
wolfSSL/wolfssl pull request #7020
Opened 2023-11-30 01:50 UTC by SparkiDev

# Description

When generating private key and nonce for ECDSA, use rejection sampling. Note: SP uses this algorithm

Fixes zd#17099

# Testing

./configure '--disable-shared' '--enable-ecccustcurves=all'
./configure '--disable-shared' '--enable-ecccustcurves=all' --enable-heapmath
./configure '--disable-shared' '--enable-ecccustcurves=all' --enable-fastmath

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2023-12-12 03:45 UTC, SparkiDev commented
retest this please

2023-12-12 06:35 UTC, SparkiDev commented
retest this please

2023-12-14 20:07 UTC, dgarske requested changes
Looks good otherwise. Just spelling

2023-12-14 20:07 UTC, dgarske commented on wolfcrypt/src/ecc.c
> + *                      Use this when CPU state can be closely observered by
Spelling `observered` -> `observed`

2023-12-14 20:16 UTC, dgarske approved these changes

2023-12-14 21:09 UTC, SparkiDev commented
Reporter is happy the new code is timing resistant.

2023-12-14 21:19 UTC, SparkiDev commented
retest this please

2023-12-14 21:54 UTC, cconlon approved these changes

2023-12-14 21:54 UTC, merged