Additional TLS checks
wolfSSL/wolfssl pull request #7029
Opened 2023-12-05 12:55 UTC by julek-wolfssl

- double check which messages need to be encrypted
- check msgs that have to be last in a record

ZD17108

2023-12-08 15:55 UTC, JacobBarthelmeh approved these changes, later dismissed

2023-12-08 15:58 UTC, JacobBarthelmeh commented
Looks good to me, would like at least one other review on this though since the code changes will affect all TLS/DTLS users.

2023-12-11 18:23 UTC, dgarske requested changes
This PR looks good. It grows my build by 384 bytes. Should we consider a way to disable this feature, but keep it on by default?
I'd like Sean to review before its merged.

2023-12-11 19:00 UTC, julek-wolfssl commented
I don't think that its a good idea to remove these checks. These are important checks that are relevant for increasing security of all (D)TLS versions.

2023-12-11 21:08 UTC, SparkiDev requested changes

2023-12-11 21:08 UTC, SparkiDev commented on src/internal.c
> +        msg->encrypted = msg->encrypted && encrypted ? 1 : 0;
msg->encrypted = msg->encrypted && encrypted;

2023-12-11 21:08 UTC, SparkiDev commented on src/internal.c
> +        msg->encrypted = encrypted ? 1 : 0;
msg->encrypted = encrypted;

2023-12-12 14:13 UTC, julek-wolfssl commented on src/internal.c
> +        msg->encrypted = msg->encrypted && encrypted ? 1 : 0;
Fixed

2023-12-12 14:13 UTC, julek-wolfssl commented on src/internal.c
> +        msg->encrypted = encrypted ? 1 : 0;
Fixed

2023-12-12 16:06 UTC, dgarske requested changes
PR looks great. Can you please add a build option to disable this check for users that might not want it?

2023-12-12 16:32 UTC, julek-wolfssl commented
@dgarske build option added with `WOLFSSL_DISABLE_EARLY_SANITY_CHECKS`.

2023-12-12 18:46 UTC, dgarske approved these changes
Over to @SparkiDev to finalize.

2023-12-12 18:47 UTC, dgarske commented
Retest this please

2023-12-12 21:15 UTC, SparkiDev commented
retest this please

2023-12-12 22:39 UTC, SparkiDev approved these changes

2023-12-13 00:14 UTC, douzzer approved these changes
passed a run through `wolfssl-multi-test.sh ... super-quick-check` (latest sanitizers, `clang-tidy`, and `cppcheck`), rebased on current `master`.

2023-12-13 00:16 UTC, dgarske commented
Retest this please

2023-12-13 04:31 UTC, merged