Add wolfSSL_set_alpn_select_cb() for setting ALPN select callback on WOLFSSL session
wolfSSL/wolfssl pull request #7054
Opened 2023-12-11 20:55 UTC by cconlon

# Description

This PR adds one API `wolfSSL_set_alpn_select_cb()`, allowing applications to set the ALPN select callback at the `WOLFSSL` level. wolfSSL already has the `WOLFSSL_CTX` variant: `wolfSSL_CTX_set_alpn_select_cb()`.

This was needed for use by wolfJSSE since the JSSE API expects to have the callback be settable on a per-session basis (not per-context).

# Testing

Added two simple API tests (success, failure), but also testing through wolfJSSE built-in tests and extended SunJSSE testing.

# Checklist

 - [x] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2023-12-12 17:07 UTC, cconlon commented
Retest this please Jenkins

2023-12-12 19:07 UTC, cconlon commented
Retest this please

2023-12-13 00:16 UTC, cconlon commented
Retest this please

2023-12-13 00:17 UTC, dgarske commented
Retest this please

2023-12-13 04:39 UTC, dgarske approved these changes

2023-12-13 15:56 UTC, dgarske requested changes

2023-12-13 15:56 UTC, dgarske commented on tests/api.c
> +    char proto[] = {0x73, 0x70, 0x64, 0x79, 0x2f, 0x32};
`const char`?

2023-12-13 15:56 UTC, dgarske commented on tests/api.c
> +        *outlen = sizeof(proto);
Needs cast `(unsigned char)`

2023-12-13 16:17 UTC, cconlon commented on tests/api.c
> +    char proto[] = {0x73, 0x70, 0x64, 0x79, 0x2f, 0x32};
Thanks, added

2023-12-13 16:17 UTC, cconlon commented on tests/api.c
> +        *outlen = sizeof(proto);
Thanks, added

2023-12-13 16:23 UTC, dgarske approved these changes

2023-12-13 17:24 UTC, merged