Add more information to the crypto callback `DEBUG_CRYPTOCB`
wolfSSL/wolfssl pull request #7070
Opened 2023-12-14 18:55 UTC by dgarske

# Description

Add more information in the `DEBUG_CRYPTOCB`.
Fix typo with HMAC determination of update/final.

# Testing

```
./configure --enable-cryptocb --enable-debug CFLAGS="-DDEBUG_CRYPTOCB"
```

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2023-12-20 21:35 UTC, dgarske commented
Retest this please

2023-12-22 06:21 UTC, douzzer requested changes

2023-12-23 00:33 UTC, douzzer requested changes
The gcc sanitizers, due to multilevel inlining, have managed to figure out that there's something wrong with `Tls13DeriveKey()` in this PR.  It's clean on `master` so it seems to be new to this PR:
```
[sp-all-asm-sanitizer] [1 of 1] [59155051bb]
    autogen.sh 59155051bb...   real 0m16.249s  user 0m14.299s  sys 0m1.088s
    configure...   real 0m18.709s  user 0m10.000s  sys 0m10.108s
    build...In function ‘Tls13DeriveKey’,
6190666108 (<anthony@wolfssl.com> 2022-09-21 03:21:33 -0400 1095)     return Tls13DeriveKey(ssl, secret, -1, key, finishedLabel,
    inlined from ‘DeriveFinishedSecret’ at src/tls13.c:1095:12:
6190666108 (<anthony@wolfssl.com> 2022-09-21 03:21:33 -0400 502)     ret = Tls13HKDFExpandKeyLabel(ssl, output, outputLen, secret, hashSz,
src/tls13.c:502:11: error: ‘hash’ may be used uninitialized [-Werror=maybe-uninitialized]
  502 |     ret = Tls13HKDFExpandKeyLabel(ssl, output, outputLen, secret, hashSz,
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  503 |                                   protocol, protocolLen, label, labelLen,
      |                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  504 |                                   hash, hashOutSz, digestAlg, side);
      |                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/tls13.c: In function ‘DeriveFinishedSecret’:
6190666108 (<anthony@wolfssl.com> 2022-09-21 03:21:33 -0400 248) static int Tls13HKDFExpandKeyLabel(WOLFSSL* ssl, byte* okm, word32 okmLen,
src/tls13.c:248:12: note: by argument 8 of type ‘const byte *’ {aka ‘const unsigned char *’} to ‘Tls13HKDFExpandKeyLabel.constprop’ declared here
  248 | static int Tls13HKDFExpandKeyLabel(WOLFSSL* ssl, byte* okm, word32 okmLen,
      |            ^~~~~~~~~~~~~~~~~~~~~~~
481f4765eb (<david@wolfssl.com> 2018-01-11 09:52:49 -0800 431)     byte        hash[WC_MAX_DIGEST_SIZE];
src/tls13.c:431:17: note: ‘hash’ declared here
  431 |     byte        hash[WC_MAX_DIGEST_SIZE];
      |                 ^~~~
In function ‘Tls13DeriveKey’,
    inlined from ‘DeriveTrafficSecret’ at src/tls13.c:1116:12,
6190666108 (<anthony@wolfssl.com> 2022-09-21 03:21:33 -0400 1538)                 ret = DeriveTrafficSecret(ssl, ssl->clientSecret,
    inlined from ‘DeriveTls13Keys’ at src/tls13.c:1538:23:
6190666108 (<anthony@wolfssl.com> 2022-09-21 03:21:33 -0400 502)     ret = Tls13HKDFExpandKeyLabel(ssl, output, outputLen, secret, hashSz,
src/tls13.c:502:11: error: ‘hash’ may be used uninitialized [-Werror=maybe-uninitialized]
  502 |     ret = Tls13HKDFExpandKeyLabel(ssl, output, outputLen, secret, hashSz,
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  503 |                                   protocol, protocolLen, label, labelLen,
      |                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  504 |                                   hash, hashOutSz, digestAlg, side);
      |                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/tls13.c: In function ‘DeriveTls13Keys’:
6190666108 (<anthony@wolfssl.com> 2022-09-21 03:21:33 -0400 248) static int Tls13HKDFExpandKeyLabel(WOLFSSL* ssl, byte* okm, word32 okmLen,
src/tls13.c:248:12: note: by argument 8 of type ‘const byte *’ {aka ‘const unsigned char *’} to ‘Tls13HKDFExpandKeyLabel.constprop’ declared here
  248 | static int Tls13HKDFExpandKeyLabel(WOLFSSL* ssl, byte* okm, word32 okmLen,
      |            ^~~~~~~~~~~~~~~~~~~~~~~
481f4765eb (<david@wolfssl.com> 2018-01-11 09:52:49 -0800 431)     byte        hash[WC_MAX_DIGEST_SIZE];
src/tls13.c:431:17: note: ‘hash’ declared here
  431 |     byte        hash[WC_MAX_DIGEST_SIZE];
      |                 ^~~~
```
If I just `XMEMSET(hash, 0, sizeof hash)` at the start of the function, the sanitizing build and `make check` are clean.  But that shouldn't be necessary -- I'm concerned one of the hash functions isn't writing out the hash value correctly.

2023-12-27 22:38 UTC, douzzer approved these changes
LGTM.  Passing all the extra tests now.  The documentation update looks great!

2023-12-27 23:33 UTC, dgarske commented
Retest this please

2023-12-27 23:55 UTC, merged