Aria sign fix
wolfSSL/wolfssl pull request #7082
Opened 2023-12-19 20:57 UTC by bandi13

There was an issue when using MagicCrypto's version of signing. Turns out the wrong key format was used.

2023-12-20 05:07 UTC, bandi13 commented
retest this please

2023-12-21 21:26 UTC, SparkiDev requested changes

2023-12-21 21:26 UTC, SparkiDev commented on wolfcrypt/src/port/aria/aria-cryptocb.c
> +        int ret = wc_EccPrivateKeyToDer(key,keyarr,keySz);
space after ','

2023-12-21 21:26 UTC, SparkiDev commented on wolfcrypt/src/port/aria/aria-cryptocb.c
> +    *res = 0; /* Default to invalid signature */
res may be NULL

2023-12-21 23:52 UTC, douzzer approved these changes

2023-12-22 00:01 UTC, merged