TLS13 padding bounds check
wolfSSL/wolfssl pull request #7099
Opened 2023-12-27 21:11 UTC by jpbland1

# Description

When removing the padding for the TLS13 verify message step, check that the index doesn't wrap around due to a malformed packet

Fixes https://github.com/wolfSSL/wolfssl/issues/7089

# Testing

Tested with malicious client example provided by the bug reporter.

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2023-12-27 21:33 UTC, dgarske approved these changes

2023-12-28 17:59 UTC, jpbland1 commented
retest this please.

2024-01-02 07:02 UTC, douzzer requested changes

2024-01-02 07:02 UTC, douzzer commented on src/internal.c
> +                    if (i > ssl->buffers.inputBuffer.length || i == 0) {
If we need to test for integer overflow, then I suspect we need to test `ssl->buffers.inputBuffer.idx + ssl->curSize - ssl->specs.aead_mac_size` before casting it.

2024-01-04 06:09 UTC, douzzer approved these changes

2024-01-04 06:09 UTC, merged