server: allow reading 0-RTT data after writing 0.5-RTT data
wolfSSL/wolfssl pull request #7102
Opened 2023-12-28 14:55 UTC by julek-wolfssl

2024-01-03 21:14 UTC, SparkiDev requested changes

2024-01-03 21:14 UTC, SparkiDev commented on src/internal.c
> +    if (ssl->earlyData > early_data_ext && ssl->earlyData < done_early_data) {
Can you put side check here too?

2024-01-04 12:22 UTC, julek-wolfssl commented on src/internal.c
> +    if (ssl->earlyData > early_data_ext && ssl->earlyData < done_early_data) {
Added side check.

2024-01-04 21:14 UTC, SparkiDev approved these changes

2024-01-04 21:20 UTC, merged