Update cmac-api documents
wolfSSL/wolfssl pull request #7115
Opened 2024-01-05 03:24 UTC by TakayukiMatsuo

# Description

Update Japanese documents for Cmac API's

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [*] Updated manual and documentation

2024-01-05 07:48 UTC, TakayukiMatsuo commented
Jenkins retest this please

2024-01-07 23:35 UTC, miyazakh requested changes

2024-01-07 23:35 UTC, miyazakh commented on doc/dox_comments/header_files-ja/cmac.h
> +    \param outSz 結果出力先バッファのサイズ(in)と出力データサイズ(out)
中の処理を見ると、`\param out` のサイズのようなので、`結果出力先バッファのサイズ`　でいいように思います。

2024-01-07 23:35 UTC, miyazakh commented on doc/dox_comments/header_files-ja/cmac.h
> +     \param outSz 結果出力先バッファのサイズ(in)と出力データサイズ(out)
中の処理を見ると、\param out のサイズのようなので、結果出力先バッファのサイズ　でいいように思います。

2024-01-16 21:22 UTC, TakayukiMatsuo commented on doc/dox_comments/header_files-ja/cmac.h
> +     \param outSz 結果出力先バッファのサイズ(in)と出力データサイズ(out)
変更しました。

2024-01-16 21:22 UTC, TakayukiMatsuo commented on doc/dox_comments/header_files-ja/cmac.h
> +    \param outSz 結果出力先バッファのサイズ(in)と出力データサイズ(out)
変更しました。

2024-01-16 22:41 UTC, TakayukiMatsuo commented
Jenkins retest this please

2024-01-16 23:17 UTC, miyazakh approved these changes

2024-01-16 23:18 UTC, merged