update x509 functions and structures to support using heap hint
wolfSSL/wolfssl pull request #7126
Opened 2024-01-10 21:46 UTC by jpbland1

# Description

Adds ex versions of the x509 functions that XMALLOC or call other functions that XMALLOC to allow the use of a custom heap.

Fixes zd#17258

# Testing

Updated the api and wolfcrypt test to use the ex versions instead of the original

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2024-01-12 00:05 UTC, dgarske requested changes
Have you tested with `WOLFSSL_HEAP_TEST`?
Do all these new _ex functions need to be public? Can you check code size increase from this change?

2024-01-12 00:05 UTC, dgarske commented on src/ssl.c
> +    return (WOLFSSL_X509_PKCS12 *)wolfSSL_d2i_X509_fp_ex2(fp, (void **)pkcs12,
Please adjust `wolfSSL_d2i_X509_fp_ex` and use directly. Its a static local.

2024-01-12 00:05 UTC, dgarske commented on wolfssl/openssl/asn1.h
> +#define ASN1_STRING_new_ex        wolfSSL_ASN1_STRING_new_ex
Does openssl have `ASN1_STRING_new_ex`? I don't think these macros are needed.

2024-01-16 16:44 UTC, jpbland1 commented
Here's the before and after for the size of the dynamic library with --enable-all:
On commit 5631bc9b2:
```
$ size -G /usr/local/lib/libwolfssl.so.42.0.0 
      text       data        bss      total filename
   1396282     772056    1288960    3457298 /usr/local/lib/libwolfssl.so.42.0.0
```
On latest of this branch:
```
$ size -G /usr/local/lib/libwolfssl.so.42.0.0 
      text       data        bss      total filename
   1398410     776322    1288960    3463692 /usr/local/lib/libwolfssl.so.42.0.0
```
So these changes add about 6.3k, might not be worth it if customers don't need the heap hint for these functions but I didn't want to do a half measure and have to come back and add more functions when a customer does ask for them.

As for testing with `WOLFSSL_HEAP_TEST`, it seems to be broken and doesn't build unless I configure with 
````
./configure --enable-crl --disable-ecc CFLAGS='-DWOLFSSL_HEAP_TEST'
```
And it passes make check.

2024-01-16 16:44 UTC, jpbland1 commented
please retest this

2024-01-16 17:02 UTC, jpbland1 commented
retest this please

2024-01-16 18:36 UTC, dgarske commented
> Here's the before and after for the size of the dynamic library with --enable-all: On commit [5631bc9](https://github.com/wolfSSL/wolfssl/commit/5631bc9b2d4104aafa34bc956462edea52281812):
> 
> ```
> $ size -G /usr/local/lib/libwolfssl.so.42.0.0 
>       text       data        bss      total filename
>    1396282     772056    1288960    3457298 /usr/local/lib/libwolfssl.so.42.0.0
> ```
> 
> On latest of this branch:
> 
> ```
> $ size -G /usr/local/lib/libwolfssl.so.42.0.0 
>       text       data        bss      total filename
>    1398410     776322    1288960    3463692 /usr/local/lib/libwolfssl.so.42.0.0
> ```
> 
> So these changes add about 6.3k, might not be worth it if customers don't need the heap hint for these functions but I didn't want to do a half measure and have to come back and add more functions when a customer does ask for them.
> 
> As for testing with `WOLFSSL_HEAP_TEST`, it seems to be broken and doesn't build unless I configure with
> 
> ```
> ./configure --enable-crl --disable-ecc CFLAGS='-DWOLFSSL_HEAP_TEST'
> ```
> And it passes make check.
> ```

I think my biggest concern is our `--enable-opensslextra=x509small` or `OPENSSL_EXTRA_X509_SMALL`. We've got a few customers that cannot tolerate code size growth with this.
@JacobBarthelmeh thoughts on this PR and possible code size increase and how to mitigate it?

2024-01-16 19:46 UTC, jpbland1 commented
It looks like a dtls test failed, having trouble reproducing, lets see if it's just the test
retest this please

2024-01-16 21:57 UTC, jpbland1 commented
With ./configure --enable-all --enable-opensslextra=x509small
On commit 5631bc9:
```
$ size -G /usr/local/lib/libwolfssl.so.42.0.0 
      text       data        bss      total filename
   1396282     772120    1288960    3457362 /usr/local/lib/libwolfssl.so.42.0.0
```
On latest of this branch:
```
$ size -G /usr/local/lib/libwolfssl.so.42.0.0 
      text       data        bss      total filename
   1398410     776386    1288960    3463756 /usr/local/lib/libwolfssl.so.42.0.0
```
So it's still a 6.3k change.

2024-01-17 00:06 UTC, JacobBarthelmeh reviewed
This PR would solve for a specific use case. Would it make sense to add a catch all heap hint? Something along the lines of wolfSSL_SetDefaultHeapHint(void* heap). For cases where a heap hint tied to a specific WOLFSSL_CTX is not a concern and a generic memory pool is registered for catching incoming XMALLOC's with NULL heap hint pointers. Then on XFREE if a generic heap hint has been registered and the heap hint passed to XFREE is NULL it would compare the incoming pointer with the memory buckets in the registered heap hint to free it back to the memory pool. Was thinking of this while reviewing this PR. It would be nice to solve all the potential compatibility layer cases at once.

2024-01-19 16:41 UTC, closed without merging