Allow for critical extensions early.
wolfSSL/wolfssl pull request #7163
Opened 2024-01-23 16:55 UTC by anhu

Later another check will be done, but that one can be overridden with custom extension handler. 
Fixes ZD17329

2024-01-24 17:01 UTC, anhu commented
Retest this please.

2024-01-24 18:44 UTC, JacobBarthelmeh submitted a review, later dismissed
~~This will potentially overwrite 'ret' with a success value in the case that the CRL check succeeds and loose the ASN_CRIT_EXT_E value.~~
Resolved

2024-01-25 19:46 UTC, julek-wolfssl requested changes
I am not a fan of this approach to the customer's problem. They should register custom callbacks for custom extensions. The `cert` structure is left in an incomplete state too (but it should always be enough if it fails on the extensions).

2024-01-29 23:00 UTC, dgarske commented
Retest this please

2024-01-29 23:19 UTC, bandi13 commented
Retest this please

2024-01-31 19:21 UTC, anhu commented
Spoke with customer and came up with alternative solution. This is NOT the approach we will be taking.

2024-01-31 19:21 UTC, closed without merging