BIO_BIO: BIO_{write|read} on a BIO pair should wrap around ring buffer
wolfSSL/wolfssl pull request #7169
Opened 2024-01-24 11:41 UTC by julek-wolfssl

2024-01-24 17:11 UTC, JacobBarthelmeh requested changes

2024-01-25 10:25 UTC, julek-wolfssl commented on tests/api.c
> +    ExpectIntEQ(BIO_read(bio1, tmp, 20), 0);
Very good catch. Fixing and trying to line up the return codes more with what openssl is returning.

2024-01-25 14:45 UTC, julek-wolfssl commented
Retest this please

2024-01-25 20:08 UTC, JacobBarthelmeh approved these changes

2024-01-25 20:08 UTC, merged