IoT-Safe sha384+sha512 support
wolfSSL/wolfssl pull request #7176
Opened 2024-01-26 09:28 UTC by danielinux

# Description

Add SHA384 and SHA512 support by removing hardcoded digest size.

Should fix github reported issue #7175 

# Testing

via #7175 

# Checklist

 - [ ] added tests
 - [x] updated/added doxygen
 - [x] updated appropriate READMEs (no update needed)
 - [x] Updated manual and documentation (no update needed)

2024-01-26 15:28 UTC, dgarske requested changes

2024-01-26 15:28 UTC, dgarske commented on wolfcrypt/src/port/iotsafe/iotsafe.c
> +#ifdef WOLFSSL_TLS13_SHA512
Should this be WOLFSSL_SHA512?

2024-01-29 11:22 UTC, danielinux commented
Confirmed working with SHA384 in #7175 . Moving to "Ready to review".

2024-01-29 15:35 UTC, dgarske approved these changes

2024-01-29 15:35 UTC, merged