Adding unknown extension callback to CertManager
wolfSSL/wolfssl pull request #7194
Opened 2024-01-31 21:34 UTC by anhu

2024-02-01 18:20 UTC, dgarske commented
Failing most tests with:

```
In file included from wolfcrypt/src/asn.c:200:
./wolfssl/internal.h:2635:5: error: unknown type name ‘wc_UnknownExtCallback’
 2635 |     wc_UnknownExtCallback unknownExtCallback;
      |     ^~~~~~~~~~~~~~~~~~~~~
```

2024-02-05 20:08 UTC, bandi13 commented
retest this please

2024-02-06 18:54 UTC, dgarske requested changes
This is a great addition. Please add a test case

2024-02-07 22:18 UTC, dgarske approved these changes

2024-02-08 12:10 UTC, SparkiDev approved these changes

2024-02-08 12:10 UTC, merged