Template for TLS v1.2 only
wolfSSL/wolfssl pull request #7198
Opened 2024-02-01 16:09 UTC by dgarske

# Description

Template for TLS v1.2 only

# Testing

```
./configure --enable-usersettings --disable-examples
make
./wolfcrypt/test/testwolfcrypt
```

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2024-02-02 19:58 UTC, douzzer requested changes
works for me -- just suggested a couple non-functional tweaks.

2024-02-02 19:58 UTC, douzzer commented on examples/configs/user_settings_tls12.h
> + */
should add the build+test instructions here.  from the PR comments:
```
./configure --enable-usersettings --disable-examples
make
./wolfcrypt/test/testwolfcrypt
```

2024-02-02 19:58 UTC, douzzer commented on examples/configs/user_settings_tls12.h
> +#define WOLFSSL_USER_IO /* Use the SetIO callbacks, not the internal wolfio.c socket code */
line length

2024-02-03 21:19 UTC, dgarske commented
Retest this please

2024-02-05 21:14 UTC, douzzer approved these changes

2024-02-05 21:14 UTC, merged