EdDsa: check private value after sign
wolfSSL/wolfssl pull request #7212
Opened 2024-02-04 22:46 UTC by SparkiDev

# Description

Check the private value hasn't changed during signing with EdDSA.

Fixes zd#17438

# Testing

./configure '--disable-shared' '--enable-curve25519' '--enable-ed25519' '--enable-curve448' '--enable-ed448' 'CFLAGS=-DWOLFSSL_EDDSA_CHECK_PRIV'

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2024-02-12 23:22 UTC, dgarske requested changes
Please document `WOLFSSL_EDDSA_CHECK_PRIV_ON_SIGN`.

2024-02-13 13:22 UTC, SparkiDev commented
retest this please

2024-02-13 13:34 UTC, SparkiDev commented
Added comments at top of ed25519.c and ed448.c.

2024-02-13 17:27 UTC, dgarske approved these changes

2024-02-13 17:27 UTC, merged