IO callbacks for content and output with PKCS7 bundle sign/encrypt
wolfSSL/wolfssl pull request #7272
Opened 2024-02-26 16:49 UTC by JacobBarthelmeh

Caps encrypting/signing content to around 26k of heap when used, instead of the full file size.

Examples for use are here (https://github.com/wolfSSL/wolfssl-examples/pull/425).

2024-03-05 09:30 UTC, JacobBarthelmeh commented
Retest this please Jenkins

2024-03-07 02:23 UTC, SparkiDev requested changes

2024-03-07 02:23 UTC, SparkiDev commented on wolfcrypt/src/pkcs7.c
> +            if (buf == NULL) {
Only applicable when using the callback.

2024-03-07 02:23 UTC, SparkiDev commented on wolfcrypt/src/pkcs7.c
> +                if (pkcs7->encodeStream) {
This looks like it will always be true.

2024-03-07 02:23 UTC, SparkiDev commented on wolfcrypt/src/pkcs7.c
> +        switch (cipherType) {
This looks the same as in the loop except for the length being idx instead of BER_OCTET_LENGTH.
Extract out as a new function.

2024-03-07 02:23 UTC, SparkiDev commented on wolfcrypt/src/pkcs7.c
> +        if (pkcs7->encodeStream) {
This looks like it is always true as well.

2024-03-07 02:23 UTC, SparkiDev commented on wolfcrypt/src/pkcs7.c
> +            #ifdef WOLFSSL_ASYNC_CRYPT
ret is not checked from above.

2024-03-07 02:23 UTC, SparkiDev commented on wolfcrypt/src/pkcs7.c
> +    #ifdef WOLFSSL_ASYNC_CRYPT
ret is not checked from above.

2024-03-07 02:23 UTC, SparkiDev commented on wolfcrypt/src/pkcs7.c
> +        WOLFSSL_MSG("No provided way to output bundle");
"No way provided ..."

2024-03-07 21:18 UTC, SparkiDev approved these changes

2024-03-07 21:18 UTC, merged