Allow to enable DES3 support without the DES3 ciphers
wolfSSL/wolfssl pull request #7315
Opened 2024-03-09 12:01 UTC by fabiankeil

DES3 support is required to use PBES2-3DES-CBC-encoded keys but also enabling the DES3 ciphers may be undesirable. When using Privoxy it results in a "Bad" rating at sites like https://www.howsmyssl.com/ due to the Sweet32 attack.

2024-03-11 14:54 UTC, dgarske commented
Okay to test

2024-03-11 20:07 UTC, ejohnstown submitted a review, later dismissed

2024-03-11 21:17 UTC, dgarske submitted a review, later dismissed
Thank you @fabiankeil for this change. I am marking it approved, but awaiting some additional feedback before I merge.

2024-03-13 21:50 UTC, dgarske commented
@douzzer you mentioned wanting this in enable-all, however that is also used for the distro build. Any suggestions?

2024-03-13 22:47 UTC, douzzer requested changes
This is an excellent change!

I requested a global name change for the new option/variables/macros for clarity.

Thanks!

2024-03-13 22:47 UTC, douzzer commented on configure.ac
> +AC_ARG_ENABLE([des3-ciphers],
To avoid confusion, we need the new option to have "tls" in its name.  I suggest `--enable-des3-tls-suites`.

2024-03-13 22:47 UTC, douzzer commented on configure.ac
> +    [ ENABLED_DES3_CIPHERS=$enableval ],
similarly this should be `ENABLED_DES3_TLS_SUITES`.

2024-03-13 22:47 UTC, douzzer commented on configure.ac
> +    AM_CFLAGS="$AM_CFLAGS -DNO_DES3_CIPHERS"
and similarly, this should be `-DNO_DES3_TLS_SUITES`.

2024-03-13 22:47 UTC, douzzer commented on configure.ac
> +        [AC_MSG_ERROR([DES3 ciphers require DES3])])
fix message to something like "DES3 TLS cipher suites require --enable-des3".

2024-03-13 22:47 UTC, douzzer commented on wolfssl/internal.h
> +    #if !defined(NO_RSA) && !defined(NO_DES3) && !defined(NO_DES3_CIPHERS)
fix macro as above.

2024-03-13 22:47 UTC, douzzer commented on wolfssl/internal.h
> +            #if !defined(NO_DES3) && !defined(NO_DES3_CIPHERS)
fix macro as above.

2024-03-13 22:47 UTC, douzzer commented on wolfssl/internal.h
> +            !defined(NO_DES3_CIPHERS)
fix macro as above.

2024-03-13 22:47 UTC, douzzer commented on configure.ac
> +if test "x$ENABLED_DES3_CIPHERS" = "xno"
fix var name as above.

2024-03-13 22:54 UTC, douzzer commented
> @douzzer you mentioned wanting this in enable-all, however that is also used for the distro build. Any suggestions?

We're good keeping DES3 in wolfCrypt with `enable-all` and `enable-all-crypto` builds, but indeed neither of those should enable DES3 for TLS suites.  By splitting the difference, we can have our cake (banish DES3 from the TLS suites, with all the accolades that brings) and eat it too (applications that depend directlly on wolfCrypt low level DES3 APIs still work with the distro build).

2024-03-14 17:35 UTC, dgarske commented
@douzzer please take another pass. I went ahead and made those cleanups.

2024-03-14 19:49 UTC, douzzer approved these changes
LGTM

2024-03-14 20:20 UTC, JacobBarthelmeh commented
Placing a note in the upcoming release that future releases will by default turn off DES3 TLS cipher suites even when --enable-des3 is used. (at the moment DES3 is off by default). This explicit --enable flag will need to be set to re-enable DES3 cipher suites.

2024-03-28 18:41 UTC, douzzer commented
retest this please.

2024-03-28 20:13 UTC, douzzer requested changes
@fabiankeil can you cook up equivalent logic for `CMakeLists.txt`?  We're thinking the autotools and cmake defaults should track each other.

i.e. `CMakeLists.txt` should have a `list(APPEND WOLFSSL_DEFINITIONS "-DNO_DES3_TLS_SUITES")` unless cmake option `-DDES3_TLS_SUITES` is passed in.

2024-04-02 23:44 UTC, JacobBarthelmeh approved these changes

2024-04-02 23:48 UTC, merged