make "yes;no" cmake options boolean instead of string
wolfSSL/wolfssl pull request #7380
Opened 2024-04-01 14:23 UTC by oltolm

# Description

Please describe the scope of the fix or feature addition.

Fixes https://github.com/wolfSSL/wolfssl/issues/5438

`add_option` in `functions.cmake` always produces variables of type string even for boolean options. I fixed it to produce boolean variables for options that only allow "yes;no".

2024-04-01 15:14 UTC, dgarske commented
Okay to test. Contributor agreement on file. Thank you @oltolm . Changes look great!

2024-04-01 17:15 UTC, dgarske commented
Retest this please

2024-05-15 16:49 UTC, dgarske requested changes
I like this change, but I think it requires some additional changes in the CMakeList.txt. For example after this change many of the options change to OFF/ON, but some are still yes/no.

Current master:
```
WOLFSSL_16BIT                    no
WOLFSSL_32BIT                    no
WOLFSSL_AES                      yes
WOLFSSL_AESCBC                   yes
WOLFSSL_AESCCM                   no
WOLFSSL_AESCFB                   no
WOLFSSL_AESCTR                   no
WOLFSSL_AESGCM                   yes
WOLFSSL_AESKEYWRAP               no
WOLFSSL_AESOFB                   no
WOLFSSL_AESSIV                   no
WOLFSSL_ALIGN_DATA               yes
WOLFSSL_ALPN                     no
WOLFSSL_ALT_CERT_CHAINS          no
WOLFSSL_ARC4                     no
WOLFSSL_ARIA                     no
WOLFSSL_ASIO                     no
WOLFSSL_ASM                      yes
WOLFSSL_ASN                      yes
WOLFSSL_ASYNC_THREADS            no
WOLFSSL_BASE64_ENCODE            yes
WOLFSSL_BUILD_OUT_OF_TREE        yes
WOLFSSL_CAAM                     no
WOLFSSL_CERTEXT                  no
WOLFSSL_CERTGEN                  no
WOLFSSL_CERTGENCACHE             no
WOLFSSL_CERTREQ                  no
WOLFSSL_CHACHA                   yes
...
```

Your PR 7380:
```
WOLFSSL_16BIT                    OFF
WOLFSSL_32BIT                    OFF
WOLFSSL_AES                      ON
WOLFSSL_AESCBC                   ON
WOLFSSL_AESCCM                   OFF
WOLFSSL_AESCFB                   OFF
WOLFSSL_AESCTR                   OFF
WOLFSSL_AESGCM                   yes
WOLFSSL_AESKEYWRAP               OFF
WOLFSSL_AESOFB                   OFF
WOLFSSL_AESSIV                   OFF
WOLFSSL_ALIGN_DATA               ON
WOLFSSL_ALPN                     OFF
WOLFSSL_ALT_CERT_CHAINS          OFF
WOLFSSL_ARC4                     OFF
WOLFSSL_ARIA                     OFF
WOLFSSL_ASIO                     OFF
WOLFSSL_ASM                      ON
WOLFSSL_ASN                      ON
WOLFSSL_ASYNC_THREADS            OFF
WOLFSSL_BASE64_ENCODE            ON
WOLFSSL_BUILD_OUT_OF_TREE        ON
WOLFSSL_CAAM                     OFF
WOLFSSL_CERTEXT                  OFF
WOLFSSL_CERTGEN                  OFF
WOLFSSL_CERTGENCACHE             OFF
WOLFSSL_CERTREQ                  OFF
WOLFSSL_CHACHA                   yes
...
```

2024-05-15 21:38 UTC, oltolm commented
Those options that are still "yes" or "no" are not boolean. For example `WOLFSSL_AESGCM` is defined like this

```
add_option("WOLFSSL_AESGCM"
    "Enable wolfSSL AES-GCM support (default: enabled)"
    "yes" "yes;no;table;small;word32;4bit")
```

As you can see it's not a boolean option.

2024-05-15 21:44 UTC, dgarske commented
> Those options that are still "yes" or "no" are not boolean. For example `WOLFSSL_AESGCM` is defined like this
> 
> ```
> add_option("WOLFSSL_AESGCM"
>     "Enable wolfSSL AES-GCM support (default: enabled)"
>     "yes" "yes;no;table;small;word32;4bit")
> ```
> 
> As you can see it's not a boolean option.

That makes sense. I like the change. Does this change to use boolean fix an issue or is it more to improve your experience when building with CMake?

2024-05-15 21:44 UTC, dgarske approved these changes

2024-05-15 22:15 UTC, oltolm commented
> > Those options that are still "yes" or "no" are not boolean. For example `WOLFSSL_AESGCM` is defined like this
> > ```
> > add_option("WOLFSSL_AESGCM"
> >     "Enable wolfSSL AES-GCM support (default: enabled)"
> >     "yes" "yes;no;table;small;word32;4bit")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > As you can see it's not a boolean option.
> 
> That makes sense. I like the change. Does this change to use boolean fix an issue or is it more to improve your experience when building with CMake?

I remember having some kind of problem, but I couldn't reproduce it. It's just a general improvement. The CMake GUI now shows a checkbox instead of a dropdown for boolean options.

2024-05-15 22:18 UTC, merged