Adding stubs required for latest nginx
wolfSSL/wolfssl pull request #7449
Opened 2024-04-18 19:32 UTC by lealem47

# Description

Adding stubs required for latest nginx (1.25.5)

# Testing

nginx unit tests

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2024-04-18 21:25 UTC, julek-wolfssl requested changes

2024-04-18 21:25 UTC, julek-wolfssl commented on src/conf.c
> +#if defined(WOLFSSL_NGINX)
I don't like osp specific gating. Put it in ossl all or leave it in extra with no gating.

2024-04-19 13:04 UTC, julek-wolfssl approved these changes

2024-04-19 13:25 UTC, julek-wolfssl commented
You also need to add the version to `nginx.yml` once the patch get merged to wolfssl-nginx.

2024-04-19 14:44 UTC, lealem47 commented
> You also need to add the version to `nginx.yml` once the patch get merged to wolfssl-nginx.

There is no new patch, the patch for 1.25.0 was sufficient to get things building & tests passing

2024-04-19 14:45 UTC, lealem47 commented
Retest this please

2024-04-19 16:38 UTC, JacobBarthelmeh approved these changes

2024-04-19 16:38 UTC, merged