configure.ac: Add --enable-dtls13 to --enable-all
wolfSSL/wolfssl pull request #7456
Opened 2024-04-20 15:34 UTC by mrdeep1

# Description

By default DTLS1.3 is not enabled, but now is enabled when --enable-dtls13, --enable-all or --enable-dist is used.

For --enable-all or --enable-dist, DTLS1.3 options --enable-dtlscid and --enable-dtls-frag-ch are also enabled.

Fixed issue reported by scan-build when DTLS13 is enabled.

Fix compile issue when WOLFSSL_DTLS_CH_FRAG is enabled.

# Testing

Running `./configure --enable-all` and reviewed `AM_FLAGS `in `Makefile `as well as running `scan-build make`.

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2024-04-22 00:35 UTC, SparkiDev approved these changes

2024-04-22 10:49 UTC, mrdeep1 commented
Fixed issue with running `scripts/dtlscid.test`.  Code pushed.

2024-04-23 21:54 UTC, SparkiDev requested changes

2024-04-23 21:54 UTC, SparkiDev commented on configure.ac
> +        test "$enable_dtls13" = "" && enable_dtls13=yes
Please remove this from the default build.
We are looking for interoperability targets before making it part of the distribution.

2024-04-25 22:51 UTC, SparkiDev approved these changes

2024-04-25 22:52 UTC, SparkiDev commented on configure.ac
> +        test "$enable_dtls13" = "" && enable_dtls13=yes
Thanks @mrdeep1!
I've approved the code changes.

2024-04-25 23:24 UTC, merged