add global heap hint setter function
wolfSSL/wolfssl pull request #7478
Opened 2024-04-26 14:25 UTC by JacobBarthelmeh

2024-04-26 15:44 UTC, billphipps submitted a review, later dismissed

2024-04-30 22:40 UTC, JacobBarthelmeh commented on examples/client/client.c
> +    /* for test case (does not handle all memory used on default build)
The comment is about heap memory size but it also has the issue of some of our tests being threaded and using the global heap hint in other tests. Removed the reference here and we now just have the test in wolfcrypt/test/test.c.

2024-04-30 22:41 UTC, JacobBarthelmeh commented on wolfcrypt/src/memory.c
> +            hint = (WOLFSSL_HEAP_HINT*)globalHeapHint;
Added in a debug print out

2024-04-30 22:41 UTC, JacobBarthelmeh commented on wolfssl/wolfcrypt/memory.h
> +    WOLFSSL_API void wolfSSL_SetGlobalHeapHint(void* heap);
Updated

2024-05-06 20:49 UTC, billphipps approved these changes

2024-05-15 16:23 UTC, dgarske requested changes
This PR is great. What's holding it up?

2024-05-15 16:23 UTC, dgarske commented on wolfcrypt/src/memory.c
> +void* wolfSSL_GetGlobalHeapHint()
`(void)`.

2024-05-15 17:01 UTC, JacobBarthelmeh commented
Restest this please Jenkins

2024-05-15 17:14 UTC, JacobBarthelmeh commented
I don't like that a retest needed done. Will need to keep an eye out for if the tests are having a threading issue with the setting of the global heap hint (is why I limited the set global heap hint test).

2024-05-15 17:41 UTC, dgarske approved these changes
@JacobBarthelmeh please make sure the static memory / user manual adds a few lines about these new APIs. Very handy addition.

2024-05-15 17:43 UTC, merged