Add user threading macro definition
wolfSSL/wolfssl pull request #7509
Opened 2024-05-07 22:15 UTC by miyazakh

# Description
Allow user specific return values for threading methods

Fixes zd#17887

# Testing

Confirmed patch by the customer

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2024-05-07 23:06 UTC, miyazakh commented
retest this please

2024-05-08 08:17 UTC, julek-wolfssl requested changes

2024-05-08 08:17 UTC, julek-wolfssl commented on wolfssl/wolfcrypt/types.h
> +         * wolfSSL_JoinThread() and CND(s) if want.
```suggestion
         * User can also implement their own wolfSSL_NewThread(),
         * wolfSSL_JoinThread() and wolfSSL_Cond signaling if they want.
```

2024-05-08 22:06 UTC, miyazakh commented on wolfssl/wolfcrypt/types.h
> +         * wolfSSL_JoinThread() and CND(s) if want.
Thanks!

2024-05-13 15:22 UTC, julek-wolfssl approved these changes

2024-05-13 16:24 UTC, merged