Avoid flexible arrays on unsupported platforms via a macro.
wolfSSL/wolfssl pull request #7538
Opened 2024-05-15 19:04 UTC by kareem-wolfssl

# Description

Fixes zd#17977

Credit to wolfSentry for the fix

# Testing

Built in tests with --enable-dtlscid --enable-tls13 --enable-tlsx --enable-dtls13 --enable-dtls which should cover all cases

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2024-05-15 19:48 UTC, dgarske requested changes

2024-05-15 19:48 UTC, dgarske commented on wolfssl/internal.h
> +    byte        hashSigAlgo[WOLFSSL_FLEXIBLE_ARRAY_SIZE]; /* sig/algo to offer */
```
[clang-tidy-defaults] [7 of 7] [ac3063c1e8]
    configure...   real 0m18.881s  user 0m5.668s  sys 0m2.801s
    build..../wolfssl/internal.h:3178:29: warning: zero size arrays are an extension [clang-diagnostic-zero-length-array]
byte        hashSigAlgo[WOLFSSL_FLEXIBLE_ARRAY_SIZE]; /* sig/algo to offer */
^
/tmp/workspace/PRB-multi-test-script/wolfssl/./wolfssl/wolfcrypt/wc_port.h:1276:41: note: expanded from macro 'WOLFSSL_FLEXIBLE_ARRAY_SIZE'
#define WOLFSSL_FLEXIBLE_ARRAY_SIZE 0
^
./wolfssl/internal.h:3356:17: warning: zero size arrays are an extension [clang-diagnostic-zero-length-array]
byte   data[WOLFSSL_FLEXIBLE_ARRAY_SIZE];
^
/tmp/workspace/PRB-multi-test-script/wolfssl/./wolfssl/wolfcrypt/wc_port.h:1276:41: note: expanded from macro 'WOLFSSL_FLEXIBLE_ARRAY_SIZE'
#define WOLFSSL_FLEXIBLE_ARRAY_SIZE 0
^
./wolfssl/internal.h:5216:14: warning: zero size arrays are an extension [clang-diagnostic-zero-length-array]
byte buf[WOLFSSL_FLEXIBLE_ARRAY_SIZE];
^
/tmp/workspace/PRB-multi-test-script/wolfssl/./wolfssl/wolfcrypt/wc_port.h:1276:41: note: expanded from macro 'WOLFSSL_FLEXIBLE_ARRAY_SIZE'
#define WOLFSSL_FLEXIBLE_ARRAY_SIZE 0
^
make[2]: *** [Makefile:7277: wolfcrypt/src/src_libwolfssl_la-asn.lo] Error 1
make[1]: *** [Makefile:8414: all-recursive] Error 1
make: *** [Makefile:5059: all] Error 2
   real 2m34.598s  user 2m0.813s  sys 0m2.866s
    clang-tidy-defaults fail_analytic_build
    failed config: 'CPPFLAGS=-DKEEP_OUR_CERT -DKEEP_PEER_CERT -DWOLFSSL_ALT_NAMES -DNO_WOLFSSL_CIPHER_SUITE_TEST -DWOLFSSL_OLD_PRIME_CHECK -pedantic -DSP_ALLOC -DWOLFSSL_CLANG_TIDY' 'CC=/tmp/workspace/PRB-multi-test-script/testing/git-hooks/clang-tidy-builder.sh' 'CLANG=/usr/lib/llvm-14/bin/clang-14' 'CFLAGS=-Wunreachable-code-aggressive -Wthread-safety -Wloop-analysis -Wenum-compare-conditional -fcolor-diagnostics -fcomplete-member-pointers -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -g -fdebug-types-section -Wunreachable-code-break -Wunreachable-code-return -Wimplicit-fallthrough'
final tally: 6 of 7 checks succeeded, 0 skipped, 0 forced, and 1 failed, for ac3063c1e8.
exiting with status 2
```

2024-11-16 00:18 UTC, douzzer requested changes
sync with latest from wolfSentry.

2024-11-16 00:18 UTC, douzzer commented on wolfssl/wolfcrypt/wc_port.h
> +
The latest setup from wolfSentry has more subtleties.

See https://github.com/wolfSSL/wolfsentry/blob/46af28fcfc7556a4db08b7a0f14068e5ab645413/wolfsentry/wolfsentry_settings.h#L327

2026-08-13 00:49 UTC, kareem-wolfssl commented
Superseded by https://github.com/wolfSSL/wolfssl/pull/10858 which has been merged.  Closing.

2026-08-13 00:49 UTC, closed without merging