Add enable provider
wolfSSL/wolfssl pull request #7550
Opened 2024-05-16 20:40 UTC by bandi13

Cleaned up how ECC_MIN_SZ gets set. Added in '--enable-wolfprovider' option.

2024-05-21 20:28 UTC, bandi13 commented
retest this please

2024-07-12 23:27 UTC, douzzer requested changes
nice catch on the FIPS eccminsz!

2024-07-12 23:27 UTC, douzzer commented on configure.ac
> +    with_max_ecc_bits=1024
These should be conditional on the user not supplying an override value to configure.  E.g.
```
    test -z "$enable_all_crypto" && enable_all_crypto=yes
```
Notice that `--enable-all`, `--enable-all-crypto`, and even FIPS `dev` or `v5-dev`, use similar logic to allow tailoring and testing of different feature combinations.  It's understood that some combinations won't work -- if the user forces something, they own the consequences.

2024-07-15 17:07 UTC, douzzer approved these changes

2024-07-15 17:08 UTC, merged