Add settings.h check: DSA needs SHA1
wolfSSL/wolfssl pull request #7551
Opened 2024-05-16 23:06 UTC by gojimmypi

# Description

Adds a `settings.h` sanity check to ensure if DSA is enabled, that SHA1 is also enabled.

I started going down the road of gating out *all* the DSA code when not enabled, but the further I got, the more complex it became. I gave up when I found [MakeAnyCert()](https://github.com/wolfSSL/wolfssl/blob/219a338107b3e60d4a360dca960542dc89b616d1/wolfcrypt/src/asn.c#L29995) that has a DSA parameter. It is certainly _possible_ to code around this, and I can do so if desired. For now we have the sanity check,

Otherwise, without this change: when DSA is enabled and SHA1 is disabled (e.g. `#define NO_SHA`) , unintuitive compile time errors may occur such as this:

```
C:/workspace/wolfssl-gojimmypi-pr/wolfcrypt/src/dsa.c: In function 'wc_DsaSign':
C:/workspace/wolfssl-gojimmypi-pr/wolfcrypt/src/dsa.c:653:34: error: 'WC_SHA_DIGEST_SIZE' undeclared (first use in this function); did you mean 'WC_SHA384_DIGEST_SIZE'?
  653 |     return wc_DsaSign_ex(digest, WC_SHA_DIGEST_SIZE, out, key, rng);
      |                                  ^~~~~~~~~~~~~~~~~~
      |                                  WC_SHA384_DIGEST_SIZE
C:/workspace/wolfssl-gojimmypi-pr/wolfcrypt/src/dsa.c:653:34: note: each undeclared identifier is reported only once for each function it appears in
C:/workspace/wolfssl-gojimmypi-pr/wolfcrypt/src/dsa.c: In function 'wc_DsaVerify':
C:/workspace/wolfssl-gojimmypi-pr/wolfcrypt/src/dsa.c:988:36: error: 'WC_SHA_DIGEST_SIZE' undeclared (first use in this function); did you mean 'WC_SHA384_DIGEST_SIZE'?
  988 |     return wc_DsaVerify_ex(digest, WC_SHA_DIGEST_SIZE, sig, key, answer);
      |                                    ^~~~~~~~~~~~~~~~~~
      |                                    WC_SHA384_DIGEST_SIZE
C:/workspace/wolfssl-gojimmypi-pr/wolfcrypt/src/dsa.c: In function 'wc_DsaSign':
C:/workspace/wolfssl-gojimmypi-pr/wolfcrypt/src/dsa.c:654:1: error: control reaches end of non-void function [-Werror=return-type]
  654 | }
      | ^
C:/workspace/wolfssl-gojimmypi-pr/wolfcrypt/src/dsa.c: In function 'wc_DsaVerify':
C:/workspace/wolfssl-gojimmypi-pr/wolfcrypt/src/dsa.c:989:1: error: control reaches end of non-void function [-Werror=return-type]
  989 | }
      | ^
```

Fixes zd# n/a

# Testing

Limited testing only with embedded target. 

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2024-05-17 14:07 UTC, dgarske requested changes

2024-05-17 14:07 UTC, dgarske commented on wolfssl/wolfcrypt/settings.h
> +#if defined(HAVE_DSA) || !defined(NO_DSA)
HAVE_DSA isn't really a thing... we don't use it.

```
./configure --enable-dsa --disable-sha && make
configure: error: please disable DSA if disabling SHA-1.
```

Would prefer simple the following:

```
#if !defined(NO_DSA) && !defined(NO_SHA)
    #error "Please disable DSA if disabling SHA-1"
#endif
```

2024-05-20 16:41 UTC, dgarske approved these changes

2024-05-20 16:41 UTC, dgarske commented on wolfssl/wolfcrypt/settings.h
> +#if (defined(HAVE_DSA) || !defined(NO_DSA)) && defined(NO_SHA)
Again, `HAVE_DSA` isn't really needed. Just gating on `!defined(NO_DSA)` should be enough. And yes I had a typo in my example `!defined(NO_SHA)` -> `defined(NO_SHA)`.

2024-05-20 23:11 UTC, gojimmypi commented
Jenkins retest this please

2024-05-21 00:04 UTC, dgarske requested changes

2024-05-21 00:04 UTC, dgarske commented on wolfssl/wolfcrypt/settings.h
> +#if (!defined(NO_DSA)) && defined(NO_SHA)
Nit: `#if !defined(NO_DSA) && defined(NO_SHA)`

2024-05-21 01:02 UTC, gojimmypi commented on wolfssl/wolfcrypt/settings.h
> +#if (!defined(NO_DSA)) && defined(NO_SHA)
Agreed. Oversight on my part.

2024-05-21 10:44 UTC, gojimmypi commented
Jenkins retest this please

2024-05-21 15:34 UTC, dgarske commented
Retest this please

2024-05-21 15:46 UTC, dgarske approved these changes

2024-05-21 15:47 UTC, merged