Add option for using a custom salt for ourselves
wolfSSL/wolfssl pull request #7552
Opened 2024-05-17 15:16 UTC by dgarske

# Description

Add option for using a custom salt for ourselves. 
TODO: Add test

ZD 17988

# Testing

```
./configure --enable-eccencrypt && make
```

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2024-05-19 22:26 UTC, SparkiDev requested changes

2024-05-19 22:26 UTC, SparkiDev commented on wolfcrypt/src/ecc.c
> + * @param  [in]       sz    Length of salt in bytes.
Parameter is 'len'.
Change it back or change the name of the parameter to the function.

2024-05-19 22:26 UTC, SparkiDev commented
New function looks good to me.

2024-05-20 15:29 UTC, dgarske commented
Retest this please

2024-05-20 16:19 UTC, dgarske commented
Retest this please

2024-05-20 23:18 UTC, SparkiDev approved these changes

2024-05-20 23:19 UTC, merged