20240522-sha256-avx1-IS_INTEL_SHA
wolfSSL/wolfssl pull request #7572
Opened 2024-05-22 19:38 UTC by douzzer

`wolfcrypt/src/sha256.c`: in `InitSha256()`, don't activate `Transform_Sha256_AVX1` unless both AVX1 and SHA ISA intrinsics are available.  on targets with AVX1 and RORX but without SHA instructions, fall back to `Transform_Sha256_AVX1_RORX`.

tested with `wolfssl-multi-test.sh ... super-quick-check`

2024-05-22 19:54 UTC, douzzer commented
note, these are the implementations that use the SHA hardware instructions:
```
$ awk 'BEGIN{printed=0;}/^\.type[      ]+[^,]+,@function/{curfunc=$0;printed=0;next}/^[        ]*sha/{if (! printed){print curfunc; printed=1}}' < wolfcrypt/src/sha256_asm.S 
.type   Transform_Sha256_SSE2_Sha,@function
.type   Transform_Sha256_SSE2_Sha_Len,@function
.type   Transform_Sha256_AVX1_Sha,@function
.type   Transform_Sha256_AVX1_Sha_Len,@function
```
` Sha256_SetTransform()` already had the SSE2 implementation correctly dependent on `IS_INTEL_SHA(intel_flags)`.  With this patch, the AVX1 implementation is similarly dependent.

2024-05-22 20:27 UTC, bandi13 requested changes
This is not really a fix. Transform_Sha256_AVX1 is eliminated from ever being called.

2024-05-22 21:09 UTC, douzzer commented
retest this please

2024-05-22 23:07 UTC, SparkiDev approved these changes

2024-05-23 02:56 UTC, bandi13 approved these changes

2024-05-23 12:37 UTC, merged