Allow user to send a user_canceled alert
wolfSSL/wolfssl pull request #7590
Opened 2024-05-28 13:27 UTC by julek-wolfssl

2024-05-28 15:47 UTC, dgarske requested changes

2024-06-05 09:07 UTC, julek-wolfssl commented on tests/api.c
> +        ExpectIntEQ(wolfSSL_negotiate(ssl_c), -1);
Doesn't look like it from the tests. The `WANT_READ` was from the second alert being discarded due to the sequence number not being incremented. Fixed now.

2024-06-05 15:43 UTC, dgarske approved these changes

2024-06-05 16:07 UTC, JacobBarthelmeh approved these changes

2024-06-05 16:08 UTC, merged