Updating socat version support
wolfSSL/wolfssl pull request #7594
Opened 2024-05-29 19:03 UTC by JacobBarthelmeh

ZD 18009

2024-05-29 19:06 UTC, JacobBarthelmeh commented
Working on going through socat's `make test` results after the update.

2024-06-10 14:01 UTC, julek-wolfssl requested changes

2024-06-10 14:01 UTC, julek-wolfssl commented on tests/api.c
> +
Just use `ExpectIntEQ` directly here and pass in `NULL`.

2024-06-10 14:49 UTC, julek-wolfssl commented
Obviously would be good to add CI for this.

2024-06-13 17:04 UTC, julek-wolfssl requested changes

2024-06-18 16:42 UTC, JacobBarthelmeh commented
Retest this please Jenkins

2024-06-19 15:07 UTC, julek-wolfssl approved these changes

2024-06-20 16:17 UTC, dgarske approved these changes

2024-06-20 16:17 UTC, merged