Rewrite pattern matching to use explicit length
wolfSSL/wolfssl pull request #7604
Opened 2024-05-30 22:40 UTC by ColtonWilley

# Description
Rewrite pattern matching to always use explicit lengths instead of expecting NULL terminated strings, thus replicating the behavior of openssl X509_check_host(). This rewrite fixes a buffer overread of size 1 to read the NULL terminator, in addition to fixing the issue of some strings matching or not matching incorrectly.

Fixes ZD 17987 which was only partially fixed by PR#7534.

# Checklist

 - [X ] added tests

2024-05-30 22:47 UTC, dgarske requested changes
Really nice work!

2024-05-31 03:47 UTC, ColtonWilley commented
Retest this please

2024-05-31 12:55 UTC, dgarske approved these changes

2024-05-31 18:28 UTC, dgarske requested changes
Again, great work on this PR. Nit picks only

2024-05-31 18:28 UTC, dgarske commented on src/x509.c
> +        for (i = 0; i < (chklen > 1 ? chklen - 1 : chklen); i++) {
Consider making `i` a `size_t` to match `chklen`.

2024-05-31 18:28 UTC, dgarske commented on src/internal.c
> +                                (word32)XSTRLEN((const char *)ssl->buffers.domainName.buffer))) == 0)
Check line length. Max 80 chars.

2024-06-03 16:38 UTC, dgarske approved these changes

2024-06-03 19:04 UTC, merged