Import Raw RSA Private Key
wolfSSL/wolfssl pull request #7608
Opened 2024-06-01 06:10 UTC by ejohnstown

# Description

Add API `wc_RsaPrivateKeyDecodeRaw()` for importing an RSA private key when all you have are the components of the key in raw arrays. Also recalculates dP and dQ if missing.

# Testing

Built wolfSSL with `--enable-wolfssh --enable-lowresource`. Tested against a pending build of wolfSSH that uses the new function if available. Tested with and without low resource set.

# Checklist

 - [X] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2024-06-01 14:21 UTC, dgarske requested changes
Nice work. This will sure be handy for wolfSSH

2024-06-01 14:21 UTC, dgarske commented on tests/api.c
> +#if !defined(NO_RSA) && !defined(WOLFSSL_RSA_PUBLIC_ONLY)
Looks like this also needs wrapped with !HAVE_SELFTEST. 

In file included from tests/api.c:152:
tests/api.c: In function ‘test_wc_RsaPrivateKeyDecodeRaw’:
tests/api.c:19733:17: error: implicit declaration of function ‘wc_RsaPrivateKeyDecodeRaw’; did you mean ‘wc_RsaPrivateKeyDecode’? [-Werror=implicit-function-declaration]
19733 |     ExpectIntEQ(wc_RsaPrivateKeyDecodeRaw(&n, sizeof(n),
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~
./tests/unit.h:160:24: note: in definition of macro ‘ExpectInt’
  160 |         int _x = (int)(x);                                                     \
      |                        ^
tests/api.c:19733:5: note: in expansion of macro ‘ExpectIntEQ’
19733 |     ExpectIntEQ(wc_RsaPrivateKeyDecodeRaw(&n, sizeof(n),
      |     ^~~~~~~~~~~
tests/api.c:19733:17: error: nested extern declaration of ‘wc_RsaPrivateKeyDecodeRaw’ [-Werror=nested-externs]
19733 |     ExpectIntEQ(wc_RsaPrivateKeyDecodeRaw(&n, sizeof(n),
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~
./tests/unit.h:160:24: note: in definition of macro ‘ExpectInt’
  160 |         int _x = (int)(x);                                                     \
      |                        ^
tests/api.c:19733:5: note: in expansion of macro ‘ExpectIntEQ’
19733 |     ExpectIntEQ(wc_RsaPrivateKeyDecodeRaw(&n, sizeof(n),
      |     ^~~~~~~~~~~

2024-06-01 23:22 UTC, ejohnstown commented
retest this please

2024-06-02 01:20 UTC, dgarske submitted a review, later dismissed
@SparkiDev please review also. Thank you

2024-06-02 22:32 UTC, SparkiDev requested changes

2024-06-02 22:32 UTC, SparkiDev commented on wolfcrypt/src/rsa.c
> + * Calculate  y = x^(-1) mod d.
This comment doesn't match the code.

2024-06-03 16:13 UTC, dgarske approved these changes

2024-06-03 16:33 UTC, merged