alloc a buff for NULL pointer
wolfSSL/wolfssl pull request #7646
Opened 2024-06-14 23:06 UTC by kojo1

# Description

allocate a buff when *pp is NULL for OpenSSL compatibility
Guarded by WOLFSSL_I2D_ECDSA_SIG_ALLOC for the backward compatibilitiy.

Fixes zd#17695

# Testing

Added the case in test_wolfSSL_ECDSA_SIG

# Checklist

 - [x] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2024-06-17 23:20 UTC, SparkiDev commented on src/pk.c
> +            else if(update_p) {
space after 'if'

2024-06-17 23:26 UTC, SparkiDev requested changes
Minor formatting changes to match rest of file.

2024-06-17 23:26 UTC, SparkiDev commented on src/pk.c
> +            else if(update_p) {
space after 'if'

2024-06-17 23:26 UTC, SparkiDev commented on src/pk.c
> +            if (!*pp) {
*pp != NULL

2024-06-17 23:26 UTC, SparkiDev commented on src/pk.c
> +        if (pp != NULL && *pp == NULL) {
if ((pp != NULL) && (*pp == NULL)) {

2024-06-18 00:40 UTC, kojo1 commented on src/pk.c
> +            if (!*pp) {
fixed

2024-06-18 00:40 UTC, kojo1 commented on src/pk.c
> +            else if(update_p) {
fixed

2024-06-18 00:51 UTC, SparkiDev approved these changes

2024-06-18 01:21 UTC, SparkiDev commented
retest this please

2024-06-18 01:47 UTC, merged