20240614-WOLFSSL_MSG-code-points
wolfSSL/wolfssl pull request #7647
Opened 2024-06-15 06:03 UTC by douzzer

add `--debug-code-points` and `WOLFSSL_DEBUG_CODEPOINTS`,

add `file_name` and `line_number` args to `wolfssl_log()`,

and inside `WOLFSSL_DEBUG_CODEPOINTS` gates,

add `WOLFSSL_MSG_EX2()`, `WOLFSSL_MSG2()`, `WOLFSSL_ENTER2()`, and `WOLFSSL_LEAVE2()`, each with file and line args,

and add wrapper macros for `WOLFSSL_MSG`, `WOLFSSL_MSG_EX`, `WOLFSSL_ENTER`, and `WOLFSSL_LEAVE`, that pass in file and line.

example output, from `unit.test -test_wolfSSL_SESSION`:
```
starting unit tests...
 Begin API Tests
[src/ssl.c L 5594] wolfSSL Entering wolfSSL_Init
[wolfcrypt/src/wc_port.c L 146] wolfSSL Entering wolfCrypt_Init
[wolfcrypt/src/random.c L 2249] RNG_HEALTH_TEST_CHECK_SIZE = 128
[wolfcrypt/src/random.c L 2251] sizeof(seedB_data)         = 128
[wolfcrypt/src/random.c L 3995] opened /dev/urandom.
[wolfcrypt/src/random.c L 4009] rnd read...
   643: test_wolfSSL_SESSION                                :[src/tls.c L 15280] wolfSSL Entering TLSv1_2_client_method_ex
[src/ssl.c L 1031] wolfSSL Entering wolfSSL_CTX_new_ex
[./src/ssl_certman.c L 91] wolfSSL Entering wolfSSL_CertManagerNew
[./src/ssl_certman.c L 93] heap param is null
[./src/ssl_certman.c L 99] DYNAMIC_TYPE_CERT_MANAGER Allocating = 368 bytes
[...]
```

2024-06-15 22:21 UTC, douzzer commented
retest this please

2024-06-17 23:19 UTC, SparkiDev requested changes

2024-06-17 23:19 UTC, SparkiDev commented on wolfcrypt/src/logging.c
> +    const int logLevel,
Don't put arguments on different lines.

2024-06-17 23:19 UTC, SparkiDev commented on wolfcrypt/src/logging.c
> +    const char *file_name,
=> const char* file_name,

2024-06-18 04:35 UTC, douzzer commented on wolfcrypt/src/logging.c
> +#ifdef WOLFSSL_DEBUG_CODEPOINTS
They're all public APIs, so we're stuck with defining and exporting them as-is.

The `WOLFSSL_DEBUG_CODEPOINTS` wrapper macros are always disabled in application anyway -- applications will use the existing public APIs.

2024-06-18 04:38 UTC, douzzer commented on wolfcrypt/src/logging.c
> +    const int logLevel,
fixed

2024-06-18 04:42 UTC, douzzer commented on wolfcrypt/src/logging.c
> +    const char *file_name,
fixed

2024-06-18 08:37 UTC, SparkiDev approved these changes

2024-06-18 08:37 UTC, merged