Sni csharp wrapper patch
wolfSSL/wolfssl pull request #7692
Opened 2024-06-27 15:03 UTC by gasbytes

# Description

Fixes zd#17990

# Testing

server:
```
mcs wolfSSL_CSharp/wolfSSL.cs wolfSSL_CSharp/X509.cs \
wolfSSL-TLS-Server/wolfSSL-TLS-Server.cs -OUT:server.exe
```
client:
```
mcs wolfSSL_CSharp/wolfSSL.cs wolfSSL_CSharp/X509.cs \
wolfSSL-TLS-Client/wolfSSL-TLS-Client.cs -OUT:client.exe
```

# Checklist

 - [x ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2024-06-27 15:08 UTC, dgarske requested changes

2024-06-27 15:08 UTC, dgarske commented on wrapper/CSharp/wolfSSL-TLS-Server/wolfSSL-TLS-Server.cs
> +        if (wolfssl.read(ssl, buff, 1024) < 0)
The point of reading 1023 is to leave a null terminator. Buff is 1024, so this is 1024-1. We use this same pattern in a few of the examples.

2024-06-27 15:08 UTC, dgarske commented on wrapper/CSharp/wolfSSL-TLS-Server/wolfSSL-TLS-Server.cs
> +            byte [] buffer = { /* www.paypal.com */
Please avoid the full link, just say from PayPal website client hello. Is there a reason you didn't use our own or something not money related like google.com?

2024-06-27 15:34 UTC, dgarske approved these changes
Looks good! Please get customer feedback. You’re welcome to put this PR into non-draft

2024-07-02 22:49 UTC, JacobBarthelmeh approved these changes

2024-07-02 22:49 UTC, merged