ocsp stapling improvements
wolfSSL/wolfssl pull request #7702
Opened 2024-07-01 23:59 UTC by rizlik

# Description

Improvements of OCSP stapling response handling

2024-07-02 19:31 UTC, dgarske commented
Retest this please

2024-07-03 08:39 UTC, rizlik commented
Retest this please

2024-07-03 17:14 UTC, JacobBarthelmeh requested changes

2024-07-03 17:14 UTC, JacobBarthelmeh commented on wolfcrypt/src/asn.c
> +    return ParseCertRelativeEx(cert, type, verify, cm, NULL);
For local functions I prefer not to have an Ex version (reduces call stack if we can just change it).

2024-07-04 08:36 UTC, rizlik commented on src/internal.c
> +                            FreeDecodedCert(&dCertAdd);
good find! Thanks

2024-07-05 01:28 UTC, JacobBarthelmeh approved these changes

2024-07-05 13:45 UTC, julek-wolfssl approved these changes

2024-07-05 13:45 UTC, julek-wolfssl commented on src/ocsp.c
> +    }
tab++

2024-07-05 15:33 UTC, JacobBarthelmeh approved these changes

2024-07-05 16:29 UTC, merged