`InitSuites` changes to order making `BUILD_TLS_AES_256_GCM_SHA384` be prioritized over `BUILD_TLS_AES_128_GCM_SHA256`
wolfSSL/wolfssl pull request #7771
Opened 2024-07-19 20:38 UTC by aidangarske

# Description 

`internal.c` - `InitSuites` changes to order making `BUILD_TLS_AES_256_GCM_SHA384` be prioritized over `BUILD_TLS_AES_128_GCM_SHA256` to match TLS 1.2 order. 
-fix for test `quic.c`, `api.c`, and `test.h` hard coded size assumption. 
-fix `ssl.c` TRUE/FALSE to 1/0. 

# Testing

```
./configure --enable-all --enable-debug --disable-shared 
make
make check
```

2024-07-19 21:30 UTC, dgarske commented
Retest this please

2024-07-24 22:55 UTC, SparkiDev requested changes

2024-07-24 22:55 UTC, SparkiDev commented on tests/api.c
> +    byte server_side_msg1[WC_MAX_DIGEST_SIZE] = {0};/* msg sent by server */
Initialization like that isn't always reliable.
Make sure an XMEMSET is done.

2024-11-19 00:09 UTC, SparkiDev approved these changes

2024-11-19 00:38 UTC, dgarske approved these changes
Please fix the Python patch in OSP to support either 32 or 48 for now. Once that is pushed through we can merge this one

2024-11-22 00:31 UTC, dgarske commented
Retest this please. Python test should pass now.

2024-11-22 02:28 UTC, dgarske commented
Retest this please. Generic config “ FAIL scripts/openssl.test ”

2024-11-22 17:13 UTC, JacobBarthelmeh approved these changes

2024-11-22 17:15 UTC, merged

2024-12-06 17:21 UTC, hholzgra commented
See also: https://jira.mariadb.org/browse/MDEV-35579