Kyber fixes
wolfSSL/wolfssl pull request #7773
Opened 2024-07-22 10:07 UTC by Frauschi

Hi all,

this PR fixes two problems regarding the WolfSSL implementation of Kyber:
* Make sure the source files are included when using CMake
* Include source files in the Zephyr port
* Fix compilation issue when liboqs is also enabled ('`ext_kyber.c` code is disabled)

2024-07-22 12:41 UTC, embhorn commented
@Frauschi is an approved contributor

2024-07-22 14:15 UTC, dgarske submitted a review, later dismissed

2024-07-22 22:18 UTC, SparkiDev requested changes

2024-07-22 22:18 UTC, SparkiDev commented on cmake/functions.cmake
> +              list(APPEND LIB_SOURCES wolfcrypt/src/wc_kyber_poly.c)
Intel ASM: wc_keyber_asm.S?

2024-07-23 14:33 UTC, Frauschi commented on cmake/functions.cmake
> +              list(APPEND LIB_SOURCES wolfcrypt/src/wc_kyber_poly.c)
fixed

2024-07-23 22:30 UTC, SparkiDev approved these changes

2024-07-24 07:59 UTC, Frauschi commented
After some more testing of the Intel ASM addition, I found two other bugs in the CMake `functions.cmake` code: Both `BUILD_INTELASM` and `BUILD_ARMASM` have been misspelled in some places (`BUILD_INTEL_ASM` and `BUILD_ARM_ASM`; I also used the incorrect one in my initial fix yesterday), leading to the two options having no effect in CMake builds. 

I integrated the fixes for that into this PR, hoping that this is ok.

2024-07-24 10:27 UTC, SparkiDev approved these changes

2024-07-24 14:30 UTC, dgarske approved these changes

2024-07-24 14:37 UTC, merged