Allow kyber to be built with FIPS
wolfSSL/wolfssl pull request #7788
Opened 2024-07-25 00:38 UTC by anhu

Tried it with fips-ready.  No problems.

2024-07-25 20:22 UTC, anhu commented
retest this please

2024-07-25 21:00 UTC, anhu commented
Requesting @SparkiDev have a look as I don't understand why it was done in the first place.

2024-07-29 07:38 UTC, SparkiDev requested changes

2024-07-30 23:04 UTC, SparkiDev approved these changes

2024-07-30 23:04 UTC, merged