`api.c` and `asn.c` changes to allow 0 to be passed in and expanded coverage on test cases.
wolfSSL/wolfssl pull request #7791
Opened 2024-07-25 15:21 UTC by aidangarske

# Description

`api.c` and `asn.c` changes to allow 0 to be passed in and expanded coverage on test cases.

# Testing

```
./configure --enable-all --enable-wolfclu  --enable-debug --disable-shared 
make 
make check 
```

2024-07-25 15:29 UTC, dgarske requested changes

2024-07-25 15:29 UTC, dgarske commented on wolfcrypt/src/asn.c
> +        return BUFFER_E;
These are mixed up. This should be `BAD_FUNC_ARG` and below `BUFFER_E`

2024-07-25 16:09 UTC, dgarske approved these changes

2024-07-25 17:09 UTC, dgarske commented
Retest this please

2024-07-25 19:08 UTC, dgarske commented
Retest this please. openssl.test failed on generic config.

2024-07-28 23:40 UTC, SparkiDev approved these changes

2024-07-28 23:40 UTC, merged