SSL asynchronous read/write and encrypt
wolfSSL/wolfssl pull request #7796
Opened 2024-07-26 04:15 UTC by SparkiDev

# Description

Add support for being able to read and write in different threads with same SSL object.
Add support for encrypt in threads.

# Testing

How did you test?

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2024-07-29 14:24 UTC, bandi13 commented
retest this please

2024-09-03 00:01 UTC, SparkiDev commented
retest this please

2024-10-15 16:51 UTC, douzzer requested changes
rebase conflicts after merge of #8064

2024-10-17 05:05 UTC, douzzer approved these changes

2024-10-17 05:05 UTC, merged