Dilithium: fix check hint
wolfSSL/wolfssl pull request #7803
Opened 2024-07-29 00:54 UTC by SparkiDev

# Description

When all indeces are 0, then don't check hints against indeces.

# Testing

./configure '--disable-shared' '--enable-experimental' '--enable-dilithium'
valgrind ./tests/unit.test -test_wc_dilithium_verify
(new test case in test_wc_dilithium_verify() will have buffer overrun without fix)

# Checklist

 - [x] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2024-07-29 02:13 UTC, SparkiDev commented
retest this please

2024-07-29 02:28 UTC, SparkiDev commented
retest this please

2024-07-29 14:22 UTC, bandi13 commented
retest this please

2024-08-05 18:55 UTC, dgarske approved these changes

2024-08-05 19:22 UTC, douzzer requested changes
not passing unit test (see the build config below):
```
   284: test_wc_dilithium_der                               :
ERROR - tests/api.c line 33410 failed with:
    expected: wc_Dilithium_PrivateKeyToDer(key , ((void *)0), 0 ) == BAD_FUNC_ARG
    result:   2590 != -173
```
The test, both before and after the PR, is also rendering a slew of hex digits to stdout:
```


    0xc5, 0x57, 0x8b, 0x6b, 0x17, 0x21, 0xcb, 0x73,
    0xcf, 0xc7, 0x0b, 0xe6, 0x81, 0x5c, 0x63, 0xf0,
[...]
 failed (  0.00398)

ERROR - tests/api.c line 85884 failed with:
    expected: Test failed
```

config (from multi-test `quantum-safe-wolfssl-all-gcc-latest`):
```
'--enable-all' '--enable-testcert' '--enable-srtp' '--enable-intelasm' '--enable-sp-asm' '--enable-experimental' '--enable-kyber' '--enable-lms' '--enable-xmss' '--enable-dilithium' '--disable-qt' 'CPPFLAGS=-DNO_WOLFSSL_CIPHER_SUITE_TEST -DWOLFSSL_OLD_PRIME_CHECK -pedantic'
```

2024-08-06 15:25 UTC, douzzer approved these changes

2024-08-06 15:25 UTC, merged