Compile flag to not include system headers
wolfSSL/wolfssl pull request #7813
Opened 2024-07-30 23:54 UTC by SparkiDev

# Description

Some builds don't require system headers: crypto only and single threaded.
WOLFSSL_NO_SYSTEM_HEADERS stops wolfSSL including system headers.

# Testing

./configure '--disable-shared' '--enable-cryptonly' 'CFLAGS=-DWOLFSSL_NO_SYSTEM_HEADERS' '--enable-singlethreaded'

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2024-07-31 00:34 UTC, SparkiDev commented
retest this please

2024-08-01 18:12 UTC, dgarske requested changes
I believe this would be solved with `SINGLE_THREADED` and `NO_FILESYSTEM`. Which headers were being included? What use case is this solving? Is it tied to a support ticket?

For example I still see:

types.h:
```
#else /* fallback to architecture size_t for pointer size */
    #include <stddef.h> /* included for getting size_t type */
    typedef size_t wc_ptr_t;
```

types.h:
```
#else
                #include <stdio.h>
                #define XSNPRINTF snprintf
```

Also had to add `-DWOLFSSL_NO_ATOMICS` to get rid of atomics `#include <stdatomic.h>`.

Just to name a few. I was able to use `-save-temps=obj` to see the headers getting pulled in.

2024-08-01 22:59 UTC, SparkiDev commented
The customer didn't open a PR, it is part of the Dilithium work.

My concern was that we include other system headers in the alternate branches that aren't related to threading and filesystem. Excluding all system headers is what they want to do.

Would you rahter I changed the condition to single threaded and no filesyetem?

2024-08-02 15:40 UTC, dgarske commented
> The customer didn't open a PR, it is part of the Dilithium work.
> 
> My concern was that we include other system headers in the alternate branches that aren't related to threading and filesystem. Excluding all system headers is what they want to do.
> 
> Would you rahter I changed the condition to single threaded and no filesyetem?

The else case at the bottom already guards on single_threaded and no_filesystem. Are you seeing something besides the else case like USE_WINDOWS_API? If so I think you should just change it to gate this section on those two macros instead of introducing a new macro.

2024-08-05 00:32 UTC, SparkiDev commented
Changed code to not try to include header files when single threaded and no filesystem.

2024-08-05 17:11 UTC, dgarske approved these changes

2024-08-05 17:49 UTC, dgarske approved these changes

2024-08-05 18:32 UTC, merged