No if xfree
wolfSSL/wolfssl pull request #7839
Opened 2024-08-06 14:59 UTC by bandi13

Remove 'if(ptr)' check before 'XFREE(ptr)'

2024-08-06 17:20 UTC, bandi13 commented
retest this please. Just a random test failure:
```
Client message: hello wolfssl!
I hear you fa shizzle!
trying server command line[1193]: SuiteTest -v 4 -l TLS13-AES128-GCM-SHA256 -2 -p 0 
repeating test without extended master secret
trying client command line[1194]: SuiteTest -v 4 -l TLS13-AES128-GCM-SHA256 -F 1 -2 -n -p 36085 
FAIL scripts/unit.test (exit status: 1)
<<<
Error: Test runtime=91sec. Make Check RESULT = 2
Exiting with status: 1
Script ran for 269 seconds.
script returned exit code 1
```

2024-08-06 17:22 UTC, dgarske requested changes
Please make sure all XFREE macros definitions have the `if()` check and clearly document this in that area of the headers. Its already a rule and I'm glad we are getting consistent with this, but let's document all `#define XFREE` examples.

2024-08-06 18:52 UTC, dgarske approved these changes

2024-08-06 22:02 UTC, SparkiDev requested changes

2024-08-06 22:02 UTC, SparkiDev commented on wolfcrypt/src/sp_arm32.c
> +    XFREE(td, NULL, DYNAMIC_TYPE_TMP_BUFFER);
This code is generated.
I'll have to go back and change the scripts to produce this code.

2024-08-07 20:23 UTC, douzzer requested changes
`quantum-safe-wolfssl-all-clang-tidy` found something to complain about:
```
[quantum-safe-wolfssl-all-clang-tidy] [22 of 32] [a31d8c5ce7]
    configure...   real 0m26.333s  user 0m11.293s  sys 0m16.875s
    build...d350ba6c41 (<andras@wolfssl.com> 2024-08-06 10:44:59 -0400 7938)     XFREE(s1, key->heap, DYNAMIC_TYPE_DILITHIUM);
/tmp/tmp.4346_12509/wolfssl_test_workdir.35142/wolfssl/wolfcrypt/src/dilithium.c:7938:5: warning: Access to field 'heap' results in a dereference of a null pointer (loaded from variable 'key') [clang-analyzer-core.NullDereference]
7938 |     XFREE(s1, key->heap, DYNAMIC_TYPE_DILITHIUM);
|     ^
[...]
```

2024-08-07 20:42 UTC, douzzer requested changes
`clang-tidy-asn-template-sp-all-small-stack` found a similar defect in `rsa.c`:
```
[clang-tidy-asn-template-sp-all-small-stack] [32 of 32] [a31d8c5ce7]
    configure...   real 0m26.067s  user 0m11.164s  sys 0m16.735s
    build...d350ba6c41 (<andras@wolfssl.com> 2024-08-06 10:44:59 -0400 5084)     XFREE(p, key->heap, DYNAMIC_TYPE_RSA);
/tmp/tmp.4346_12509/wolfssl_test_workdir.35142/wolfssl/wolfcrypt/src/rsa.c:5084:5: warning: Access to field 'heap' results in a dereference of a null pointer (loaded from variable 'key') [clang-analyzer-core.NullDereference]
5084 |     XFREE(p, key->heap, DYNAMIC_TYPE_RSA);
|     ^
[...]
```

2024-08-07 22:04 UTC, douzzer approved these changes

2024-08-07 22:08 UTC, merged