RX72N support update
wolfSSL/wolfssl pull request #7849
Opened 2024-08-08 09:45 UTC by miyazakh

Revert 2b4acf5027a165e93e53858035e62c017011c706
Fix compile failure when no TSIP uses

# Description
TSIP random generator is not true random generator, but it generates pseudo random based on AES CTR-DRBG. So, it needs to use CUSTOM_RAND_GENERATE_BLOCK.

fix build failure when no using TSIP
 this fixes zd#18415(#4 item, TIME_OVERRIDES define)

zd#18415

# Testing

Run RX72N example programs

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2024-08-08 13:04 UTC, dgarske approved these changes

2024-08-09 14:19 UTC, dgarske requested changes

2024-08-09 14:19 UTC, dgarske commented on wolfcrypt/src/random.c
> -#elif defined(WOLFSSL_RENESAS_TSIP)
I don't want this removed. I added it back for a customer in ZD 18222. The TSIP RNG comes out of a CTR-DRBG but there is no issue using it as a seed for our DRBG. If a customer wants to use it directly then they can still define `CUSTOM_RAND_GENERATE_BLOCK` to override our DRBG and use `wc_tsip_GenerateRandBlock` directly.

2024-08-09 21:46 UTC, miyazakh commented
Added comment to `CUSTOM_RAND_GENERATE_BLOCK` use
Put back the RNG changes

2024-08-09 22:04 UTC, dgarske approved these changes

2024-08-12 23:26 UTC, douzzer approved these changes

2024-08-12 23:26 UTC, merged