libspdm x509 parts
wolfSSL/wolfssl pull request #7869
Opened 2024-08-14 09:48 UTC by julek-wolfssl

2024-08-19 09:54 UTC, julek-wolfssl commented
Failures (not sure about `fips-ready-config`) not related to PR.

2024-08-23 22:15 UTC, douzzer commented
retest this please

2024-09-02 06:27 UTC, douzzer requested changes
found some minor stuff.

2024-09-02 08:02 UTC, julek-wolfssl commented on wolfcrypt/test/test.c
> +        if (EVP_CIPHER_CTX_block_size(NULL) != WOLFSSL_FAILURE)
Fixed

2024-09-02 08:02 UTC, julek-wolfssl commented on wolfcrypt/test/test.c
> +        if (EVP_CIPHER_block_size(NULL) != WOLFSSL_FAILURE)
Fixed

2024-09-02 08:02 UTC, julek-wolfssl commented on wolfcrypt/test/test.c
> +        if (EVP_CIPHER_CTX_set_padding(NULL, 0) != WOLFSSL_FAILURE)
Fixed

2024-09-04 01:09 UTC, douzzer approved these changes

2024-09-04 01:09 UTC, merged