Add conditional repository_owner to workflow
wolfSSL/wolfssl pull request #7871
Opened 2024-08-14 15:55 UTC by gojimmypi

# Description

This PR adds a workflow condition to only run the workflow on wolfssl-owned repositories (in this case, [async.yml](https://github.com/wolfSSL/wolfssl/compare/master...gojimmypi:wolfssl:pr-repo-owner-check?expand=1#diff-0a009bf1c1ebe9e868237e406808864f41ee3af04b3b371e70a86a1f5a53027d)). I propose doing this on all workflows, but this PR is only for the first one to open a discussion and code review. I'm happy to make the changes for others.

Why?

I've recently begun implementing automated Espressif CI testing. One of the things that has been annoying and even problematic has been all the upstream workflows running in my fork, such as this sync from upstream:

![image](https://github.com/user-attachments/assets/daff7acc-ef74-4b68-983b-2aeada39481f)

Worse, some of them appear to never stop:

![image](https://github.com/user-attachments/assets/fcd75187-990f-4efa-8d05-670ccde2fd23)

Although I think that's actually a GitHub bug, as the ones from last month are not actually running:

![image](https://github.com/user-attachments/assets/7922729b-7036-4be3-9307-584ed51d72b7)

Fixes zd# n/a

# Testing

How did you test?

not tested.

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2024-08-14 16:57 UTC, gojimmypi commented
Update: thanks @julek-wolfssl for the tip on [manually disabling workflows](https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/disabling-and-enabling-a-workflow) in a fork. That works, but I found it rather unintuitive. 

I still think it's a good idea to not run all the upstream workflows by default. We could have contributors that may be time-limited on computing power or something. It just seems to be a waste. Thoughts?

2024-08-14 16:58 UTC, gojimmypi commented
Jenkins retest this please

2024-08-14 22:10 UTC, julek-wolfssl requested changes
I don't think this is a good way to do this. Its still going to run just result in errors. This also adds unnecessary and unintuitive clutter to the actions. If you really want to I'm sure there is a way to disable the actions through the gh api and run that as cron job.

2024-08-20 08:26 UTC, julek-wolfssl submitted a review, later dismissed
I've been persuaded that this may have some merit.

2024-09-23 18:36 UTC, gojimmypi commented
## Conditional Updates

After a discussion with @bandi13 I've updated _all_ the wolfSSL workflows to conditionally run on:

```
if: github.repository_owner == 'wolfssl'
```

This condition was generally placed between the `name:` and `runs-on:` keywords.

## socat_check update
I noticed a syntax highlighting error for the `socat_check` strategy (none was defined), so I removed it.

![image](https://github.com/user-attachments/assets/8b9a8fc6-ef44-4626-8eb5-772989b737f2)

2024-09-26 15:29 UTC, JacobBarthelmeh commented
@bandi13 please review these changes to github action tests

2024-09-26 16:18 UTC, merged