Feature/multiple aes siv ads
wolfSSL/wolfssl pull request #7911
Opened 2024-08-28 09:48 UTC by ptsiewie

# Description

The AES SIV algorithm implementation in WolfSSL would accept only exactly one vector of associated data, even though the definition of the algorithm of RFC5297 allows any number no larger than 126.

Fixes zd#18509

# Testing

The tests in test.c have been extended to include the two examples given in the RFC5297 document. The second of these two examples uses two ADs.

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2024-08-28 14:55 UTC, dgarske commented
Okay to test. Contributor agreement in progress.

2024-08-28 14:59 UTC, dgarske requested changes
Over to @wolfssl-bot and @SparkiDev for further review. Thank you for adding a test case.

2024-08-28 14:59 UTC, dgarske commented on wolfcrypt/src/aes.c
> +        for(word32 ai = 0; ai < numAssoc; ++ai) {
For portability please declare `word32 ai` on line above. Code consistency please use `for (` add space.

2024-08-28 14:59 UTC, dgarske commented on wolfcrypt/src/aes.c
> +    const AesSivAssoc ad0 = { .assoc = assoc, .assocSz=assocSz };
This syntax is not very portable. Please use:
```
AesSivAssoc ad0;
ad0.assoc = assoc;
ad0.assocSz = assocSz;
```

2024-08-29 14:53 UTC, dgarske commented
Okay to test. Contributor agreement in progress. @ptsiewie sorry for the delay in getting your agreement approved. Expect it next week.

2024-08-29 14:54 UTC, dgarske submitted a review, later dismissed
Feature looks good to me. @SparkiDev please review. Also should we wrap any of this new SIV support in a new build macro?

2024-08-29 22:40 UTC, SparkiDev submitted a review, later dismissed

2024-08-29 22:40 UTC, SparkiDev commented
retest this please

2024-08-29 22:41 UTC, SparkiDev commented
The old API goes through the new API so we will always include code.

2024-08-29 22:56 UTC, SparkiDev commented
Hi @ptsiewie 

Errors in ctidy check

TLDR: change '1u' to '1U'

Error:
 shellcheck configure.../var/lib/jenkins/workspace/PRB-multi-test-script/wolfssl/wolfcrypt/src/aes.c:13850:43: warning: integer literal has suffix 'u', which is not uppercase [readability-uppercase-literal-suffix]
return AesSivCipher(key, keySz, &ad0, 1u, nonce, nonceSz, in, inSz,
^~
U
/var/lib/jenkins/workspace/PRB-multi-test-script/wolfssl/wolfcrypt/src/aes.c:13864:43: warning: integer literal has suffix 'u', which is not uppercase [readability-uppercase-literal-suffix]
return AesSivCipher(key, keySz, &ad0, 1u, nonce, nonceSz, in, inSz,
^~
U

2024-08-30 18:43 UTC, dgarske commented
Okay to test. Retest this please

2024-08-30 18:44 UTC, dgarske commented
Reminder, contributor agreement in progress, but not yet approved. Person needed for that is on vacation this week.

2024-09-10 00:10 UTC, dgarske commented
Contributor agreement approved and on file. Thank you @ptsiewie!

2024-09-10 00:36 UTC, SparkiDev approved these changes

2024-09-10 02:23 UTC, dgarske approved these changes

2024-09-12 10:58 UTC, ptsiewie commented
Do I need to do something before this branch will be merged?

2024-09-12 14:55 UTC, merged