Type conversion fixes
wolfSSL/wolfssl pull request #7918
Opened 2024-08-29 07:56 UTC by SparkiDev

# Description

Changes to get compilation with -Wconversion passing on the files.

# Testing

./configure --disable-shared --enable-all CFLAGS=-Wconversion
Compile the files changed only.

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2024-08-29 09:02 UTC, SparkiDev commented
retest this pleae

2024-08-29 23:07 UTC, SparkiDev commented
retest this please

2024-08-30 00:46 UTC, SparkiDev commented
retest this please

2024-08-31 05:23 UTC, douzzer requested changes
Good amount of progress here, though of course it would be nicer if we just had self-consistent types in the first place, rather than an armada of casts to support legacy code and API signatures.

checkpoint for the record: on a default build of this PR, I count 150 remaining `-Wconversions` in the TLS layer, 39 in `api.c`, and 28 in the crypto layer, all but 2 in `test.c`.  (and I've noted those 2 in my review.)

2024-08-31 05:23 UTC, douzzer commented on wolfcrypt/src/pkcs7.c
> +    pkcs7->encodeStream = (flag == 1);
`!= 0`

2024-08-31 05:23 UTC, douzzer commented on wolfcrypt/src/pkcs7.c
> +    pkcs7->noCerts = (flag == 1);
`!= 0`

2024-08-31 05:23 UTC, douzzer commented on wolfcrypt/src/pkcs7.c
>                          ret = wc_AesGcmEncrypt(aes, out, in, inSz, iv, ivSz,
I'm seeing
```
wolfcrypt/src/pkcs7.c:8207:62: error: conversion to 'word32' {aka 'unsigned int'} from 'int' may change the sign of the result [-Werror=sign-conversion]
 8207 |                         ret = wc_AesGcmEncrypt(aes, out, in, inSz, iv, ivSz,
      |                                                              ^~~~
wolfcrypt/src/pkcs7.c:8207:72: error: conversion to 'word32' {aka 'unsigned int'} from 'int' may change the sign of the result [-Werror=sign-conversion]
 8207 |                         ret = wc_AesGcmEncrypt(aes, out, in, inSz, iv, ivSz,
      |                                                                        ^~~~
```

2024-09-02 09:19 UTC, SparkiDev commented on wolfssl/wolfcrypt/asn.h
> +            if ((asn)[ii].depth <= (asn)[(node)].depth)                \
fixed

2024-09-02 09:19 UTC, SparkiDev commented on wolfssl/wolfcrypt/asn.h
> +            if ((asn)[ii].depth <= (asn)[(node)].depth)                \
fixed

2024-09-02 09:20 UTC, SparkiDev commented on wolfssl/wolfcrypt/asn.h
> +    (dataASN)->data.buffer.data = OidFromId((oid), (oidType),          \
fixed

2024-09-02 09:20 UTC, SparkiDev commented on wolfcrypt/src/pkcs7.c
> +    pkcs7->detached = (flag == 1);
fixed

2024-09-02 09:20 UTC, SparkiDev commented on wolfcrypt/src/pkcs7.c
> +            pkcs7->stream->degenerate = (degenerate == 1);
fixed

2024-09-02 09:20 UTC, SparkiDev commented on wolfcrypt/src/pkcs7.c
> +                            pkcs7->stream->multi         = (multiPart == 1);
fixed

2024-09-02 09:20 UTC, SparkiDev commented on wolfcrypt/src/pkcs7.c
> +                        pkcs7->stream->multi         = (multiPart == 1);
fixed

2024-09-02 09:20 UTC, SparkiDev commented on wolfcrypt/src/pkcs7.c
> +            pkcs7->stream->detached = (detached == 1);
fixed

2024-09-02 09:20 UTC, SparkiDev commented on wolfcrypt/src/pkcs7.c
> +                        pkcs7->contentIsPkcs7Type = (contentIsPkcs7Type == 1);
fixed

2024-09-02 09:20 UTC, SparkiDev commented on wolfcrypt/src/pkcs7.c
> +    pkcs7->encodeStream = (flag == 1);
fixed

2024-09-02 09:20 UTC, SparkiDev commented on wolfcrypt/src/pkcs7.c
> +    pkcs7->noCerts = (flag == 1);
fixed

2024-09-02 10:26 UTC, SparkiDev commented
retest this please

2024-09-04 01:17 UTC, douzzer approved these changes

2024-09-04 01:18 UTC, merged