Fix conversion in ssl* files and in internal.c
wolfSSL/wolfssl pull request #7946
Opened 2024-09-05 13:55 UTC by gasbytes

Fix issues related to -Wconversion and -Wsign-conversion in the ssl* files and in internal.c.

2024-09-05 14:13 UTC, bandi13 requested changes
Please go through and check if the variable declaration type should be changed instead of being cast.

2024-09-05 14:13 UTC, bandi13 commented on src/internal.c
> +    *pKey = (void *)XMALLOC((size_t)sz, ssl->heap, type);
Better to change the type of the variable declaration.

2024-09-05 14:13 UTC, bandi13 commented on src/internal.c
> +        ssl->buffers.outputBuffer.idx += (word32)sent;
Change variable type instead

2024-09-05 14:13 UTC, bandi13 commented on src/internal.c
> +    tmp = (byte*)XMALLOC((size_t)(size + usedLength + align),
I wonder if it is possible to change the function input variable types

2024-09-05 14:13 UTC, bandi13 commented on src/internal.c
> +        dataSz -= (word32)ivExtra;
Change variable type instead

2024-09-05 14:13 UTC, bandi13 commented on src/internal.c
> +        idx += (word32)rawSz;
Change variable type instead

2024-09-05 19:51 UTC, bandi13 approved these changes

2024-09-06 21:13 UTC, douzzer approved these changes

2024-09-06 21:13 UTC, merged