add option to set custom SKID with PKCS7 bundle creation
wolfSSL/wolfssl pull request #7954
Opened 2024-09-06 22:31 UTC by JacobBarthelmeh

ZD 18401

2024-09-18 06:08 UTC, SparkiDev submitted a review, later dismissed

2024-09-18 18:01 UTC, dgarske approved these changes

2024-09-18 18:08 UTC, dgarske requested changes

2024-09-18 18:08 UTC, dgarske commented on tests/api.c
> +        wc_InitRng(&rng);
Should return code be checked here?

2024-09-18 18:08 UTC, dgarske commented on tests/api.c
> +        byte customSKID[] = {
Can this be `const`?

2024-09-21 00:05 UTC, dgarske approved these changes

2024-09-21 00:05 UTC, merged