Check if it has been defined before defining _GNU_SOURCE
wolfSSL/wolfssl pull request #7958
Opened 2024-09-07 11:16 UTC by rdmark

# Description

Do a check for the `_GNU_SOURCE` macro before defining it.

Fixes #7957

# Testing

Tested by building WolfSSL 5.7.2 against Netatalk.

# Checklist

N/A

2024-09-09 14:29 UTC, dgarske commented
Okay to test. Contributor agreement in progress.

2024-09-09 15:26 UTC, dgarske commented
Retest this please:

```
dtls.txt_57
SSL_read input error -501, can't match cipher suite
client failed! Suite = DHE-RSA-AES128-SHA256 version = 3
```

2024-09-09 15:33 UTC, dgarske approved these changes
Do not merge until contributor agreement has been approved.

2024-09-10 05:51 UTC, douzzer requested changes
I assume the problem this addresses is when a system header defines `_GNU_SOURCE` to `1`, then this is undone by the code in `bio.c` and `ssl.c`.  Seems like a good fix.

I'd like to see the `#undef _GNU_SOURCE` clauses removed from inside the conditions, now that the outer gates have made them frivolous.

2024-09-10 05:51 UTC, douzzer commented on src/bio.c
>      #undef  _GNU_SOURCE
remove this now that it's frivolous

2024-09-10 05:51 UTC, douzzer commented on src/ssl.c
>      #undef  _GNU_SOURCE
here too

2024-09-12 21:41 UTC, douzzer commented
superseded by #7971

2024-09-12 21:41 UTC, closed without merging