Fix sniffer
wolfSSL/wolfssl pull request #7973
Opened 2024-09-13 17:19 UTC by bandi13

# Description
Using Linux, there is a 'linux cooked capture' layer that is added on, and the packets seem to contain two extra bytes.

# Testing
Able to read packet capture when using 'any' interface

2024-09-17 17:01 UTC, JacobBarthelmeh commented
Assigning back to @bandi13. Failing one of the sniffer tests `snifftest static RSA failed`

2024-09-23 17:38 UTC, dgarske commented on sslSniffer/sslSnifferTest/snifftest.c
> +            int ptype = pcap_datalink(pcap);
Avoid mixed-declaration. Move `int ptype` up. Also please add comment documenting what Linux SLL is and what the 2 bytes are.

2024-09-27 19:52 UTC, dgarske requested changes
Ask discussed yesterday. Works now with "any" interface, but not with "lo".

2024-10-02 17:18 UTC, bandi13 commented
retest this please

2024-10-21 15:27 UTC, dgarske requested changes
Otherwise PR looks awesome!

2024-10-21 15:27 UTC, dgarske commented on src/sniffer.c
> +        tmpPacket = (byte*)XMALLOC(length, NULL, DYNAMIC_TYPE_TMP_BUFFER);
I wonder if there is a better dynamic type like `DYNAMIC_TYPE_SNIFFER_PB_BUFFER` that could be used or maybe even a new `DYNAMIC_TYPE_SNIFFER_CHAIN_BUFFER`?

2024-10-29 20:46 UTC, dgarske approved these changes
Please squash this PR. Thanks @bandi13

2024-10-29 20:56 UTC, bandi13 commented
> Can you update the comment: "Please run directly from wolfSSL root dir".... It is no longer true.
> 
> ```
> Enter the port to scan [default: 11111, '0' for all]:
> Enter the server key [default: ../../certs/statickeys/ecc-secp256r1.pem,../../certs/statickeys/dh-ffdhe2048.pem,../../certs/statickeys/x25519.pem]:
> Enter alternate SNI [default: none]:
> Failed loading private key ../../certs/statickeys/ecc-secp256r1.pem: ret -1
> Please run directly from wolfSSL root dir
> Failed loading private key ../../certs/statickeys/dh-ffdhe2048.pem: ret -1
> Please run directly from wolfSSL root dir
> Failed loading private key ../../certs/statickeys/x25519.pem: ret -1
> Please run directly from wolfSSL root dir
> davidgarske@Davids-MacBook-Pro-2 wolfssl % pwd
> /Users/davidgarske/GitHub/wolfssl
> ```

Done, and squashed.

2024-10-29 21:22 UTC, dgarske approved these changes

2024-10-29 22:21 UTC, merged