20240917-fixes
wolfSSL/wolfssl pull request #7991
Opened 2024-09-18 21:13 UTC by douzzer

`m4/ax_atomic.m4`: fixes for C++ compatibility.

`wolfssl/wolfcrypt/wc_port.h`: add `WOLFSSL_API` attribute to `wolfSSL_Atomic_Int_Init`, `wolfSSL_Atomic_Int_FetchAdd`, and `wolfSSL_Atomic_Int_FetchAdd`, and add fallback definitions for them, allowing elimination of `SINGLE_THREADED` implementations of `wolfSSL_Ref*()`, and allowing ungated use of `wolfSSL_Atomic_*` calls in `api.c`.

`wolfcrypt/src/dh.c`: in `wc_DhAgree_ct()`, remove frivolous `XMEMSET()` and stray semicolon.

`wolfcrypt/benchmark/benchmark.c`: fix `bench_rsaKeyGen()` to skip tests of key sizes below `RSA_MIN_SIZE`, and add 4096 bit benchmark if `RSA_MAX_SIZE` is big enough.

`tests/unit.h`:
* adopt definitions of `TEST_FAIL`, `TEST_SUCCESS`, and `TEST_SKIPPED` from `unit.c`, remap `TEST_SKIPPED` from `-7777` to `3`, and add `TEST_SUCCESS_NO_MSGS`, `TEST_SKIPPED_NO_MSGS`, `EXPECT_DECLS_NO_MSGS()`, and `EXPECT_FAILURE_CODEPOINT_ID`, to support existing and future expected-particular-failure test cases without log noise.
* rename outer gate from `CyaSSL_UNIT_H` to `TESTS_UNIT_H`.

`tests/api.c`:
* use `EXPECT_DECLS_NO_MSGS()` in `test_ssl_memio_setup()`, `test_ssl_memio_read_write()`, and `test_wolfSSL_client_server_nofail_memio()`, and globally update affected expected error codes to correspond.
* use atomics for `{client,server}SessRemCount{Malloc,free}` to fix races in `SessRemCtxCb()` and `SessRemSslSetupCb()`.

tested with `wolfssl-multi-test.sh ... super-quick-check`

2024-09-19 04:32 UTC, douzzer commented
retest this please

2024-09-19 15:22 UTC, douzzer commented
retest this please

2024-09-19 21:49 UTC, SparkiDev requested changes

2024-09-19 22:07 UTC, douzzer commented on wolfcrypt/benchmark/benchmark.c
> +        static const word32  keySizes[3] = {1024, 2048, 4096 };
:heavy_check_mark:

2024-09-20 05:20 UTC, SparkiDev approved these changes

2024-09-20 05:20 UTC, merged