Support for STM32G4
wolfSSL/wolfssl pull request #7997
Opened 2024-09-19 17:56 UTC by dgarske

# Description

Support for STM32G4. ZD 18675

Synchronized the `examples/configs/user_settings_stm32.h` file with the `IDE/STM32Cube/default_conf.ftl`.

@lealem47 : For next pack release added the following new options:
* `WOLF_CONF_IO`: Network stack: 1=User IO (custom), 2=LWIP (posix), 3=LWIP (native
* `WOLF_CONF_RESUMPTION`: 0=No session cache, 1=Session cache / Session Tickets
* `WOLF_CONF_TPM`: Enable TPM support (Crypto Callbacks, Public MP and AES CFB)
* `WOLF_CONF_PK`: TLS Key Callbacks
* `WOLF_CONF_AESGCM`: AES GCM (1=GCM_SMALL, 2=GCM_TABLE_4BIT

# Testing

Built successfully in STM32CubeIDE for STM32G491xx, but do not have hardware to test on.
Tested build with RTC, RNG, LPUART1 and ARM ASM.

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2024-09-19 19:35 UTC, lealem47 requested changes

2024-09-19 19:35 UTC, lealem47 commented on IDE/STM32Cube/default_conf.ftl
> +    #if WOLF_CONF_AESGCM == 2
This won't be hit since `WOLF_CONF_AESGCM == 1` was checked above

2024-09-19 21:53 UTC, lealem47 approved these changes

2024-09-20 20:05 UTC, JacobBarthelmeh approved these changes

2024-09-20 20:05 UTC, merged