remove undef LARGE_HASH_TEST_INPUT_SZ
wolfSSL/wolfssl pull request #8049
Opened 2024-10-08 18:56 UTC by gojimmypi

# Description

The `LARGE_HASH_TEST_INPUT_SZ` may be used later in `test.c` (see line 4130, inside `#ifndef NO_UNALIGNED_MEMORY_TEST`)

Fixes zd# n/a

# Testing

Observed failure and tested only in Espressif. 

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2024-10-08 21:04 UTC, gojimmypi commented
Jenkins retest this please

2024-10-08 22:53 UTC, douzzer requested changes
These `LARGE_HASH_TEST_INPUT_SZ` definitions are context-specific, defined locally at the start of a span, and undefined when that span is done with it.  We currently have two such spans.

The right fix is either to move the `#undef` later, or add a new `#define`...`#undef` span with a value appropriate for that span.  They shouldn't be left open.

2024-10-09 02:07 UTC, gojimmypi commented
> These `LARGE_HASH_TEST_INPUT_SZ` definitions are context-specific [...] We currently have two such spans.

Any particular reason for that? Why not just have a single setting for the file? I've updated with a proposed fix. Having two same-name macros in two different places with possibly later mismatched values seems to be asking for trouble.

Happy to change it to your suggested, multi-span values if needed

2024-10-09 03:39 UTC, gojimmypi commented
Even though the Jenkins tests all passed, 2/3 of my Espressif tests are now failing. 

More investigation needed. Converted to draft. Stand by.

2024-10-09 04:41 UTC, gojimmypi commented
@douzzer could you please help me understand why there are still many `(word32)sizeof(large_input)` instances, along with the two blocks of `LARGE_HASH_TEST_INPUT_SZ`? 

The `test.c` file is too large to link directly, but there are 10 instances of:

```
#ifndef NO_LARGE_HASH_TEST
    /* BEGIN LARGE HASH TEST */ {
    byte large_input[1024];
```

See lines 3165, 3364, 4419, etc. 

Should all of these be `byte large_input[LARGE_HASH_TEST_INPUT_SZ];` ?

2024-10-09 16:02 UTC, gojimmypi commented
ok, all good here. The testing failure was on my dev branch & unrelated. Please see above questions and advise how best I should proceed.

I'm thinking it would be best to make the `#define LARGE_HASH_TEST_INPUT_SZ 1024` global in scope and change all the existing instances of `byte large_input[1024];` to instead use the defined value.

2024-10-10 04:25 UTC, douzzer commented
The `LARGE_HASH_TEST_INPUT_SZ` macros are just local coordinators for bigstack vs smallstack paths, to avoid number literals that might go out of sync in a future moment of inattention.  It happens that both neighborhoods where it's defined have it as `1024`, but that wasn't necessarily the case and might not stay the case in the future.  The macro name and values aren't intended to have any broader meaning or applicability.  They were both added earlier this year in 321a72c906, which was just a smallstack refactor PR.  That refactor, in turn, was guided by `-Wframe-larger-than=2048`, and it happens that the other instances of `byte large_input[1024]` didn't (yet) push their associated functions over the 2k limit we observe.  We fix these as needed.

2024-10-11 00:13 UTC, closed without merging

2024-10-11 01:02 UTC, gojimmypi commented
Looks like someone else also encountered this problem & fixed it. 

I pushed changes to this branch & retested. All looks well.