minor fixes for Coverity reports
wolfSSL/wolfssl pull request #8094
Opened 2024-10-21 19:38 UTC by JacobBarthelmeh

minor fixes for Coverity reports

2024-10-21 21:55 UTC, JacobBarthelmeh commented
Retest this please Jenkins. Possible network timeout: PRB-single-flag.txt_95

```
SSL curve name is SECP256R1

Unexpected server result

removing ready file: /tmp/workspace/PRB-generic-config-parser/wolfssl/tmp.l0SKcXeQK1/wolf_ocsp_s2_readyF1162286

removing ready file: /tmp/workspace/PRB-generic-config-parser/wolfssl/tmp.l0SKcXeQK1/wolf_ocsp_s2_readyF2162286

removing ready file: /tmp/workspace/PRB-generic-config-parser/wolfssl/tmp.l0SKcXeQK1/wolf_ocsp_s2_readyF3162286

removing ready file: /tmp/workspace/PRB-generic-config-parser/wolfssl/tmp.l0SKcXeQK1/wolf_ocsp_s2_readyF4162286

removing ready file: /tmp/workspace/PRB-generic-config-parser/wolfssl/tmp.l0SKcXeQK1/wolf_ocsp_s2_readyF5162286

retrying...

FAIL scripts/ocsp-stapling_tls13multi.test (exit status: 143)

<<<

Error: Test runtime=4603sec. Make Check RESULT = 2

Exiting with status: 1

Script ran for 5167 seconds.

script returned exit code 1
```

2024-10-22 06:22 UTC, JacobBarthelmeh commented on src/x509.c
> +        XFREE(dCert, x->heap, DYNAMIC_TYPE_DCERT);
thanks, I should have checked x for null here not dCert

2024-10-22 06:22 UTC, JacobBarthelmeh commented on wolfcrypt/src/aes.c
> +    #endif
likely a false positive then, I missed that the return would always be null if ret is set to nonzero

2024-10-22 20:05 UTC, douzzer requested changes

2024-10-22 20:05 UTC, douzzer commented on wolfcrypt/test/test.c
> +        ERROR_OUT(WC_TEST_RET_ENC_EC(ret), cleanup);
whoops, need to actually `return WC_TEST_RET_ENC_EC(ret)` here, since `cleanup:` will `wc_FreeRng()` unconditionally.

2024-10-23 16:16 UTC, douzzer approved these changes

2024-10-23 16:26 UTC, merged