memory: fix types in wc_LoadStaticMemory_ex()
wolfSSL/wolfssl pull request #8117
Opened 2024-10-28 16:21 UTC by rizlik

# Description

Please describe the scope of the fix or feature addition.

Fixes zd#

# Testing

How did you test?

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2024-10-28 17:44 UTC, rizlik commented
retest this please

2024-10-30 22:37 UTC, JacobBarthelmeh requested changes
There's a few more locations that need touched to make all sizeList and distList be an array of word32's 

- wolfssl/wolfcrypt/memory.h, line 222
- wolfssl/wolfcrypt/memory.h, line 260
- wolfssl/wolfcrypt/memory.h, line 284
- wolfcrypt/src/memory.c, line 672
- wolfcrypt/src/memory.c, line 820

2024-11-04 16:22 UTC, rizlik commented
> There's a few more locations that need touched to make all sizeList and distList be an array of word32's
> 
>     * wolfssl/wolfcrypt/memory.h, line 222
> 
>     * wolfssl/wolfcrypt/memory.h, line 260
> 
>     * wolfssl/wolfcrypt/memory.h, line 284
> 
>     * wolfcrypt/src/memory.c, line 672
> 
>     * wolfcrypt/src/memory.c, line 820

completely missed them. Thanks

2024-11-08 20:35 UTC, JacobBarthelmeh commented
Retest this please Jenkins. I missed capturing what the failure was.

2024-11-11 16:48 UTC, JacobBarthelmeh approved these changes

2024-11-11 16:48 UTC, merged