Implement TSIP RSA Public Enc/Private Dec
wolfSSL/wolfssl pull request #8122
Opened 2024-10-29 13:33 UTC by miyazakh

# Description

Add TSIP RSA public Encryption/Private Decryption

# Testing

Run unit test on RX72N

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2024-10-29 18:40 UTC, dgarske requested changes
```
[check-source-text] [2 of 7] [wolfssl]
trailing whitespace:
./IDE/Renesas/e2studio/RX72N/EnvisionKit/wolfssl_demo/user_settings.h:249:····
./wolfcrypt/src/port/Renesas/renesas_tsip_rsa.c:238:················
./wolfcrypt/src/port/Renesas/renesas_tsip_rsa.c:258:················
weird control chars, hard tabs, CRs, trailing whitespace:
./wolfcrypt/src/port/Renesas/renesas_common.c:262:        »(info->pk.rsa.type == RSA_PRIVATE_DECRYPT ||
./wolfcrypt/src/port/Renesas/renesas_common.c:278:        »» info->pk.rsa.type == RSA_PUBLIC_DECRYPT) {
overlong lines added:
wolfcrypt/src/port/Renesas/renesas_tsip_rsa.c:249                                                             "1024 or 2048 bits.");
wolfcrypt/src/port/Renesas/renesas_tsip_rsa.c:269                                                             "1024 or 2048 bits.");
```

2024-10-29 22:21 UTC, dgarske requested changes
```[check-source-text] [2 of 7] [wolfssl]
trailing whitespace:
./IDE/Renesas/e2studio/RX72N/EnvisionKit/wolfssl_demo/user_settings.h:249:····
    check-source-text fail_A```

2024-10-29 23:57 UTC, dgarske approved these changes
Thank you. Awaiting merge until customer provides feedback.

2024-11-04 18:44 UTC, dgarske requested changes

2024-11-04 18:44 UTC, dgarske commented on wolfcrypt/src/port/Renesas/renesas_tsip_rsa.c
> +WOLFSSL_LOCAL int wc_tsip_RsaFunction(wc_CryptoInfo* info, TsipUserCtx* tuc)
Doesn't `WOLFSSL_LOCAL int wc_tsip_RsaFunction(wc_CryptoInfo* info, TsipUserCtx* tuc);` need added to a header? Please put the WOLFSSL_LOCAL on the header, not the .c.

2024-11-05 18:18 UTC, dgarske approved these changes

2024-11-15 01:58 UTC, dgarske approved these changes

2024-11-16 22:12 UTC, douzzer approved these changes

2024-11-16 22:12 UTC, merged