Introduce IDE-FIPS directory
wolfSSL/wolfssl pull request #8126
Opened 2024-10-30 17:51 UTC by gojimmypi

# Description

Upon reconsideration after the merge of https://github.com/wolfSSL/wolfssl/pull/8090, I think it would be best to move all project files to the respective [IDE/\<environment\>](https://github.com/wolfSSL/wolfssl/tree/master/IDE) directory, out of the respective source directories such as [wolfcrypt/benchmark](https://github.com/wolfSSL/wolfssl/tree/master/wolfcrypt/benchmark).

Additionally, it may be best to isolate FIPS and non-FIPS environments.

This PR proposes a new `IDE-FIPS` for all the FIPS-related builds in preparation for the moves.

Fixes zd# n/a

# Testing

Not tested.

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2024-10-30 19:47 UTC, gojimmypi commented
Jenkins retest this please

2024-11-04 23:31 UTC, kaleb-himes approved these changes
Excellent prep work on getting the transition space ready @gojimmypi, thank you!

2024-12-17 05:26 UTC, douzzer requested changes
I think it may be an unforced error to separate FIPS from non-FIPS artifacts for a given IDE.

My thinking is that the big variable here is the IDE, not FIPSness, and we go to a lot of trouble to assure that things work the same API-wise, FIPS vs non-FIPS, modulo the reduced set of available crypto algorithms.

I could be convinced otherwise, but currently I find it more intuitive to have side-by-side FIPS and non-FIPS project files grouped under the same IDE.

2024-12-19 00:03 UTC, JacobBarthelmeh commented
Reviewed these changes. My thinking is more aligned with @douzzer on this. I also think that in most IDE projects there should not be enough of a difference between a FIPS and non-FIPS build to merit a new IDE project. Just build configuration options, possibly linker file changes and handling a couple of FIPS API calls on initialization.

2024-12-30 18:03 UTC, gojimmypi commented
After feedback, I'm closing this unmerged. We can revisit later if there are compelling reasons for separation of IDE project files.

2024-12-30 18:03 UTC, closed without merging