Curve25519 generic keyparsing
wolfSSL/wolfssl pull request #8129
Opened 2024-10-30 20:06 UTC by bigbrett

Adds API for curve25519 `der` import/export that can handle both private and public keys in one step. I realize that typically curve25519 keys are distributed as public/private only, since you can recover the public key from the private key, but this API simplifies usage for some cases in that it doesn't require multiple import attempts if you don't know at runtime what the contents of a `der` key holds. 

This API is particularly useful for wolfHSM, where the server doesn't know the contents of a `der` contain when it loads from NVM, but needs to import the key into a `curve25519_key` struct that then will have the proper public/private key fields set. The current API doesn't provide a straightforward way to do this.

Added doxygen, and will update the manual/docs once this merges

# Testing

- Added test to ensure new API can handle private only/public only keys in the same exact way as the existing API
- Added test to ensure a combined keypair import/export yields the same exported der as public/private only

# Checklist

 - [x] added tests
 - [x] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2024-10-30 22:20 UTC, dgarske approved these changes
Over to @SparkiDev

2024-10-31 00:41 UTC, SparkiDev requested changes

2024-10-31 00:41 UTC, SparkiDev commented on wolfcrypt/src/asn.c
> +    byte pubKey[CURVE25519_KEYSIZE];
CURVE25519_PUB_KEY_SIZE
(same value but more correct name)

2024-10-31 00:41 UTC, SparkiDev commented on wolfcrypt/src/asn.c
> +    byte pubKey[CURVE25519_KEYSIZE];
CURVE25519_PUB_KEY_SIZE

2024-10-31 00:41 UTC, SparkiDev commented on wolfcrypt/test/test.c
> +    /* Test decode/encode of a key file containing both public and private
key file -> key data?

2024-10-31 00:43 UTC, SparkiDev submitted a review, later dismissed

2024-10-31 00:43 UTC, SparkiDev commented on doc/dox_comments/header_files/asn_public.h
> +*/
Add \sa comments for see also.

2024-10-31 00:43 UTC, SparkiDev commented on doc/dox_comments/header_files/asn_public.h
> +int wc_Curve25519PrivateKeyDecode(const byte* input, word32* inOutIdx,
Missing examples too.

2024-10-31 19:02 UTC, bigbrett commented on wolfcrypt/src/asn.c
> +    byte pubKey[CURVE25519_KEYSIZE];
fixed

2024-10-31 19:02 UTC, bigbrett commented on wolfcrypt/src/asn.c
> +    byte pubKey[CURVE25519_KEYSIZE];
fixed

2024-10-31 19:02 UTC, bigbrett commented on wolfcrypt/test/test.c
> +    /* Test decode/encode of a key file containing both public and private
fixed

2024-10-31 19:02 UTC, bigbrett commented on doc/dox_comments/header_files/asn_public.h
> +*/
done

2024-10-31 19:02 UTC, bigbrett commented on doc/dox_comments/header_files/asn_public.h
> +int wc_Curve25519PrivateKeyDecode(const byte* input, word32* inOutIdx,
added examples

2024-10-31 19:05 UTC, bigbrett commented
@dgarske @SparkiDev addressed all feedback

2024-10-31 22:00 UTC, dgarske approved these changes

2024-10-31 23:04 UTC, SparkiDev approved these changes
Great work by the way.

2024-10-31 23:04 UTC, merged

2024-11-01 15:40 UTC, bigbrett commented
Thanks @SparkiDev!