Fix conversion on various files
wolfSSL/wolfssl pull request #8135
Opened 2024-10-31 17:59 UTC by gasbytes

These ones were linux specific (x86_64 on Void Linux).
Most of them were automated using a shell script that I wrote locally, that uses a vim interactive shell.
Working on the next block of files.

2024-11-09 06:14 UTC, douzzer submitted a review, later dismissed
rebase+reconciliation needed.
```
CONFLICT (content): Merge conflict in src/tls.c
```
looks good otherwise.

2024-11-13 13:16 UTC, gasbytes commented
retest this please

2024-11-15 01:52 UTC, dgarske commented
@gasbytes please share how you produced these conversion warnings. Which complier and what build steps. Thank you

2024-11-15 01:52 UTC, dgarske commented
@gasbytes please squash.

2024-11-15 11:18 UTC, gasbytes commented
> @gasbytes please share how you produced these conversion warnings. Which complier and what build steps. Thank you

@dgarske 
Of course, version of gcc:
```
$ gcc --version
$ gcc (GCC) 13.2.0
```

And this is the configuration:
```
$ ./config.status --config
$ --enable-all CC=gcc 'CFLAGS=-Werror -Wno-pragmas -Wall -Wextra -Wunknown-pragmas --param=ssp-buffer-size=1 -Waddress -Warray-bounds -Wbad-function-cast -Wchar-subscripts -Wcomment -Wfloat-equal -Wformat-security -Wformat=2 -Wmaybe-uninitialized -Wmissing-field-initializers -Wmissing-noreturn -Wmissing-prototypes -Wnested-externs -Wnormalized=id -Woverride-init -Wpointer-arith -Wpointer-sign -Wshadow -Wsign-compare -Wstrict-overflow=1 -Wstrict-prototypes -Wswitch-enum -Wundef -Wunused -Wunused-result -Wunused-variable -Wwrite-strings -fwrapv -Wsign-conversion -fmax-errors=1'
```

2024-11-15 14:58 UTC, dgarske approved these changes

2024-11-16 04:20 UTC, douzzer commented
has a slew of conflicts relative to current `master`:
```
CONFLICT (content): Merge conflict in configure.ac
CONFLICT (content): Merge conflict in src/ssl.c
CONFLICT (content): Merge conflict in src/tls.c
CONFLICT (content): Merge conflict in tests/quic.c
```
it's a mystery to me why github thinks "Merging can be performed automatically"...

2024-11-18 11:22 UTC, gasbytes commented
@douzzer 

I think this might be because I resolved those conflicts using GitHub's web editor, but I'm not entirely sure why GitHub now says the merge can be performed automatically. As far as I can tell, those files don’t seem to have any breaking changes compared to master, so that might also be a reason.

2024-11-19 17:02 UTC, JacobBarthelmeh submitted a review, later dismissed

2024-11-21 11:18 UTC, gasbytes commented
Retest this please (https://github.com/wolfSSL/wolfssl/pull/8182/)

2024-11-22 16:40 UTC, gasbytes commented
Working on a couple more Renesas specific.

2024-12-18 17:56 UTC, gasbytes commented
Retest this please

2024-12-20 23:47 UTC, douzzer requested changes
needs another round of rebase reconciliation:
```
CONFLICT (content): Merge conflict in wolfcrypt/src/misc.c
CONFLICT (content): Merge conflict in wolfcrypt/src/port/Renesas/renesas_fspsm_util.c
```

2024-12-21 04:52 UTC, douzzer commented
retest this please (numerous inexplicable test timeouts)

2024-12-21 05:54 UTC, douzzer requested changes
@gasbytes -- unfortunately, the history on your branch needs to be completely reset, and the changes need to be reapplied manually relative to `master`.

The problem is that you did a "Merge branch 'master' into fix-conversion", rather than a `git rebase master` that would have properly preserved the upstream history.

See the `git log` for the crazy log entry concatenating a hundred or so commit messages and attributing it to @LinuxJedi for reasons unknown.  ("200 files changed, 8520 insertions(+), 2959 deletions(-)")  That commit is not in the history of `master` and shouldn't be in it.

Also this branch now has at least one unwanted and unrelated change in it, to `configure.ac`, and you're going to need to go through the entire change set to make sure there aren't any others.

One way to fix the mess, tested locally:
```
git checkout master
git pull upstream master
git checkout fix-conversion
git reset --soft master
git diff master configure.ac | git apply --reverse
git commit -n -a
```
This will create a single new commit with all your changes except for the `configure.ac` change, directly atop current `master`, with a perfectly clean history.
 
As long as that change to `configure.ac` was the only mistaken one, that'll do the trick.

2024-12-23 20:18 UTC, gasbytes commented
Retest this please

2024-12-24 07:00 UTC, douzzer requested changes
The branch has many unintended and unwanted changes, all of them in a single commit at the head.

With the branch checked out,
```
git show --stat HEAD
```
shows the problem.
```
 280 files changed, 7111 insertions(+), 8905 deletions(-)
```

2025-02-12 22:48 UTC, dgarske commented
Consistently failing on:

```
   369: test_wolfSSL_ASN1_TIME_print                        :
ERROR - tests/api.c line 52178 failed with:
    expected: memcmp((buf),("Dec 13 22:19:28 2023 GMT"),(sizeof(buf) - 1)) == 0
    result:   5 != 0

 failed (  0.00005)

ERROR - tests/api.c line 100318 failed with:
    expected: Test failed

    result:   ret 0
```

2025-02-24 20:31 UTC, gasbytes commented
Retest this please

2025-02-24 21:39 UTC, dgarske approved these changes

2025-02-24 22:27 UTC, douzzer requested changes
Looks great!  A rebase error snuck in -- see note, re `src/ssl.c` around line 21948.

2025-02-24 22:27 UTC, douzzer commented on src/ssl.c
> +#if defined(OPENSSL_ALL) || defined(WOLFSSL_NGINX) || defined(WOLFSSL_HAPROXY)
whoops, rebase error here.

This change needs to be reverted.  Caught it with `all-crypto-openssl-extra-coexist-smallstack` (got lucky!).

A recipe to repro is
```
./configure --enable-all --disable-all-osp --disable-opensslall --enable-opensslcoexist --with-sys-crypto-policy
```

2025-02-25 10:57 UTC, gasbytes commented
Retest this please

2025-02-25 14:36 UTC, dgarske approved these changes

2025-02-25 16:01 UTC, douzzer approved these changes

2025-02-25 16:01 UTC, merged