Add support for Raspberry Pi Pico
wolfSSL/wolfssl pull request #8153
Opened 2024-11-06 16:39 UTC by LinuxJedi

# Description

This adds improved support for the Raspberry Pi Pico range of microcontrollers.

Benchmark now compiles, and added support for the RNG functions of the Pico SDK. This gives a ~2x RNG performance improvement on the RP2040 and over 3x improvement on the RP2350.

The accelerated SHA256 in the RP2350 unfortunately cannot be used with wolfSSL.

# Testing

WolfSSL-examples PR coming shortly which runs tests and benchmark.

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2024-11-06 16:58 UTC, dgarske commented
Okay to test

2024-11-06 18:53 UTC, dgarske requested changes

2024-11-06 18:53 UTC, dgarske commented on wolfcrypt/src/port/rpi_pico/pico.c
> +/* pico.c
Please add a README.md for this port and any tips for building / testing.
Please add the new files pico.c and pico.h to the include.am EXTRA_DIST.

2024-11-07 12:12 UTC, LinuxJedi commented
Rebased off master to resolve conflicts.

2024-11-07 16:44 UTC, dgarske requested changes

2024-11-07 16:44 UTC, dgarske commented on wolfcrypt/src/port/rpi_pico/README.md
> +In `settings.c` you should uncomment:
`settings.h`?. We typically don't recommend this approach. Recommendation is WOLFSSL_USER_SETTINGS and user_settings.h. The reason is making changes to settings.h causes issue with new software updates.

2024-11-07 17:24 UTC, LinuxJedi commented
Last review round of problems should now be addressed. Many thanks!

2024-11-07 17:27 UTC, LinuxJedi commented
Typo found by Codespell addressed.

2024-11-07 19:33 UTC, dgarske approved these changes

2024-11-07 19:34 UTC, dgarske commented
Okay to test.

2024-11-07 19:59 UTC, merged