Fix issues identified in TSIP on RX72N
wolfSSL/wolfssl pull request #8201
Opened 2024-11-18 23:01 UTC by gauravks

# Description

Fix issues in TSIP Decryption and Verification while testing on RX72N

# Testing

Tested on Custom RX72N board 

# Checklist

 - [ ] added tests
 - [ ] updated/added doxygen
 - [ ] updated appropriate READMEs
 - [ ] Updated manual and documentation

2024-11-18 23:15 UTC, dgarske commented
Hi @gauravks ,

Thank you for the PR and email. We will review and I'll coordinate a contributor agreement if needed directly.

Thanks,
David Garske, wolfSSL

2024-11-18 23:15 UTC, dgarske requested changes

2024-11-18 23:15 UTC, dgarske commented on wolfcrypt/src/rsa.c
> +					break;
Check indent here. Might be tabs vs. spaces.

2024-11-18 23:15 UTC, dgarske commented on wolfcrypt/src/port/Renesas/renesas_tsip_rsa.c
> +                *(info->pk.rsa.outLen) = cipher.data_length;
Same. Check indent here. Might be tabs vs. spaces.

2024-11-19 02:41 UTC, miyazakh requested changes
Thanks for the fix. I have one miner request.

2024-11-19 02:41 UTC, miyazakh commented on wolfcrypt/src/port/Renesas/renesas_tsip_rsa.c
> +        hashData.data_length = info->pk.rsa.outLen;
This should be *(info->pk.rsa.outLen) as well.

2024-11-20 21:10 UTC, dgarske commented
Thank you @gauravks . Closing in favor of https://github.com/wolfSSL/wolfssl/pull/8206 Please give the new PR a try.

2024-11-20 21:10 UTC, closed without merging