Add CID interop with mbedtls
wolfSSL/wolfssl pull request #8245
Opened 2024-12-03 15:04 UTC by julek-wolfssl

- CID now also supported in DTLS 1.2

2024-12-03 21:11 UTC, dgarske requested changes

2024-12-03 21:11 UTC, dgarske commented on .github/workflows/mbedtls.sh
> +set -e
Missing shell directive... `#!/usr/bin/env bash`

2024-12-04 17:09 UTC, dgarske approved these changes, later dismissed

2024-12-05 14:23 UTC, julek-wolfssl commented
Retest this please

2024-12-10 16:03 UTC, dgarske approved these changes

2024-12-11 14:37 UTC, rizlik approved these changes

2024-12-17 05:04 UTC, douzzer approved these changes

2024-12-17 05:04 UTC, merged