wolfSSL_CTX_set_tlsext_use_srtp() should return 1 on failure and 0 up…
wolfSSL/wolfssl pull request #8252
Opened 2024-12-04 18:02 UTC by anhu

…on success.

Same with wolfSSL_set_tlsext_use_srtp().

See https://docs.openssl.org/1.1.1/man3/SSL_CTX_set_tlsext_use_srtp/

2024-12-06 17:13 UTC, anhu commented
See https://docs.openssl.org/1.1.1/man3/SSL_CTX_set_tlsext_use_srtp/

2024-12-06 21:22 UTC, JacobBarthelmeh requested changes
We need a test case for this so a regression does not happen. Looks like simply passing null in for profile_str should trigger the failure? Could you add a call to each function in tests/api.c with a fail case to complete the fix?

2024-12-11 14:02 UTC, anhu commented
failed test: [make check (macos-latest, --enable-tls13 --enable-session-ticket --enable-dtls --enable-dtls13 --...]  Bad socket state.

2024-12-13 20:35 UTC, JacobBarthelmeh approved these changes

2024-12-13 20:35 UTC, merged