4.2.8p17 additions
wolfSSL/wolfssl pull request #8324
Opened 2024-12-31 16:22 UTC by julek-wolfssl

- OBJ_sn2nid: use correct short names
- Add MD4 to EVP layer
- Add ntp 4.2.8p17 to tested versions

2024-12-31 16:22 UTC, julek-wolfssl commented
Depends on https://github.com/wolfSSL/osp/pull/220

2025-01-10 18:13 UTC, JacobBarthelmeh requested changes

2025-01-10 18:13 UTC, JacobBarthelmeh commented on src/ssl.c
> -        sn = "SECP256R1";
Are we confident that this and also removing the check on WOLFSSL_*_NAME strings will not cause issues? Would prefer keeping the extra handling of those additional short names if possible.

2025-01-13 22:55 UTC, julek-wolfssl commented on src/ssl.c
> -        sn = "SECP256R1";
These extra names are not OpenSSL compliant. That is why I removed it to simplify the implementation.

2025-01-21 17:45 UTC, dgarske approved these changes

2025-01-21 18:02 UTC, JacobBarthelmeh approved these changes

2025-01-21 18:02 UTC, merged